### ISSUE TITLE
Europenboard.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1000]
### Dodatkowe informacje mogące mieć znaczenie
`https://europeonboard.com/` spam przekierowanie 

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Chyba za późno wychwycony URL #972.

**Comment by krystian3w** [comment]
`https://apps.apple.com/US/app/id510873505?l=en` to mi otwiera strona, Apple wywali aplikacje to i może domenę się zbanuje jako przekręt.
