### ISSUE TITLE
Uwaga na SMS-y od Biedronki i Rossmana

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1012]
https://niebezpiecznik.pl/post/uwaga-na-sms-y-od-biedronki-i-rossmana/

**Comment by hawkeye116477** [comment]
@MajkiIT A zaktualizował listę :stuck_out_tongue: ?
 https://github.com/PolishFiltersTeam/KAD/commit/326ae0b60cdacaa8394272c05afdd89f8fdf3e68

**Comment by MajkiIT** [comment]
ja nie aktualizowałem u siebie ... bo krzyczałeś na mnie 🗡

**Comment by hawkeye116477** [comment]
@MajkiIT Przed zgłoszeniem czegokolwiek należy zaktualizować listę KAD, taki opiekun listy jak ty powinien to wiedzieć.  Nie krzyczałem, tylko kulturalnie zwracałem uwagę na parę kwestii :stuck_out_tongue:.

**Comment by MajkiIT** [comment]
@hawkeye116477 ok... załapalem ... przepraszam
