### ISSUE TITLE
zalukaj.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1017]
Co myślicie o zablokowaniu zalujaj? Od kilu mają "duże obciążenie"
`https://zalukaj.com/zalukaj-film/38938/joker-2019.html
`![Zrzut ekranu z 2019-11-08 04-51-18](https://user-images.githubusercontent.com/36385327/68448360-8e9bca80-01e3-11ea-99e4-99e1b76c1026.png)

**Comment by krystian3w** [comment]
Nie?
