### ISSUE TITLE
fili.com.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1019]
### Dodatkowe informacje mogące mieć znaczenie
`https://fili.com.pl/`

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Słabe serwery / bardzo przeciążone?

**Comment by krystian3w** [comment]
A już widzę, znowu wydatek:

- Przelew 19,99 PLN
- SMS Premium 24,60 PLN
- PayPal 23,00 PLN
