### ISSUE TITLE
netfilmy.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1023]
### Dodatkowe informacje mogące mieć znaczenie
`netfilmy.pl/seriale-online/The_Mandalorian/s1e0/Zwiastun/32187`
Zapętlenie na jakieś śmieciowe strony?

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
coś im padło?

`https://leadmy.pl/inactiveprogram?program_id=51656`

**Comment by hawkeye116477** [comment]
@krystian3w Może ktoś zgłosił i ich zdjęli albo ekipa leadmy obserwuje ten wątek.
