### ISSUE TITLE
obcas.pl

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1028]
https://obcas.pl/muniek-staszczyk-wypowiedzial-sie-na-temat-dawida-podsiadlo/
dla mnie to nabijaczka informacji

**Comment by krystian3w** [comment]
No to nie czytać?

**Comment by MajkiIT** [comment]
@krystian3w co nie czytać?

**Comment by krystian3w** [comment]
No może ktoś lubi czytać o farbowaniu i perukach gwiazdy, bo nie ogląda jej na instagramie, gdzie pod sesje założyła peruka a tam zrobili teorię "spiskową" bez informacji, że ty tylko pod zdjęcie na insta.

**Comment by MajkiIT** [comment]
no wiem, tylko dla mnie to dostosowanie informacji do zdjęcia.

**Comment by xMaap** [comment]
To byś musiał zablokować całe pudelki z takim czymś.

**Comment by krystian3w** [comment]
Jak przekręcili wypowiedź, to może dałoby się podciągnąć pod fake news.

KAD raczej nie blokuje clickbaitu z miniaturami.
