### ISSUE TITLE
vodafone.com-gift-winner-lucky-day.vip

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1029]
> Szansa na wygranie Samsung Galaxy S10, Apple iPhone XS lub iPad Pro

Tylko po zamknięciu przeglądarki i wejściu ponownie na ten adres strona nie działa.

`https://vodafone.com-gift-winner-lucky-day.vip/lucky-888/PL-CC-S10/T-Mobile/index.html?brand=Apple&isp=UPC%20Polska%20Sp.%20z%20o.o.&city=Krak%C3%B3w&cep=Q28ViM4VapSzRQZ6KyE-M_INdzuWUL3BRm9BA_p2Vplr0_OVB_qzAj8lljI5DnNETFwVH6sQ6BdOU2s4cmBE9VyhqOmoNBcGOxaVEH3lLvUhLL1OQwLZTZtQgoGGi-ycj8IPTOosAEj0rbLblRE6DHZj8f9M2MjwYBEpaD9nnE59oZgtAOTHp20qoX5elsjesOefk3qjb99SwtuyJkTe9YBbf4tgMiHiElHnT8zVmUdFOy2O0-8Y-nxuZdc9N6OJMtY-D0c0znOiQw4LN2k2IrsH8Rex0Hal3a1v5vj82C86An_Qo6R5IHMS8ooZr3yuwS3-kaGMFwhXi4DWZ-CpcwM6_JQUsLbgdBfYibBBP0lTuOTXEugsa34MzP9yyVc2&lptoken=15b773a1304806936533&pub_id=wykop.pl&ssp=300x250&campaign=Rubicon#`

**Comment by hawkeye116477** [comment]
@xMaap Słabe nagrody... Daj znać, jak będzie Xiaomi :smiley:
