### ISSUE TITLE
otube.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1034]
### Link bezpośredni 
`https://otube.pl/film/joker-2019`
### Dodatkowe informacje mogące mieć znaczenie
Czy ta strona stwarza zagrożenie? Obecnie widzę, że jest możliwe odpalenie video, a strona nie zachowuje się inwazyjnie.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
W sumie zależy czy regex reklamowy wystarczająco już wycina reklamy "+18"/

**Comment by krystian3w** [comment]
> `AdBlock blokuje niektóre playery, dodaj stronę do wyjątków aby bez problemu oglądać filmy`
