### ISSUE TITLE
stopgender.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1042]
### Link bezpośredni 
`http://stopgender.pl/Homoseksualizm-fakty.php`
### Dodatkowe informacje mogące mieć znaczenie
Pseudonauka, polecanie i promowanie leczenia terapią komperatywną niezgodną z wiedzą naukową.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
@hawkeye116477  a whitelist koniecznie musi zbudować VSC?

**Comment by hawkeye116477** [comment]
@krystian3w Może być i cmder :smile:

**Comment by krystian3w** [comment]
Mnie chodzi, że bot nie ogarnie? I czy na Windows nie głupiej skrypt bo mnie niby Github for Windows nie prezentuje ładnie gałęzi a w tle jakby podmieniał pliki po zmienieniu gałęzi.

**Comment by hawkeye116477** [comment]
A to chyba trzeba skrypt poprawić, bo niby robi, ale nie wysyła i w sumie już się domyślam gdzie jest błąd.
`czy na Windows nie głupieje skrypt`
Nie testowałem na Windzie, ale u ciebie chyba coś z tam z zegarkiem nie trybiło, co nie?

**Comment by krystian3w** [comment]
Tak robił się czas Greenwich z braku "`tzdata`" na Windows lub obejścia by oszukać skrypt w jakiej strefie czasowej jestem.
