### ISSUE TITLE
dobreklucze.pl

### ISSUE THREAD

**Issue by FadeMind** [PolishFiltersTeam/KAD#1045]
dobreklucze.pl

Brak informacji na temat właściciela. Kontakt via mail i randomowy telefon komórkowy. 
Wątpliwości co do oryginalności kluczy. 
Polityka Cookies klasyczna, Regulamin LOREM IPSUM z danymi domeny. 

IMHO do weryfikacji jako SCAM.

NIE WIEM czy historia opisana tutaj jest wiarygodna, ale strona brzydko pachnie na megabit 
http://www.wykop.pl/artykul/5242731/serwis-kluczy-dobreklucze-pl-oszusci/

**Comment by hawkeye116477** [comment]
Tak generalnie to klucze do gier raczej najlepiej kupować na zaufanych stronach opisanych na `https://www.reddit.com/r/Steam/comments/2yhnsw/key_resellers_and_what_they_mean_for_you/`.

**Comment by hawkeye116477** [comment]
@FadeMind Jakby co, to azeta już jakiś czas nie ma, także jak masz jakąś sprawę to raczej do mnie albo do Krystiana, bo azet raczej raz na jakieś stulecie się tylko zjawia :smile:

**Comment by FadeMind** [comment]
@hawkeye116477 spoko. Nie jestem na bieżąco 😬
