### ISSUE TITLE
klodawa.eu

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/KAD#1057]
Czemu strona jest blokowana a może to błąd ?.

**Comment by hawkeye116477** [comment]
@blocker999 Strona nie jest blokowana przez KAD.

**Comment by blocker999** [comment]
Może faktycznie niejest ale ja poprostu niemoge wejść na strone, odrazu mam taki komunikat : 
![best](https://user-images.githubusercontent.com/23176832/70615786-58e86800-1c0d-11ea-8912-18217f2ff873.png)

**Comment by hawkeye116477** [comment]
@blocker999 Jak wchodzisz przez Google, to czasem pojawiają się różne fejkowe losowania z nagrodami i to właśnie zostało zablokowane. Wyczyść dane i wejdź bezpośrednio na stronę.

**Comment by blocker999** [comment]
Ok, fałszywy alarm
