### ISSUE TITLE
oszczedzanie-na-ekranie.pl

### ISSUE THREAD

**Issue by xxcriticxx** [PolishFiltersTeam/KAD#1071]
Warning: This is a High Risk Site
Webroot has blocked the website you are trying to access for your protection:
http://www.oszczedzanie-na-ekranie.pl/

Detected Malicious Site
This site might contain links to viruses or other malicious software programs that can capture personal information or corrupt files on your computer.

**Comment by krystian3w** [comment]
Chyba linijka z pliku wyleciała?
