### ISSUE TITLE
sportowedzialdowo.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1073]
### Link bezpośredni 
`http://sportowedzialdowo.pl/`
### Dodatkowe informacje mogące mieć znaczenie
Strona udaje, że sprzedaje buty timberland po mocno zaniżonych cenach. Tłumaczenie z translatora. Płatność z góry, jedyna meoda płatności to karta mastercard. Powiązana z `serviceonline.linda@gmail.com`, do którego przypięta jest masa tego typu skleþów

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
#1077 / #1079
