### ISSUE TITLE
www.cebuladeal.info

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1076]
### Dodatkowe informacje mogące mieć znaczenie
Czy ta strona jest legit?

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Na razie wydaje się być po prostu zbiorem `aliexpress.com` / `banggood.com`.

W przypadku Ali nawet nie promują za bardzo danego sprzedawcy a frazę z towarami.

----

Nie pchałbym się w te cashbacki pod ali...:

> `Givingassistant` lub `Topcashback`
