### ISSUE TITLE
www.zielonakaruzela.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1079]
### Link bezpośredni 
`http://www.zielonakaruzela.pl/`
### Dodatkowe informacje mogące mieć znaczenie
Strona udaje, że sprzedaje buty timberland po mocno zaniżonych cenach. Tłumaczenie z translatora. Płatność z góry, jedyna metoda płatności to karta mastercard. Powiązana z `serviceonline.linda@gmail.com`, do którego przypięta jest masa tego typu sklepów

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
#1073

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KAD/issues/1077
