### ISSUE TITLE
www.bntnews.fr

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1085]
### Link bezpośredni 
`http://www.bntnews.fr/`
### Dodatkowe informacje mogące mieć znaczenie
Strona udaje, że sprzedaje buty dr.martens po mocno zaniżonych cenach. Tłumaczenie z translatora. Płatność z góry, jedyna metoda płatności to karta mastercard. Powiązana z `serviceonline.linda@gmail.com`, do którego przypięta jest masa tego typu sklepów

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Brak jakiegokolwiek tłumaczenia na polski, francuski chyba zna mniej niż 50% Polaków?
