### ISSUE TITLE
www.linnlilja.se

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1086]
### Link bezpośredni 
`http://www.linnlilja.se`
### Dodatkowe informacje mogące mieć znaczenie
Strona udaje, że sprzedaje torebki lauren ralph po mocno zaniżonych cenach. Tłumaczenie z translatora. Płatność z góry, jedyna metoda płatności to karta mastercard. Powiązana z `serviceonline.linda@gmail.com`, do którego przypięta jest masa tego typu sklepów

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
#1085  - szwedzki to już chyba maks 10% Polaków?

**Comment by krystian3w** [comment]
@DandelionSprout  / @lassekongo83  - fake shop report.
