### ISSUE TITLE
adidasbeyaz.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1087]
### Link bezpośredni 
`http://adidasbeyaz.com/`
### Dodatkowe informacje mogące mieć znaczenie
Strona udaje, że sprzedaje buty adidas po mocno zaniżonych cenach. Tłumaczenie z translatora. Płatność z góry, jedyna metoda płatności to karta mastercard. Powiązana z `serviceonline.linda@gmail.com`, do którego przypięta jest masa tego typu sklepów

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
#1085 - a tu Turecki...
