### ISSUE TITLE
Niedoszłe zgłoszenia z maila

### ISSUE THREAD

**Issue by hawkeye116477** [PolishFiltersTeam/KAD#1112]
To są strony z niedoszłych zgłoszeń (wyłączyłem tymczasowo zgłaszanie w obawie, że może banana dadzą, bo chyba trochę za często było, no i powinno być raczej wszystko w jednym, skoro powiązane :smile:).

```
sklep-bio.pl
dbo2.pl
psiakademia.pl
pomozbudowac.pl
pitfree.pl
restauracjasiesta.pl
kitcarforum.pl
pixelbus.pl
contestlight.pl
```

Wszystko to oczywiście powiązane z `serviceonline.karen@gmail.com`, itd.

**Comment by krystian3w** [comment]
Nie biorą tego ze spisów domen usuniętych?

**Comment by hawkeye116477** [comment]
Tak na szybko kilka domen sprawdziłem i niby aktywne.

**Comment by krystian3w** [comment]
No aktywne to są, mnie chodzi, czy nie próbują podwędzać starego pozycjonowania z tym 💩.
