### ISSUE TITLE
nazwiązanie do zamkniętego #1120

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1137]
### Link bezpośredni 
`http://timberlandpoland.pl/`
### Dodatkowe informacje mogące mieć znaczenie
`http://timberlandpoland.pl/`
`https://www.newbalancepoland.pl/`

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Duplicate of #1136
