### ISSUE TITLE
poczta-polska.net

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1142]
### Dodatkowe informacje mogące mieć znaczenie
`https://www.wykop.pl/wpis/46705413/dostalem-wlasnie-smsa-od-sms-aby-doplacic-0-94zl-b/`

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Niby wywalili ich z serwera już - ładują reklamy.
