### ISSUE TITLE
ploskonax.com

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1144]
https://ploskonax.com/?gclid=EAIaIQobChMI1ffbzOj95gIVtwPTCh0ZdgfFEAEYASAAEgIhMPD_BwE

**Comment by MajkiIT** [comment]
takie same strony 
https://medium.com/@levickaterina911/raport-specjalny-eksperci-s%C4%85-pe%C5%82ni-podziwu-dla-roberta-lewandowskia-i-jego-ostatniej-inwestycji-7f533d169f8c

**Comment by MajkiIT** [comment]
dodatkowo 
https://pl-pulsbiz.net/
https://puls-biznesu.info/
http://businesspuls.online/
http://www.smkmotala.com/
https://ppl-puls.gloryft.com/?utm_source=bfn&utm_medium=link&utm_campaign=invest&aff=bfn

**Comment by krystian3w** [comment]
>takie same strony
>https://medium.com/@levickaterina911/raport-specjalny-eksperci-s%C4%85-pe%C5%82ni-podziwu-dla-roberta-lewandowskia-i-jego-ostatniej-inwestycji-7f533d169f8c
>

https://github.com/PolishFiltersTeam/KAD/issues/971#issuecomment-538008390


KAD doesn't filter single fake news, a ban on the whole medium.com will rather be a bad decision.

---

KAD nie filtruje pojedynczych fake newsów, ban na całe medium.com raczej będzie złą decyzją.
