### ISSUE TITLE
wap.mobiltek.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1151]
### Dodatkowe informacje mogące mieć znaczenie
Dlaczego w filtrze znajduje się operator płatności MobilTek? Jest to fałszywa bramka płatności, czy coś? Próbowałem kupić transfer na chomikuj i dostałem informacje o zablokowaniu, więc wolę zapytać.

Strona operatora: https://mobiltek.pl/
Reguły blokujące:

https://github.com/PolishFiltersTeam/KAD/blob/38ebc8f90b2772677892a98ce8c24d9eedee34b6/sections/przekierowania_do_przekretow.txt#L97 https://github.com/PolishFiltersTeam/KAD/blob/38ebc8f90b2772677892a98ce8c24d9eedee34b6/sections/przekrety.txt#L575

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
@krystian3w `https://github.com/PolishFiltersTeam/KAD/issues/40`

**Comment by krystian3w** [comment]
SMS działa, niby jedynie dziwne, że u mnie była domena `pay.`; subskrypcja 💩 się nie włączyła.

Widać nie każdemu odpowiada jakieś Yeti Pay.
