### ISSUE TITLE
Dhl-paczka.eu

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1156]
### Dodatkowe informacje mogące mieć znaczenie
Próba oszustwa, scam

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by MajkiIT** [comment]
https://dhl-paczka.eu/zamowienie3354

**Comment by MajkiIT** [comment]
ONLINE
![obraz](https://user-images.githubusercontent.com/11302675/72558231-91c9cb80-38a2-11ea-88b0-2f6cf84976bb.png)
