### ISSUE TITLE
Roundcube.pl zbiera dane logowania do skrzynek. 

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1160]
### Link bezpośredni 
`http://roundcube.pl/`
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/46817389/czesc-%CA%96-uwazajcie-gdzie-logujecie-sie-do-poczty-t/164979145/#comment-164979145

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
#2530
