### ISSUE TITLE
rushpay.pl / paybylink.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1165]
### Dodatkowe informacje mogące mieć znaczenie
Próbowałem kupić konto premium na zalukaj. KAD blokuję te stronę, po wyłączeniu blokady wszystko przebiegło pomyślnie. Co prawda aktywacja od finalizacji transakcji była zdecydowanie dłużej, niż deklarowane przez zalukaj 30 minut, ale została ukończona sukcesem. Dlaczego ten operator płatności został zablokowany? 

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
`https://www.wprost.pl/prime-time/10256011/uwaga-na-te-firmy-nowe-podmioty-na-liscie-ostrzezen-publicznych-knf.html`

**Comment by krystian3w** [comment]
Ja bym zostawił teraz trzeba obserwować czy `paybylink.pl` zrobi figla KNF-owi.
