### ISSUE TITLE
strony podzywające się pod olx

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/KAD#1179]
adresy w artykule : https://blog.olx.pl/2020/01/20/uwaga-na-falszywe-linki-do-uslugi-wysylki-przez-olx/

**Comment by Thuiljos** [comment]
# Dotyczy strony: „ http://delivery-olx.pl„.

**Comment by blocker999** [comment]
**oraz delivery-olx.pl.**

**Comment by hawkeye116477** [comment]
Jak na razie, to obie domeny są wygaszone.
