### ISSUE TITLE
mobstarter.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1181]
### Link bezpośredni 
`https://mobstarter.com/47hfdj/index.php/?brand=Apple&model=iPhone&clickid=&cep=4t0dkrCes0ySaV09ESFq7HSTU4ljkEs_o3geahB0QI28vvW14lyCuGHAnHoYdvHYoYcg4sl6aQA2xoGm_eF3EtYI4_9FFKOLBb76Pwu5mfirRjkmrX7vqxIn810n_Mk-Om-dgI0w5w33a5JQVAKNDcFC0Pmlug0s9DQzoWxXRj3M-Ca9iFDa6Tle0mGxOskS6wuYHYpkfQtm0BjVaqbwnxCA-vbfSF2ZJerw-Q9ZNKAeERjYiL5iIJwE9CiLAtKvG76lhDP8n5PAJZAu9MgAw0-crp_ftdtQKgNZOKb3WTd4tgnQg63TgFMEKzX3hUQhmYq172qc_IExhH45QFBW36vE96qLykkPC3oCtyP2YJxC64hS6inqT0Kzz6wqGUFZ&lptoken=158580e9106509ff4305&PLACEMENT_ID=14892298#`
### Dodatkowe informacje mogące mieć znaczenie
Fałszywa strona otwarta z przekierowania ze strony 

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Nie męcz bota?

**Comment by hawkeye116477** [comment]
Serwer, na którym jest chyba miał jakiegoś laga.

**Comment by krystian3w** [comment]
Albo to przez przywrócenie na PASS-ie, zrobiłem bym dostawał asygnację o buttonach RSS.

**Comment by hawkeye116477** [comment]
@krystian3w Raczej serwer albo maszyna, bo chciałem wejść w edycję, by zobaczyć co tam wypluł w konsoli i coś właśnie długo mielił. Ramu niby 512 MB tylko, ale raczej wątpię, by więcej trzeba było.

Bot siedzi na glitch.com (AWS). Jakby co, to zawsze możemy przejść na `repl.it`.
