### ISSUE TITLE
pl.oriflame.com

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/KAD#1182]
Czemu blokujecie tą strone, ja bym odblokował ( błąd )

**Comment by hawkeye116477** [comment]
To chyba azet zablokował.

**Comment by krystian3w** [comment]
Bo "cirkiem" wkleił @xMapp?

**Comment by krystian3w** [comment]
`organiclife.com.pl` - też jest prośba prawna / adwokacka by odblokować.

**Comment by krystian3w** [comment]
`organiclife.com.pl` - też jest prośba prawna / adwokacka by odblokować.

**Comment by hawkeye116477** [comment]
@krystian3w Ciekawe skąd @xMaap wział o tym informacje, bo w linku UOKIK faktycznie tego nie ma. Może trzebaby resztę sprawdzić z #744 i usunąć z listy.

**Comment by krystian3w** [comment]
Na tę chwilę wszystko wycofane, 2/3 już nie funkcjonuje.
