### ISSUE TITLE
aerosneakers.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1184]
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/47018793/mirki-mam-problem-moj-rozowy-kupil-buty-ze-sklepu-/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
To już od dawna jest na liście.
Do poprawnego działania wymagany jest uBlock Origin 1.20.0+ lub AdGuard AdBlocker 3.3.2+. Ewentualnie można skorzystać z hosts.
