### ISSUE TITLE
ziololecznictwo.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1190]
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/47082005/oszukujo-czesc-murki-mialem-ostatnio-niemila-przyg/

Proszę o weryfikację, czy strona nie jest oszustwem lub zablokowanie zapobiegawcze.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
Niby KRS się zgadza i ten e-mail z dołu strony, bo ten na górze jest niepoprawny.
Tak czy siak, to podejrzane, że po za tym wpisem z wykopu nie ma żadnych innych opinii i nie mają `https`.

**Comment by krystian3w** [comment]
Może jednoosobowy sklep i hospitalizacja..., ale żeby telefonu nie mógł zabrać (zakład psychiatryczny... lub ojom(intensywna terapia))?
