### ISSUE TITLE
worldoftanks.eu

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/KAD#1195]
Niewiem może stronka jest ok ale zgłaszam bo mnie wkurza gdy chce coś pobrać z " Medoafire.com " a tu wyskakuje " gra za darmo " : https://worldoftanks.eu/join/2473_PL1?pub_id=101&xid=6e17a966-d1e7-413d-b63f-53c29b90cd64&sid=SIDGVplJa5G7Q0JS3yvar75hBtb9s4uaMPBPI4B0qbdvVwtrQR36J1mLbGynHYG-vjX0_GbF0Nj17r1sXhGNHxfwvBNjxIbvQU5CCHf5e965Mo_wkK8Ge1CQ3PYdHMYuyCvjaGfOkXO3b2rWg9cPMcmegw&enctid=c0efa1ex8i5i&lpsn=WoT+Video1+RegDark+nstandart+SOI&utm_source=networks&utm_medium=affiliate&utm_campaign=bn-adsupply-wot-pl&utm_content=101

**Comment by hawkeye116477** [comment]
To jest znana gra, wszystko jest ok. Może to raczej do @MajkiIT powinno iść jako reklama.
