### ISSUE TITLE
platnosc.twojkurier.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1200]

**Comment by krystian3w** [comment]
Już offline...?

**Comment by hawkeye116477** [comment]
Niby jeszcze domena jest w rejestrze i prawdopodobnie kompletnie zostanie usunięta w 2021 r.

**Comment by krystian3w** [comment]
A rozgryzłem rejestr domen usuniętych - to plik codziennie aktualizowany i trzeba by bazować na stronie co robi kopię:

http://www.seodomeny.pl/deleted/

**Comment by krystian3w** [comment]
No chyba, że ktoś ma GiB wolnej przestrzeni.
