### ISSUE TITLE
twojkurier.com

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1203]
twojkurier.com ==> domena już nie działa

**Comment by hawkeye116477** [comment]
Wiemy, ale ty wiesz, że mamy skrypt sprawdzający i on nam mówi jak wygaśnie któraś domena :smile:
Niby aktualnie nie działa, ale w rejestrze aktualnie jest wpisane, że wygasa dopiero w 2021 r.
