### ISSUE TITLE
ekino.pw

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1215]
https://ekino.pw/pewnego-razu-w-hollywood/
kopalnia popów, jak nie weźmienie do siebie to ja dodam.

**Comment by krystian3w** [comment]
W sumie to może uAssets da radę naprawić player jakby chcieli, chyba że masz pop-upy do nich z innych stron np. cba generuje pop-up otwierajacy `ekino.pw` z osadzonym playerem: 

`https://waaw.tv/player/embed_player.php?#iss=MTg4LjE0Ny4zOS4yOA==`

**Comment by krystian3w** [comment]
`ekino.pw##+js(aopr, decodeURI)` a odtwarzacza nie da się ujarzymić by nie był w osobnym oknie.
