### ISSUE TITLE
anitkakurier.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1227]
### Link bezpośredni 
`https://anitkakurier.com/oplata23`
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/47412981/security-cyberbezpieczenstwo-bespieczenstwo-oszuku/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Niby już ich zwinięto, ale domenę niech sprawdzi za tydzień skrypt.
