### ISSUE TITLE
movie-pass.live

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1237]
### Link bezpośredni 
`https://movie-pass.live/su/?s=movies&a=2&cid=w3iqcfq4stb3623t1tmoae11&ts=5c6e8e55-c308-4770-99ec-28fce5ce0655&q=`
### Dodatkowe informacje mogące mieć znaczenie
wyłudzenie danych karty kredytowej. 

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
brak "polonizacji".
