### ISSUE TITLE
Lista od CERT

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1297]
https://www.cert.pl/ostrzezenia_phishing/

 * format tekstowy, tylko aktywne domeny, jedna domena per linia: https://hole.cert.pl/domains/domains.txt
 *  format TSV (tab-separated values): https://hole.cert.pl/domains/domains.csv
 *  format JSON: https://hole.cert.pl/domains/domains.json
 *  format XML: https://hole.cert.pl/domains/domains.xml

W tej chwili to jest bieda wersja, ale może się przydać.

**Comment by KonoromiHimaries** [comment]
@krystian3w nie lepiej wrzucić w automat?

**Comment by krystian3w** [comment]
No właśnie ja nie mam pomysłu jak to zamontować by pobierało raz na dzień i co jak tam nagle podejrzane sklepy będą (te trafiają do osobnego pliku).

**Comment by hawkeye116477** [comment]
W przypadku niektórych lepiej blokować całe domeny, w innych znowu regex lepiej robić. Tak więc, ręcznie byłoby chyba najskuteczniej.

**Comment by hawkeye116477** [comment]
Dorobiłem skrypt `https://github.com/PolishFiltersTeam/ScriptsPlayground/blob/master/scripts/CI/CI_LETS_DO_THIS_CERT.sh`, który pokazuje to co jest na liście CERT i jest aktywne, a my tego jeszcze nie mamy.
