### ISSUE TITLE
payoner.club

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1298]
`http://payoner.club/`

**Comment by krystian3w** [comment]
see #1297 

```
||payoner.club^$all
||in-post.net^$all
||faktury3941.org^$all
||rachinfo.com^$all
||get-payment.pl^$all
||e-bokpge.pl^$all
||e-platnosc.best^$all
||windykacjajagoda.org^$all
```

**Comment by MajkiIT** [comment]
@krystian3w Ok, dzięki

**Comment by hawkeye116477** [comment]
Po co się tak znowu rozdrabniać => `https://www.certyficate.it/blokowanie-domen-z-listy-holecert-na-mikrotik/` :stuck_out_tongue:

**Comment by MajkiIT** [comment]
Na mikrotiku ma wiele mniejszych ISP swoją infrę stąd ten pomysł. A 195.187.6.34 jest adresem CERT.PL na którym wyświetlany jest alert dla usera. To samo co tutaj. https://hole.cert.pl/

**Comment by hawkeye116477** [comment]
W przypadku PH ten myk z adresem certa nie działa i tak w zasadzie, to dodanie `https://hole.cert.pl/domains/domains.txt` w zupełności wystarcza, nie trzeba kolejnych pośredników. Informacja `Copyright CertyficateIT` jak dla mnie jest trochę niestosowna.
Nie wiem też dlaczego azet tam jest wpisany jako collaborator, przecież go już od dłuższego czasu nie ma, w ogóle w tym przypadku zamiast collaborator powinno być raczej „source".

**Comment by MajkiIT** [comment]
To moja wersja. Zrobiłem aby mi było wygodniej i aby cały proces szedł u mnie. Listę przerabiam tak jak chce i stąd to Copyright . No nie przejdzie ale ktoś dostanie błąd certyfikatu a jak nawet zatwierdzi to dostanie alert, który da mu do myślenia.

**Comment by hawkeye116477** [comment]
`No nie przejdzie ale ktoś dostanie błąd certyfikatu`

Nie wiem o czym ty teraz mówisz, ale w przypadku PH jest informacja „Website Blocked" i podana lista, z której pochodzi wpis, żadnych tam błędów. Tak więc, myk z adresem działa chyba tylko w przypadku pliku hosts i być może w tym Mikrotiku, o którym pierwsze słyszę.

**Comment by MajkiIT** [comment]
@hawkeye116477 
Tą informację możesz sobie zmienić lub kierować na wybrane IP, domyślenie tak jest, ale to już jest również informacja dla uzytkownika. To samo możesz robić w hosts lub Mikrotiku.
