### ISSUE TITLE
jezykobcywdomu.eu

### ISSUE THREAD

**Issue by MajsterMechazod** [PolishFiltersTeam/KAD#1304]
### Dodatkowe informacje mogące mieć znaczenie

> - jezykobcywdomu.eu
> - dofinasowanieregionalne.pl
> - kursjezykowy.eu

https://niebezpiecznik.pl/post/uwazaj-na-kursy-jezykowe-z-dotacjami-nie-wiadomo-kto-przetwarza-dane-osobowe-ale-mozna-sie-tego-domyslic/

**Comment by hawkeye116477** [comment]
Ale to jest wpis z 2018r i to już jest na liście...
