### ISSUE TITLE
primevideo.com

### ISSUE THREAD

**Issue by xxcriticxx** [PolishFiltersTeam/KAD#1311]
https://bit.ly/ekino-amazon

**Comment by krystian3w** [comment]
`primevideo.com`?

**Comment by krystian3w** [comment]
A i skróconych linków nie blokujemy filtrami, trzeba by do bit.ly zgłosić scam (nie wiem czy banują u siebie linki).

**Comment by hawkeye116477** [comment]
Prime Video to domena Amazonu, także nie blokujemy.
