### ISSUE TITLE
liveglobalalert.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1313]
Tytuły na stronie głównej 

> Będziemy znakowani jak bydło: ID2020 obowiązkowe szczepienie z mikroczipem

> To nie jest III Wojna Światowa, to jest I Wojna Globalna

> Technologia 5G uśmierci milionów ludzi rocznie

> Martwe nietoperze spadające z nieba w całym Izraelu to znaki czasów ostatecznych?

**Comment by hawkeye116477** [comment]
Jeszcze zapomnieli napisać, że za koronawirusa odpowiedzialne jest 5G :smiley:
