### ISSUE TITLE
goldenmark.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1314]
### Link bezpośredni 
`https://goldenmark.com/pl/`
### Dodatkowe informacje mogące mieć znaczenie
https://www.imsig.pl/pozycja/2019/211/56155,GOLDENMARK_SPÓŁKA_AKCYJNA
https://slomski.us/2020/04/03/goldenmark-nabici-w-butelke/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
@krystian3w #871
