### ISSUE TITLE
comkola.myshopify.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1322]
### Link bezpośredni 
`https://comkola.myshopify.com/apps/okiho/?gclid=EAIaIQobChMIjd2Nz8vj6AIVgcYZCh1b1go2EAEYASAAEgJ74PD_BwE`
### Dodatkowe informacje mogące mieć znaczenie
Spam, oszustwo

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Brak polonizacji, brak wtyczki tłumacza Google - zostaje zgłosić do Google / Eset i Spam404.
