### ISSUE TITLE
Nadużycie - niesłuszne umieszczenie portalu na liście filtra KAD

### ISSUE THREAD

**Issue by wolnemedia** [PolishFiltersTeam/KAD#1326]
NADUŻYCIE - niesłuszne umieszczenie portalu na liście filtra KAD, skutkujące straszeniem ludzi przed oszustwami i złośliwym oprogramowaniem, którego na moim portalu nie ma (zniesławienie mojego portalu) i blokowaniem poczty mailowej przez dalsze dopisanie jej do list filtrów antyspamerskich.

Według głównego założenia filtra zawiera „Strony w środku pliku mogą być złośliwe. Nie jest zalecane odwiedzanie tych witryn z wyłączonym oprogramowaniem blokującym i antywirusowym." Tymczasem z tego co widzę, służy do blokowania stron sklepów internetowych i stron legalnie krytykujących korporacje farmaceutyczne w ramach legalnej debaty publicznej i konstytucyjnego prawa do wolności słowa.

1. Portal WolneMedia.net nie pobiera opłat ani niczego nie sprzedaje.

2. Mój portal nie używa hasła „za darmo", bo wszystko na stronie jest bezpłatne i dostępne bez ograniczeń.

3. Portal nie rozpowszechnia złośliwego oprogramowania, wirusów, nie wyłudza danych osobowych, nie rozsyła ofert ani spamów, etc.

4. Strona nie prowadzi działalności cyberprzestępczej.

5. Strona nie przekierowuje do innych stron z przekrętami - dodawanie linków do stron handlujących czymkolwiek jest nawet zabronione w regulaminie portalu.

6. Strona nie zamieszcza reklam, linków ani przycisków do stron wyłudzających pieniądze. Jest tylko jeden zewnętrzny banner do Schroniak.pl (bezpłatnie udostępniony) do strony człowieka, który chce pomóc zwierzętom ze schronisk znaleźć nowe domy.

7. Strona jest przejrzysta i nieprzeładowana, chociaż jest na niej ok. 30 nowości dziennie z różnych kategorii (to duży, wielotematyczny portal a nie blog).

8. Strona udostępnia treści, które uważa za wiarygodne, nawet jeśli są kontrowersyjne. Jeśli są jakieś wpadki z fake newsami, wynika to z nabrania się na nie administratora (czyli mnie). Każdemu może się to przytrafić. Jeśli odkrywam, że nabrałem się na fake newsa - natychmiast go usuwam.

9. Regulamin jest łatwo dostępny, jednoznaczny i przejrzysty. Dla ułatwienia jest nawet łopatologicznie streszczony.

10. Na mój portal wchodzą głównie ludzie z pozytywną opinią o portalu. Możliwe, że poza portalem są gdzieś ludzie, którym nie podobają się poglądy rozpowszechniane na moi portalu (każda strona ma swoich przeciwników, nawet WOŚP Jurka Owsiaka, gdyby uznać ich głosy, musielibyście na listę wpisać wszystkie strony w internecie).

11. Zakazane jest na portalu publikowanie płatnych opinii, treści sponsorowanych, PR, marketingowych. Ciągle dostaję oferty publikacji takich treści za dużą kasę, ale ODMAWIAM, bo działam uczciwie wobec moich czytelników.

12. Strona nie zatrudnia wróżek, doradców rozwoju osobistego ani naciągaczy oferujących odpłatne usługi finansowe czy inne. Strona jest NIEKOMERCYJNA - każdy może się zarejestrować i publikować artykuły pod warunkiem, że są darmowe, nie zawierają linków do sklepów ani ofert handlowych. Strona pozwala dzielić się autorom poglądami na różne tematy (od kultury, sportu i edukacji po gospodarkę, naukę i zdrowie). Strona przedstawia RÓŻNE poglądy, nawet takie, z którymi administrator (czyli ja) się nie zgadza, ale treści sponsorowanych i handlowych nie ma.

13. Strona nie oferuje żadnych produktów handlowych.

Mój portal z jednej strony uczy ludzi samodzielnego myślenia, z drugiej strony pozwala dzielić się czytelnikom własnymi poglądami - także przeciwstawnymi, z trzeciej walczy z marketingiem i reklamą, aby nie narażać ludzi na utratę pieniędzy ze strony oszustów. Celem strony jest wymiana poglądów i uczciwa dyskusja różnych środowisk - wzajemne przekonywanie się argumentami do swoich racji.

Myślę, że osoba, która dopisała mój portal do listy, dokonała NADUŻYCIA UPRAWNIEŃ i nadinterpretacji wytycznych dla filtra (pisze wyraźnie, że walczy personalnie z Justyną Sochą i Jerzym Ziębą, i wpisuje na listę wszystkie strony, na których się kiedykolwiek się pojawili). Czyli prowadzi wojnę personalną, a nie walczy o cyberbezpieczeństwo użytkowników przeglądarek.

O Waszej liście dowiedziałem się od czytelnika AdGuarda, któremu nie podoba się, że mu zablokowano dostęp do WolneMedia.net. On Wam zaufał, że będziecie chronić go przed oszustami, a zamiast tego cenzurujecie mu strony krytykujące m.in. korporacje farmaceutyczne. To cenzura prewencyjna, sprzeczna z Konstytucją RP i publiczne zniesławienie mojego portalu (sugerowaniem, że to „strona oszustów-wyłudzaczy”). Na dodatek nie ostrzegacie ludzi, którzy instalują Wasz filtr ufając Wam, że solidnie wykonujecie swoją robotę, że obok stron oszustów-wyłudzaczy na liście umieszczacie strony, na których istnieją światopoglądy, z którymi się nie zgadzacie. To nie ochrona przed oszustwami, ale zwykła cenzura. Oszukujecie ludzi nadużywając uprawnień do edycji filtra.

Problem został poruszony na moim portalu (tam można przeczytać list od czytelnika):
https://wolnemedia.net/kolejny-odslona-walki-z-portalem-wolne-media-i-innymi/

W przypadku odmowy usunięcia mojego portalu z Waszej listy, proszę o udostępnienie danych prawnych Waszej organizacji w Polsce (lub osoby odpowiedzialnej prawnie za Wasz projekt). Czy odpowiedzialność ponosi MICROSOFT? Rozważę opcję pozwu sądowego o publiczne zniesławienie (sugerujecie użyrkownikom filtra, że mój portal to PRZEKRĘT podważajac zaufanie czytelników do mnie, które buduję uczciwie od 13 lat), oraz o stosowanie cenzury prewencyjnej zakazanej w Konstytucji RP (konstytucja obowiązuje wszystkich obywateli Polski - także Was). Możliwe, że zostanie skierowana skarga do Rzecznika Praw Obywatelskich.

Chronić ludzi przed wirusami komputerowymi i podejrzanymi sklepami z nielegalnym towarem to jedno, a blokować dostęp do portalu z różnymi treściami, który niczym nie handluje, to zupełnie coś innego.

ALE TO NIE WSZYSTKO! Z POWODU WPISANIA MOJEJ DOMENY NA WASZĄ LISTĘ STRON PISHINGOWYCH I INNYCH ZE ZŁOŚLIWYM OPROGRAMOWANIEM I WIRUSAMI KOMPUTEROWYMI, DOPISANO MOJĄ DOMENĘ DO LIST ANTYSPAMOWYCH GMAILA I WIELU INNYCH ANTYSPAMÓW I MOJA POCZTA WYSYŁANA Z DOMENY JEST BLOKOWANA!

Ludzie się rejestrują, wysyłane jest im hasło i login, a wiadomości nie docierają! Problemy z mailami (dostaję zwroty, że wiadomości mailowe nie są dostarczane bo są wysłane ze skrzynki mailowej w domenie wolnemedia.net) pojawiły się w chwili, gdy dopisaliście domenę do Waszej listy. Wasza lista powinna zawierać TYLKO które „Strony w środku pliku mogą być złośliwe. Nie jest zalecane odwiedzanie tych witryn z wyłączonym oprogramowaniem blokującym i antywirusowym". A co zawiera faktycznie? Strony, na których takich rzeczy nie ma.

Co ciekawe, wiele osób w dyskusji podnosiło wątek, że domeny stron o odmiennych światopoglądach od twórcy filtra nie powinnny na niej figurować. A jak zareagował twórca filtra? Nic nie zrobił i kontynuował swoją działalność. Inne firmy walczące ze spamami i złośliwym oprogarmowaniem WAM UFAJĄ i dopisują domeny z filtra do pocztowych antyspamów.

To co zrobiliście, nadaje się do zgłoszenia w Prokuraturze - utrudnianie legalnej działalności, blokowanie poczty mailowej przez antyspamy, publiczne zniesławienie i straszenie internautów, że wchodząc na mój portal ryzykują zainstalowanie wirusa lub złośliwego oprogramowania.

ŻĄDAM NATYCHMIASTOWO USUNIĘCIA MOJEJ DOMENY Z WASZEJ LISTY I ODKRĘCENIE PROBLEMÓW Z BLOKOWANIEM MOICH E-MAILI PRZEZ LISTY ANTYSPAMOWE. TO CO ZROBILIŚCIE JEST CYBERPRZESTĘPSTWEM I PODLEGA ZGŁOSZENIU DO PROKURATURY.

Podsumowanie:

- doprowadziliście do blokowania wiadomości mailowych wysyłanych ze skrzynek w domenie wolnemedia.net

- publicznie zniesławiacie mój portal strasząc ludzi, że to portal cyberprzestępców ze złośliwym oprogramowaniem (np. do kradzieży danych osobowych, handlująca nielegalnym towarem, rozsiewającym wirusy, oszukańcze oferty handlowe, etc.)

Samo zamknięcie dyskusji (czyli dopisywanie nowych stron do filtra KAD) nie rozwiązuje problemu, póki moja domena na nim figuruje. W przypadku odmowy - sprawa zostanie zgłoszona do Prokuratury lub zostanie przeciwko Wam skierowany pozew sądowy.

M. Hawranek

Administrator WolneMedia.net

**Comment by wolnemedia** [comment]
I do tego dochodzi jeszcze uwzględnianie filtra „KAD - przekręty" przez wyszukiwarkę Google - walcząc ze spamem obniża stronę w wynikach wyświetlania. Teraz wiem, dlaczego od daty wpisania mojej strony na Wasz filtr, obniżyła mi się gwałtownie liczba wejść z Google. Nie wiem, czy jesteście świadomi ODPOWIEDZIALNOŚCI jaka na Was ciąży i KONSEKWENCJI.

**Comment by hawkeye116477** [comment]
Wasza strona nie jest już od wczoraj na liście „KAD - Przekręty".

**Comment by wolnemedia** [comment]
Poproszę o linka do aktualnej listy. Bo znalazłem tylko to:

https://github.com/PolishFiltersTeam/KAD/blob/master/sections/pseudonauka_fake_news.txt

https://github.com/PolishFiltersTeam/KAD/blob/master/KADfake.txt

i w obu plikach txt portal figuruje.

**Comment by hawkeye116477** [comment]
https://raw.githubusercontent.com/PolishFiltersTeam/KAD/master/KAD.txt

**Comment by wolnemedia** [comment]
Dziękuję za linka i szybką, pozytywną interwencję.

Mam nadzieję, że antyspamy pocztowe Gmaila i innych usługodawców poczty elektronicznej zaktualizują filtry antyspamerskie i przestaną blokować mi pocztę.

**Comment by krystian3w** [comment]
Raczej wątpię, że szybko zdejmą, może coś wywalczysz; Google / Facebook raczej nie patrzy na regionalną listę dla 3-4 milionów użytkowników `uBO` / `NAb` / `AdGuard` (pewnie 5-6 milionów dalej używa ABP / AdBlock z przyzwyczajenia - tam uznaliśmy że lista nie ma racji bytu).

**Comment by kompowiec** [comment]
IMO niezrozumiałe jest dołączanie stron tego rodzaju do użytecznej listy zawierającej przykłady najbardziej oczywistego naciągactwa albo phishingu czy spamu.

Jeżeli chcesz dać ludziom opcję zabezpieczenia przed stronami poświęconymi zagadnieniom o wątpliwej wiarygodności, możesz stworzyć odrębną listę specjalnie do tego celu. Listę o profilu antyfoliarskim, antyszurskim. Wtedy byłoby to rzeczywiście przejrzyste, jak chciał sprawca całego zamieszania.

Rzecz wygląda zupełnie inaczej, kiedy zatruwasz studnię, z jakiej pije już całkiem sporo osób, dołaczjąc coś takiego jako ficzer do czegoś, co już zdążyło zdobyć popularność.

**Comment by MajsterMechazod** [comment]
Rozumiem, że może strona niesłuszne dodana do listy stron kontrowersyjnych według Ciebie, ale muszę wtrącić kilka swoich uwag. A mianowicie o cenzurze i jak mniemam do odwołania się do konstytucji RP o cenzurze prewencyjnej...

1. Listy KAD nigdzie nie są domyślne, są jako opcjonalne. Od woli użytkownika zależy ich włączenie i zaakceptowanie ich wewnętrznych reguł.
2. Nawet jeśli strona znajduje się na KAD nie oznacza to jej blokady. Przed otworzeniem owej strony dodatek wyświetli monit, który użytkownik może zignorować, a nawet dodać stronę do „białej listy”.

Ale podsumowując dobrze, że lista stron kontrowersyjnych została odłączona od głównego filtra, bo trochę odstawała od założeń pierwotnych i wytyczonych celów filtra.

**Comment by kompowiec** [comment]
To nie jest cenzura prewencyjna ponieważ rząd nie wymusił obowiązku używania tych filtrów, ochłoń trochę.

**Comment by krystian3w** [comment]
https://www.instalki.pl/aktualnosci/internet/53790-cenzura-prorosyjskich-stron-internetowych-w-polsce.html
