### ISSUE TITLE
flexgum.pl + roomdeco.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1327]
https://www.wykop.pl/wpis/48742213/uwazajcie-na-internetowego-oszusta-https-flexgum-p/

Tutaj nawet nie jestem w 1% pewny, bo nawet nie sprawdzałem regulaminu i tylko zgłaszam. Jak ktoś znajdzie czas to może poszperać.

**Comment by hawkeye116477** [comment]
Oba sklepy są nowe, `flexgum` najnowszy, 4 dni temu powstał. Oba sklepy nie mają żadnych numerów KRS ani NIP. W jednym i drugim brakuje jakiejkolwiek informacji o adresie siedziby firmy. W `roomdeco` podają jedynie adres pośrednika i piszą, żeby nie wysyłać tam, bo zwrotów nie przyjmą oraz trzeba napisać maila, by poznać adres do zwrotu.
