### ISSUE TITLE
KAD - AdGuard iOS

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1328]
### Dodatkowe informacje mogące mieć znaczenie
Czy osoby tworzące filtry KAD mają kontakt z twórcami AdGuarda na urządzenia mobilne? 

Zwłaszcza jeśli mowa o iOS - lista ma tag `#security`, ale jest dodawana do zestawu „AdGuard - General”, a „AdGuard - Security” jest teoretycznie niewykorzystany (tylko użytkownicy premium mogą dodać np. Spam 404).

 Ogółem zmierzam do tego, że każda kategoria (`general`, `security`, `privacy`, `social` i `custom`) ma maksymalnie 50.000 możliwych reguł, z jakich może korzystać... takie niestety są wymagania Apple do używania blokowania treści w Safari mobilnym.

Jednym słowem, przesunąć filtry KAD z „`General`” do „`Security`”, by zwolnić ilość reguł w „`General`” dla innych filtrów. 

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
@AdamWr @F4z Możesz coś tej sprawie zdziałać?

**Comment by krystian3w** [comment]
Może wystarczy jak ręcznie do szablonu dodamy:

```js
!#safari_cb_affinity(security)




!#safari_cb_affinity
```

Chyba, że to kompilator wywali / ominie.

**Comment by krystian3w** [comment]
I jeszcze ciekawe czy filtry w ogóle działają jakoś z iOS np. efekt białych stron z czarnym tekstem - `$all` jak nie trafiło na iOS pewnie sprawia że filtr nic nie robi (18 na 23 tysiące)?

**Comment by AdamWr** [comment]
Na iOS działa to w ten sposób, że pojawia się komunikat:
```
Safari nie może otworzyć tej strony.
Błąd: "URL został zablokowany przez blokadę zawartości".
```

Potem zapytam się o przeniesienie tej listy do kategorii `Security`.
Dzięki za zawołanie.

**Comment by MajsterMechazod** [comment]
> Na iOS działa to w ten sposób, że pojawia się komunikat:
> 
> ```
> Safari nie może otworzyć tej strony.
> Błąd: "URL został zablokowany przez blokadę zawartości".
> ```
> 
> Potem zapytam się o przeniesienie tej listy do kategorii `Security`.
> Dzięki za zawołanie.

Tylko przypadkiem nie sprawcie, by lista była możliwa do subskrypcji tylko po wykupieniu premium, a po prostu sama się tam dodała po zaznaczeniu filtrów regionalnych jak jest teraz (za free).  ( ͡º ͜ʖ͡º)

**Comment by krystian3w** [comment]
W sumie ciekawe czy te `safari_cb_affinity` można używać - niby twórca filtrów mających macOS w domu i może iPhona prosił/prosiła o rozważenie by dodać je do "jak tworzyć filtry do AdGuard.

A z komentarzy do AdGuard base wynika że raczej jednak zrezygnowali z tego?

**Comment by AdamWr** [comment]
>Tylko przypadkiem nie sprawcie, by lista była możliwa do subskrypcji tylko po wykupieniu premium, a po prostu sama się tam dodała po zaznaczeniu filtrów regionalnych jak jest teraz (za free).

Ja nie mam zbyt dużego wpływu na to co zostanie zrobione, ale na razie, z tego co widzę, to zostanie tak jak jest obecnie ¯\\_(ツ)_/¯

<hr>

>W sumie ciekawe czy te safari_cb_affinity można używać - niby twórca filtrów mających macOS w domu i może iPhona prosił/prosiła o rozważenie by dodać je do "jak tworzyć filtry do AdGuard".
>
>A z komentarzy do AdGuard base wynika że raczej jednak zrezygnowali z tego?

Z tego co wiem, to był problem z działaniem `safari_cb_affinity`, więc zostało to tymczasowo wyłączone.

**Comment by krystian3w** [comment]
Niby uruchomiono ponownie `safari_cb_affinity`, niestety nie mam jak sprawdzić czy `safari_cb_affinity` przeniosło 5100 filtrów między kontenerami lub na liście z regionalnych do `security`.

**Comment by hawkeye116477** [comment]
Ale znamy jednego fana :apple: , który może mógłby to sprawdzić - @xxcriticxx.

**Comment by krystian3w** [comment]
Pytanie czy ma on oczekiwać około 6.4K komunikatów:

```
Safari nie może otworzyć tej strony.
Błąd: "URL został zablokowany przez blokadę zawartości".
```

**Comment by ClusterByte-x** [comment]
Zainstalowany na czysto AdGuard z domyślnymi listami i po dodaniu KAD:

![034A1C87-0760-42F3-83FB-DDBEC3BF799E](https://user-images.githubusercontent.com/76107417/112705366-b1915200-8e9e-11eb-9326-ec00d8703cc4.png)

![91C1B5C5-BF2C-4CA7-8863-FC78B9B8B220](https://user-images.githubusercontent.com/76107417/112705377-b8b86000-8e9e-11eb-91f1-adb833cc21c6.png)

**Comment by krystian3w** [comment]
Czyli zaczęło działać `!#safari_cb_affinity(security)` i czy masz wykupione premium (lub bardzo opcjonalnie zamknięto zgłoszenie jakie założył `adamwr` z dobrym wsparciem dla darmowych użytkowników).

Bardzo opcjonalnie premium nie jest warunkiem dla list "ochrona" od jakiegoś czasu.

**Comment by ClusterByte-x** [comment]
Nie. Jest to darmowa wersja, bez premium. 😉
