### ISSUE TITLE
millensbannk.xyz

### ISSUE THREAD

**Issue by MajsterMechazod** [PolishFiltersTeam/KAD#1332]
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/48795891/uwaga-na-oszustwo-na-millennium-bank-wyswietla-sie/

**Comment by hawkeye116477** [comment]
Ktoś usunął wpis na wykopie?

**Comment by krystian3w** [comment]
Tak, ale ceny jakby robili upadłość "-80%"?
