### ISSUE TITLE
Merlin Commerce Sp. z o.o.

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1341]
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/49033825/przypominam-zenieprzeczytane-plnie-wywiazuje-sie-z/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by xMaap** [comment]
> PROFIT M Spółka z ograniczoną odpowiedzialnością z siedzibą w Warszawie (02-305), Aleje Jerozolimskie 134, wpisana do rejestru przedsiębiorców, prowadzonego przez Sąd Rejonowy dla m.st. Warszawy w Warszawie, XII Wydział Gospodarczy, KRS 0000756053, NIP 525-22-45-459, REGON 015227002. 
https://www.nieprzeczytane.pl/regulamin

> Utworzona | 2013.11.08 17:40:08
> Ostatnia modyfikacja | 2019.10.31 19:16:18
> Koniec okresu rozliczeniowego | 2020.11.08 17:40:08
> Nazwy serwerów | dns108.ovh.net    ns108.ovh.netAbonent | PROFIT M SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ SP. J.  Al. Jerozolimskie 134 02-305 Warszawa, PL
https://www.dns.pl/whois

Może teraz mają jakieś problemy.

**Comment by hawkeye116477** [comment]
Na ceneo też coraz wiecej negatywnych opinii.

A jest też odpowiedź sklepu:
`Dzień dobry, bardzo przepraszam za opóźnienie w realizacji zamówienia i niedogodności z tym związane. Obecnie oczekujemy opóźnionych dostaw z magazynów zewnętrznych i robimy co w naszej mocy, by jak najszybciej wysłać opóźnione paczki. Wiemy, że nasi dostawcy również robią wszystko, żeby wywiązać się terminowo z dostaw, jednak w magazynach pracuje obecnie mniej ludzi, co ma znaczący wpływ na opóźnienia. Staramy się, aby ten czas był jak najkrótszy, a zamówienie zostało zrealizowane jak najszybciej. Oczywiście przysługuje także prawo do anulowania całego zamówienia. W tym przypadku proszę o wiadomość na mailal. Z uwagi na zdecydowanie zwiększoną ilość zapytań nasz dział obsługi klienta pracuje z małym opóźnieniem, ale sukcesywnie odpowiada na wszystkie wiadomości.`

**Comment by xMaap** [comment]
Sklep ma już swoje lata i sytuacje mogą ogarnąć jutro lub za kilka miesięcy. Ja bym zostawił tak jak jest, bo później trzeba by było co chwile sprawdzać czy już się ogarnęli.

**Comment by krystian3w** [comment]
Powinni robić zwrot kasy, niby hipermarkety umieją jak braknie "chleba".

**Comment by MajsterMechazod** [comment]
https://niebezpiecznik.pl/post/uwaga-na-zakupy-w-merlin-pl/?more

Podobnie Merlin - ponoć to ta sama grupa kapitałowa (jak zaznaczył ktoś w komentarzach). 

> Inne sklepy prowadzone przez grupę Merlin – mówi tu konkretnie o nieprzeczytane.pl mają ten sam problem. 

> Uważajcie również na sklepy nieprzeczytane, profit24, mestro oraz smarkacz, które zostały wykupione przez grupę merlin ponad rok temu i od tamtej pory jest problem taki sam jak w merlinie.

> Nie tylko w merlinie. We wszystkich sklepach należących do tej grupy są podobne komentarze. nieprzeczytane, profit24, smarkacz, mestro. Coś mi się wydaje, że w tym roku merlin upadnie.

**Comment by xMaap** [comment]
Teraz ja bym dodał do filtrów.

**Comment by hawkeye116477** [comment]
A ja czytałem, że już kiedyś raz upadli, potem ich ktoś przejął i uratowani...

**Comment by hawkeye116477** [comment]
`We wszystkich sklepach należących do tej grupy`

@krystian3w A co z cdp? 
https://www.ceneo.pl/sklepy/cdp.pl-s24610#tab=reviews
https://www.opineo.pl/opinie/cdp-pl

Na ceneo o dziwo z 30 dni mało negatywów. Na opineo więcej, ale tam są opinie z przed roku.

**Comment by xMaap** [comment]
CDP ogłosiło upadłość https://www.spidersweb.pl/2020/04/cyberpunk-2077-cdp-upadlosc.html
https://www.money.pl/gospodarka/sprzedawali-gry-video-od-zawsze-to-koniec-cdp-z-wnioskiem-o-upadlosc-6502303949297793a.html

**Comment by hawkeye116477** [comment]
@xMaap To nie oni, to inna firma...

**Comment by xMaap** [comment]
@hawkeye116477 Ja o tym wiem. Tylko napisałem, że już dawno ogłosili upadłość.
