### ISSUE TITLE
dstreet.pl

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1344]
https://www.google.com/search?client=firefox-b-d&q=dstreet.pl+ zerknijcie w opinie

**Comment by MajsterMechazod** [comment]
Kiedyś korzystałem z tego sklepu i zamówienie przebiegło zgodnie z oczekiwaniami, bez problemów. Nawet ze zwrotem. Coś się popsuło?

**Comment by krystian3w** [comment]
Może to amerykańska rozmiarówka?

:gb: M - 🇺🇸  XXL niby po przeliczaniu.

**Comment by MajkiIT** [comment]
Z tego co widzę to problemy zaczęły się wcześniej niestety.
https://www.opineo.pl/opinie/dstreet-pl

**Comment by krystian3w** [comment]
Jakieś postępy z poprawą jakości marki? Rozmiarówka poprawiona w ofertach?

**Comment by hawkeye116477** [comment]
Na opineo nadal nie widać pozytywów, na ceneo ostatnia 1 dobra opinia 4 miesiące temu. Jest też raport byłego pracownika na wykopie => https://www.wykop.pl/link/5475407/#comment-76527857.

**Comment by krystian3w** [comment]
W AdGuard niby `Podstawowe Filtry AdGuard` rozwalają stronę.

Podejrzewam, że ktoś specjalnie usunął listy aktywne i zamknął ostrzeżenie z informacją co blokuje.

**Comment by hawkeye116477** [comment]
@MajkiIT Twoja reguła na dstreet rozwala stronę w przypadku AG, może lepiej dopisać tam `$all` na końcu, niby to nie zadziała dla ABP, ale jak rozwala stronę to tak nie elegancko, ktoś pomyśli, że to błąd na liście i wyłączy albo zgłosi, więc chyba lepiej jakby blokowało dla wybranych niż by robiło taki efekt...

**Comment by krystian3w** [comment]
KAD też mogą wyłączyć po zignorowaniu komunikatu - też się strony w większości rozwalą z braku `CSS+JS+GRAFIK`.

Przepisanie wszystkiego na `document` by wymagało kombinacji alpejskich w skrypcie CI a w przypadku stron używanych jako hosting badziewia `third-party` nagle może ono znów robić złośliwe przekierowania:

https://github.com/PolishFiltersTeam/KAD/issues/927 [`tvntl.pl`]

**Comment by hawkeye116477** [comment]
No niby tak, choć przynajmniej zobaczą od razu ten komunikat.

A tak a propos, póki co na opineo pojawiły się 2 pozytywne opinie parę dni temu.

**Comment by MajkiIT** [comment]
@hawkeye116477 zaraz usunę tą regułę a kto chce się chronić to na bank ma Wasze reguły.

**Comment by krystian3w** [comment]
Niby umieją nic zapakować do pudełka i o tym mailowo poinformować.

Zakładając, że mniej będą pakować "pustek" do pudełek i spamować na mail o tym, to może się w końcu ogarnęli.

**Comment by MajkiIT** [comment]
@krystian3w przejrzałem opinie w wizytówce Google i na moje oko kupują opinie. Zamieszczają to osoby, które tylko to oceniły dotychczas.

**Comment by krystian3w** [comment]
Ja wciąż widzę, że mają problem z rozmiarami / farbowaniem / komplementacją zamówień / helpdeskiem.
