### ISSUE TITLE
playerek.pl 

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1345]
Playerek.pl

**Comment by krystian3w** [comment]
Niby wideo leci a nie po 30 minutach "wymagana rejestracja" / "tylko dla premium".

Jedyny pop-up jaki starszy to taki o wykryciu uBlock Origin.

Niby mają kiepskie hostingi wideo w 480p (słabo się buforuje u mnie).

**Comment by hawkeye116477** [comment]
https://www.hybrid-analysis.com/sample/13c0d841fdc0dc865fd3fe2ddffed3e5c17612164e4e8506a24f9c36055efc6d

**Comment by krystian3w** [comment]
To jeszcze trzeba by zrobić konto i zobaczyć czy w opcjach nie oferują premium że niby 4k jak zapłacisz to ci znajdziemy.
