### ISSUE TITLE
Sekcja zhakowanych stron

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/KAD#1346]
```
https://github.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/blob/master/hacked-domains.list
```

**Comment by krystian3w** [comment]
10 tysięcy hostów, trochę dużo, za raz AdGuard powie że usuwa nas z iOS #1328?

**Comment by KonoromiHimaries** [comment]
@krystian3w jest tego więcej https://github.com/uBlockOrigin/uBlock-issues/issues/984

**Comment by krystian3w** [comment]
W sumie oni chyba nie sprawdzają czy hosting istnieje / został oczyszczony.

**Comment by krystian3w** [comment]
#2094
