### ISSUE TITLE
vitamedia.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1348]
Utworzona | 2020.04.26 14:04:02
Ostatnia modyfikacja | 2020.04.26 14:04:03
Koniec okresu rozliczeniowego | 2021.04.26 14:04:02
Abonent | dane niedostępne

https://www.dns.pl/whois

**Comment by hawkeye116477** [comment]
Po sprawdzeniu NIPu wynika, że niby firma założona w 2018. Co ciekawe na opineo są opinie nawet z 2016r...

**Comment by xMaap** [comment]
https://vitamedia.pl/regulamin-sklepu
oroty Pałat prowadzącej działalność gospodarczą pod firmą VitaMedia Dorota Pałat z siedzibą w Olsztynie,  ul. Piłsudskiego 72C/11, NIP: 5931472123, REGON: 385963881, wpisaną do Centralnej Ewidencji i Informacji o Działalności Gospodarczej.

Dla mnie śmierdzi ten sklep.

**Comment by krystian3w** [comment]
Pytanie skąd też mają urządzenia, może znowu jakieś z sąsiednich państw.

I czy to jakieś mocne leżaki magazynowe w promocji i czemu nowości nie mają oznaczenia promocji i po niskiej cenie...

**Comment by hawkeye116477** [comment]
https://www.legalniewsieci.pl/zagrozenia-w-sieci/zalecamy-ostroznosc-podczas-zakupow-w-sklepie-vitamediapl

Czyli numer telefonu i mail nie działa. Co do tych cen to co np podali w przykładzie, to ja widzę na ceneo, że inne sklepy mają nawet niższe ceny i to wcale nie są jakieś zupełnie nowe sklepy => https://www.ceneo.pl/90216659. Tak czy siak negatywnych opinii póki co widać przybywa => https://m.opineo.pl/opinie/vitamedia-pl.

**Comment by hawkeye116477** [comment]
No i najwyraźniej już kasę wzięli i się zawinęli...
