### ISSUE TITLE
vitamedia.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1349]
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/49167063/czasy-sa-tak-okropne-ze-jak-czlowiek-chce-cos-kupi/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
Proszę o nie duplikowanie zgłoszeń (#1348).
