### ISSUE TITLE
*.is-best.net

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1352]
### Dodatkowe informacje mogące mieć znaczenie
https://www.cert.orange.pl/aktualnosci/nie-ufajcie-fakenewsom-o-wielkich-pieniadzach

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
To już wczoraj zostało dodane, proszę zaktualizować KAD.
