### ISSUE TITLE
ctbike.pl

### ISSUE THREAD

**Issue by MajsterMechazod** [PolishFiltersTeam/KAD#1353]
### Dodatkowe informacje mogące mieć znaczenie
https://opineo.pl/opinie/ctbike-pl

**Comment by hawkeye116477** [comment]
Wg whois, strona założona w 2010r, ale najwyraźniej problemy z tym sklepem są od samego początku jego założenia.
Na ceneo również pełno negatywów, bardzo mało pozytywnych opinii.
https://www.ceneo.pl/sklepy/ctbike.pl-s13549
