### ISSUE TITLE
komfort.pl + homla.com.pl + sklepmartes.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1354]
https://www.wykop.pl/link/5493255/sklep-internetowy-komfort-nie-wysyla-zamowionych-towarow-od-kwietnia/
https://www.wykop.pl/link/5493255/#comment-76957957

**Comment by xMaap** [comment]
To może się przydać https://docs.google.com/spreadsheets/d/1V3Nsxhpnd6_i3wIxqIcE7DgmQWs22sAe1DujNGuMpKM/edit#gid=0

**Comment by hawkeye116477** [comment]
Może jeszcze się ogarną...

**Comment by hawkeye116477** [comment]
Jeszcze Martes, ale tylko, żeby się nie okazało, że niedługo się ogarną...

`https://www.ceneo.pl/sklepy/sklepmartes.pl-s2829#tab=reviews`

`https://www.opineo.pl/opinie/sklepmartes-pl#opinie`
