### ISSUE TITLE
proshop.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1361]
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/49472727/ostrzegam-przed-ta-strona-poprzednio-byl-e-elektro/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
To raczej nie jest fakowy sklep. Tak jak ktoś podał `to jest polska wersja proshop.dk`.
