### ISSUE TITLE
bonynaszkolenie.eu

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1365]
### Dodatkowe informacje mogące mieć znaczenie
Facebookowy scam

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by xMaap** [comment]
Ci dalej się świetnie bawią i zakładają nowe strony.

**Comment by hawkeye116477** [comment]
Jest tego więcej => https://sprawdzam.afp.com/nie-nie-sa-unijne-dofinansowania-do-kursow-jezykowych.
