### ISSUE TITLE
seriale.co

### ISSUE THREAD

**Issue by xxcriticxx** [PolishFiltersTeam/KAD#1366]
strona do weryfikacji 

szkielet oryginalnej strony z podpietym wyludzaniem kasy

**Comment by krystian3w** [comment]
Tylko linki do:
- Player 
- Chili 
- Ipla 
- `Gdzieobejrzec.co` - głównie Netflix
- `vod1.pl` - głównie Netflix

---

Raczej wycinać Chili per URL się nie opłaca jak nie mają jeszcze filmu a otwiera się spis na Chili z podobnymi lub starszy.
