### ISSUE TITLE
rossmann-rozdawanie.eu

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1368]
https://www.dobreprogramy.pl/Bon-do-Rossmanna-na-250-zlotych-powraca.-Uwazajcie-strona-wyludza-dane,News,108039.html

**Comment by hawkeye116477** [comment]
Aktualizacja listy będzie o 13 :smile:

**Comment by krystian3w** [comment]
A dodatkowo w niedzielę już się zwinęli.

**Comment by hawkeye116477** [comment]
@krystian3w Strona jeszcze działa.
