### ISSUE TITLE
sklep.dagma.pl

### ISSUE THREAD

**Issue by FadeMind** [PolishFiltersTeam/KAD#1369]
`http://sklep.dagma.pl/`

Domena `http://sklep.dagma.pl/` aktualnie to pusta strona, ale aktywny adres.
Łatwo o literówkę, ponieważ oryginalny oficjalny sklep ma domenę `[com] [dot] [pl]` na końcu.

**Comment by hawkeye116477** [comment]
No niby pusta, choć Vivaldi ostrzega, że hakerzy się włamali i może faktycznie coś nie gra, bo sama `dagma.pl` jest od 1999 roku i na głównej nic nie ma o żadnym sklepie...

**Comment by krystian3w** [comment]
Raczej IT nie przeniosą.

**Comment by krystian3w** [comment]
Chyba coś zaczęli działać, już przekierowuje na `https` z ostrzeżeniem i brakiem opcji dodania dopuszczenia z błędnym certyfikatem.

**Comment by krystian3w** [comment]
Już wydaje się offline.

Ciekawe czy 30 dni będzie wyparowywać z Google:

![obraz](https://user-images.githubusercontent.com/35370833/83195416-7917cf00-a13a-11ea-8443-27665b609552.png) |
--- |
