### ISSUE TITLE
Odnośnie "pseudonauki"

### ISSUE THREAD

**Issue by tafola7531** [PolishFiltersTeam/KAD#1375]
> 
> ### Nieprawdziwe, wprowadzające w błąd informacje lub podobne.
> #### False, misleading information or similar.
> 

Dokładnie tak jak powyżej napisane, hipokryci, sami wprowadzacie w błąd oraz promujecie pseudonaukę poprzez BRAK DOŚWIADCZENIA w wielu tematach, które blokujecie. Blokujecie wolność informacji i wypowiedzi „jedynie robiąc swoje obowiązki”. Blokujecie rozwój i naukę właśnie, najbardziej przez własny brak odpowiednich kwalifikacji i na pewno „brak czasu” na myślenie.

Polecam zażyć więcej DOŚWIADCZENIA, zanim zacznie się kreować postrzeganie świata innych ludzi poprzez swoje filtry, które jak już było wspomniane w innym miejscu (odnośnie do strony wolnemedia), nie są zgodne z konstytucją, utrudniacie dostęp do informacji zwykłym ludziom. Ja naprawdę rozumiem, że ludzie ogólnie są głupi, i nie odróżniają prawdy od fikcji, ale to się tyczy was też, widać przecież co jest blokowane i jaka jest tendencja twórców...

To że coś jest „kontrowersyjne” albo ma wiele „negatywnych opinii” NICZEGO NIE DOWODZI, a bardzo często dowodzi tylko braku wiedzy ze strony krytykantów, albo że jest na „to coś” nagonka medialna. I to właśnie jest „kontrowersyjne”, czyli „nie wiem i się wypowiem”, bo tylko głupki mają niejasności jakieś i kontrowersje... Wstyd, a nie filtr dla lepszego Internetu.

W kółko muszę odblokowywać strony typu:
* `wykop.pl`,
* `zmianynaziemi`, 
* `innemedia`...

Z całym szacunkiem dla pracy włożonej w filtry, z szacunku do PRAWDY OBIEKTYWNEJ radze przestać manipulować życiem innych wpychając swoje łapy w to, co jest „kontrowersyjne” i radzę ten filtr zrobić oddzielnie, jak to jest tylko kilka linijek, to co komu szkodzi zrobić to oddzielnie?

Nie nie każdemu chce się uczyć obsługi komputera, a jako informatyk dodaję filtry w wielu urządzeniach i później weź to człowieku ręcznie każdemu kowalskiemu pomagaj później, bo nie wiedzą co to jest adblock w ogóle.

Oddzielny filtr rozwiązałby sprawę tymczasowo, dopóki autor filtrów czy tam któryś użytkownik się nie doedukuje na tematy, na które czyta i myśli że na pewno ma racje, bo tak czuje albo widzi :) tzn. zobaczy że zablokowane to pomyśli że tak jest dobrze, a to błąd, blokują (blokujecie) nam dostęp do wiedzy.

Widać tu silny nurt anty-anty-systemowy i pro-big-pharma w wielu blokowanych linkach. Nie popieram. Nie popieram niewolnictwa spowodowanego brakiem informacji, czyli głupotą, a w tym wypadku cenzor wspomaga niewolnictwo umysłowe i do tego jeszcze depopulację, nieważne świadomie czy nie, widzę fakt.

To już nie jest ani śmieszne, ani to nie jest zabawa.

Autorzy filtrów zacznijcie traktować świat na poważnie wreszcie, ja wiem jak jest, ale postarajcie się, chociaż ZROZUMIEĆ, O CZYM MOWA.

**Comment by krystian3w** [comment]
Projekt jest rodzielony pewnie maksymalnie 1 procent dosubskrybował.

Nie chcesz się szczepić to twój problem lub jak się perhydrolem dożylnie leczysz.

**Comment by krystian3w** [comment]
Wykop nie jest blokowany filtrami, możesz nawet próbować w historii comittów to zweryfikować.

**Comment by hawkeye116477** [comment]
Już jakiś czas temu sprawy się zmieniły, jest wszystko rozdzielone, więc nie musi tu pan wykładu robić.

**Comment by MajsterMechazod** [comment]
> Z całym szacunkiem dla pracy włożonej w filtry, z szacunku do PRAWDY OBIEKTYWNEJ radze przestać manipulować życiem innych wpychając swoje łapy w to, co jest „kontrowersyjne” i radzę ten filtr zrobić oddzielnie, jak to jest tylko kilka linijek, to co komu szkodzi zrobić to oddzielnie?

Tak jak napisali poprzednicy - sekcja fake newsów została oddzielona i nie stanowi integralnej części. Cały czas decyzją użytkownika pozostaje subskrypcja listy i jednej, i drugiej. KAD nigdzie nie jest domyślnie włączony. Został ten temat poruszony w zgłoszeniu #1326 

> 
> W kółko muszę odblokowywać strony typu:
> `wykop.pl`

Filtr KAD nie blokuje i nigdy nie blokował tej strony. Musi odpowiadać za to inny filtr.

> Nie nie każdemu chce się uczyć obsługi komputera, a jako informatyk dodaję filtry w wielu urządzeniach i później weź to człowieku ręcznie każdemu kowalskiemu pomagaj później, bo nie wiedzą co to jest adblock w ogóle.
> 
> Oddzielny filtr rozwiązałby sprawę tymczasowo, dopóki autor filtrów czy tam któryś użytkownik się nie doedukuje na tematy, na które czyta i myśli że na pewno ma racje, bo tak czuje albo widzi :) tzn. zobaczy że zablokowane to pomyśli że tak jest dobrze, a to błąd, blokują (blokujecie) nam dostęp do wiedzy.

Pan jest z wykształcenia informatykiem, ja posiadam wykształcenie medyczne. Nie jestem związany z projektem filtra inaczej, niż dobrowolnie zgłaszając tutaj scamy, ale gwarantuję, że większość stron typu fake newsów z nauki to ma tylko przedrostek "pseudo-". Mimo wszystko rozumiem, że każdy ma swoje poglądy i jestem zdania, że nikt nikomu nie powinien nic narzucać - i taki wybór ma użytkownik. 

> Jak komuś raz na rok aktualizujesz plik hosts to czas chyba przerzucić się z zwykłego notatnika na coś z harmonogramem zadań / cronem.

Lepiej użyć [nextDNS](https://nextdns.io/) dla laików. [Threat Intelligence Feeds subskrybuje listę hostów KAD (bez kontrowersji)](https://github.com/nextdns/metadata/issues/244).
