### ISSUE TITLE
appstorepost.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1382]
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/49841035/nie-wiem-skad-ten-syf-ma-moj-numer-telefonu-zaklad/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
2 godziny temu już zrobione. Proszę aktualizować listę przed utworzeniem zgłoszenia :smile:.

https://github.com/PolishFiltersTeam/KAD/commit/3a1e206970bb9e81f918ad5e13c17038146a4cef
