### ISSUE TITLE
reguła uszkadza strony

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/KAD#1387]
```
||wp.*.top^
```

**Comment by hawkeye116477** [comment]
@KonoromiHimaries Np które?

**Comment by KonoromiHimaries** [comment]
@hawkeye116477 zagraniczne

**Comment by KonoromiHimaries** [comment]
```
i1.wp.com
```

**Comment by hawkeye116477** [comment]
@KonoromiHimaries Ale tam nic nie ma....

`Sorry, the parameters you provided were not valid`

**Comment by KonoromiHimaries** [comment]
@KonoromiHimaries

**Comment by krystian3w** [comment]
`||wp.6645478.top^` jak nie pomoże ograniczenie do `document` to może regex z cyframi.

**Comment by hawkeye116477** [comment]
Adres jesthttps://i1.wp.com/static-assets.droidbuzz.top/images/logo-100.png?quality=100
