### ISSUE TITLE
shop.brkcenter.com + itpesthetique.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1394]
### Dodatkowe informacje mogące mieć znaczenie
Nowe strony na liście legalne w sieci

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
`shop.brkcenter.com`

Strona jest po angielsku, nie ma polskiego do wyboru, więc odpada.
