### ISSUE TITLE
sterburty.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1397]
### Dodatkowe informacje mogące mieć znaczenie
Brak towaru, Brak kontaktu, pieniądze przepadły 

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
Ale problem w tym, że nie ma takiej domeny...

**Comment by krystian3w** [comment]
Może się zwinęli, może czas na awaryjne wysłanie stron w `Archive.Today` / `Archive.org`?

**Comment by hawkeye116477** [comment]
Zwykle jeżeli się zwijają, to chociaż jest podana data wygaśnięcia. A jeżeli nie ma w rejestrze domen, to zwykle bywa raczej tak, że zwinęli się bardzo dawno... Więc albo naprawdę  sporo czasu już minęło i pani ze zgłoszenia dopiero sobie przypomniała albo jakaś literówka, bo naprawdę dziwna sprawa, nigdzie nie mogę znaleźć jakiejkolwiek wzmianki o tej domenie...

**Comment by krystian3w** [comment]
Mnie to najwyżej śmierdzi #1241 niby ktoś chciał sprzedać buty ale nie miał słownika i zaakceptował "sterbu**R**tę"
