### ISSUE TITLE
www.nav-pl.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1398]
### Dodatkowe informacje mogące mieć znaczenie
Podmienia stronę startową wyników wyszukiwania

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Na Adware to AdwCleaner i Mawlwarebytes:

* AdwCleaner
   * https://pl.malwarebytes.com/adwcleaner/ (brak wersji na macOS i telefony)

* Mawlwarebytes
   * https://pl.malwarebytes.com/mwb-download/thankyou/ (Windows)
   * https://pl.malwarebytes.com/mac/
   * https://pl.malwarebytes.com/android/
   * https://www.malwarebytes.com/ios/

**Comment by hawkeye116477** [comment]
Jest jeszcze https://safegroup.pl/ i https://malwaretips.com/.

**Comment by krystian3w** [comment]
Na pierwszym miesiąc od aktywności użytkowników, może i wolontariusze odeszli, a angielski może być dalej ścianą.

Na elektrodzie to przynajmniej `Kolobos` się nie poddaje.

**Comment by hawkeye116477** [comment]
`Na pierwszym miesiąc od aktywności użytkowników`

Tzn. miesiąc temu ktoś doradzał, choć niby `39 użytkowników aktywnych w ciągu ostatnich 30 minut` :smile:.

**Comment by krystian3w** [comment]
W sumie los niepewny bo autor silnika niby miał ubić domenę i trzeba by z innej robić aktualizacje lub udawać że w silniku nie ma luk i spam kasować ręcznie.
