### ISSUE TITLE
Kilka stron z legalniewsieci.pl

### ISSUE THREAD

**Issue by MajsterMechazod** [PolishFiltersTeam/KAD#1402]
```
beciki.pl
feniks-tm.pl
gadzety.club
reklamanazuku.pl
remex-barnas.pl
szaszlyk.club
```
https://www.legalniewsieci.pl/aktualnosci/podejrzane-sklepy-internetowe

**Comment by krystian3w** [comment]
Mamy do tego skrypt, tyle że trzeba najlepiej odpalać z GNU/Linux lub dobrze skonfigurowanego WSL (by działała opcja sprawdzania czy domena jest jeszcze w WHOIS).

**Comment by hawkeye116477** [comment]
> by działała opcja sprawdzania czy domena jest jeszcze w WHOIS

Jakiś czas temu już to zmieniłem, teraz sprawdza tylko za pomocą `host` czy strona działa.

**Comment by xMaap** [comment]
Hm a tutaj czasami przy aten.com nie wkradł się https?
![2020-06-20 07 36 01 github com 15e68f6672d4](https://user-images.githubusercontent.com/36385327/85193450-db429a80-b2c8-11ea-970b-46517329fb8a.png)

**Comment by krystian3w** [comment]
Poprawny wpis, oni nie nie mieli na serwerze przekierowania na wersję z `www.` i najkrótszy adres nie miał prawidłowego certyfikatu SSL.
