### ISSUE TITLE
cda-tv.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1406]
### Dodatkowe informacje mogące mieć znaczenie
Przekierowuje na zablokowane „https://cda-tv.online/”.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Ostrzeżenie jest o złośliwych reklamach:


[MajkiIT/polish-ads-filter#16260 (comment)](https://github.com/MajkiIT/polish-ads-filter/issues/16260#issuecomment-633223413)
[MajkiIT/polish-ads-filter#16260 (comment)](https://github.com/MajkiIT/polish-ads-filter/issues/16260#issuecomment-633223213)
