### ISSUE TITLE
Nowy filtr wyszukiwania dla popularnych wyszukiwarek?

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/KAD#1407]
przykład `https://addons.mozilla.org/en-US/firefox/addon/add-custom-search-engine/`

```
https://duckduckgo.com/?q=-site:TuDomenaStrony.pl%20%s
```

##

inny przykład `https://addons.mozilla.org/en-US/firefox/addon/searchmage-search-enhancer/`

**Comment by krystian3w** [comment]
Y...

**Comment by hawkeye116477** [comment]
@KonoromiHimaries A co to ma wspólnego z KADem? To rozszerzenie jest po angielsku i raczej takich pojedynczych nie blokujemy, jeśli to jakieś niebezpieczne rozszerzenie, to raczej zgłosić trzeba do Mozilli.

**Comment by krystian3w** [comment]
Raczej chodziło może by łatwiej użyć filtra `site:` jakby szukać tych cyferkowych subdomen co kiedyś znalazłeś, bo Google ładnie zindeksował.
