### ISSUE TITLE
mikamayclothing.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1413]
https://teleshow.wp.pl/christian-paul-amerykanski-projektant-mody-z-tvp-istnieje-a-raczej-zaczal-istniec-na-youtube-6524569064119136a

**Comment by krystian3w** [comment]
Ale podróbka po angielsku i brak tłumacza Google. Wątpię by czytelnik WP wydał 1 566,25 - 2 194,33 zł na strój / sukienkę.
