### ISSUE TITLE
vubu.pl

### ISSUE THREAD

**Issue by MajsterMechazod** [PolishFiltersTeam/KAD#1416]
### Dodatkowe informacje mogące mieć znaczenie
Dużo negatywnych opinii w serwisie Opineo:
https://opineo.pl/opinie/vubu-pl/2

**Comment by hawkeye116477** [comment]
Na fejsie też jakiś antyfanpage jest => https://www.facebook.com/vubu.opinie/posts/247148642407475/, filmik na YT => https://www.youtube.com/watch?v=Etu2ogGzX58.

Vubu niby powstało w 2013, z tego co czytałem to na początku chyba było ok, a po jakimś czasie zaczęły się problemy.

**Comment by MajsterMechazod** [comment]
https://www.legalniewsieci.pl/aktualnosci/oszustwo-czy-nie-oszustwo-oto-jest-pytanie

> **O co chodzi ze sklepem vubu.pl?**
Ten sklep od kilku lat wywołuje skrajne emocje wśród użytkowników. Sklep posiada ponad 500 tys. lajków na Facebooku, a jednocześnie liczne negatywne opinie zarówno w serwisie CENEO, jak i na Facebooku. Wielu klientów sklepu jasno szufladkuje go jako oszustwo. Powstały na ten temat 3 osobne grupy na Facebooku.
> 
> Jednocześnie z informacji znacznej części klientów sklepu wynika, że sklep realizuje zamówienia – co potwierdzają zdjęciami otrzymanych produktów. Wszyscy klienci zgadzają się jednak, że sklep ma problem ze zwrotem środków w przypadku odstąpienia od umowy. Zgodnie z ustawą o prawach konsumenta – sprzedawca ma max. 14 dni na zwrot pieniędzy od dnia otrzymania oświadczenia konsumenta o odstąpieniu od umowy.
> 
> Art. 32. [Zwrot przedmiotu świadczenia oraz płatności]
> 1. Przedsiębiorca ma obowiązek niezwłocznie, nie później niż w terminie 14 dni od dnia otrzymania oświadczenia konsumenta o odstąpieniu od umowy, zwrócić konsumentowi wszystkie dokonane przez niego płatności, w tym koszty dostarczenia rzeczy.
> 
> Tymczasem, jak wynika z komentarzy klientów vubu.pl, sklep dokonuje zwrotu ze znacznym opóźnieniem sięgającym nawet kilka miesięcy!
>
