### ISSUE TITLE
inpost.live

### ISSUE THREAD

**Issue by FadeMind** [PolishFiltersTeam/KAD#1417]
`https://inpost.live/app/`

Źródło : FB > grupa Sekurak 
![20200626-1593159540-001](https://user-images.githubusercontent.com/9846948/85836501-f1ec6400-b796-11ea-90d4-7be863fd7c40.png)

![20200626-1593159796-001](https://user-images.githubusercontent.com/9846948/85836568-0fb9c900-b797-11ea-8835-371e38eb7683.png)

**Comment by krystian3w** [comment]
Hosting częściowo zbanował pytając po angielsku czy na pewno chcemy wejść, ale to chyba za mało.

Google też już zbanowało.

**Comment by FadeMind** [comment]
@krystian3w 
![20200626-1593173670-001](https://user-images.githubusercontent.com/9846948/85855981-69ca8680-b7b7-11ea-8e4d-e269bf3d8458.png)
