### ISSUE TITLE
blokada getin-secure-bank.xyz blokuje cały internet (UBO dev build)

### ISSUE THREAD

**Issue by Yhonay** [PolishFiltersTeam/KAD#1418]
W linii blokującej
`||getin-secure-bank.xyz‎^$all`
wkradły się niedrukowalne znaki które w ublock origin dev build 1.27.11rc8 powodują stworzenie reguły
`*$document`
skutkującej blokowaniem _wszystkiego_.

![image](https://user-images.githubusercontent.com/668573/85931374-56591180-b8c4-11ea-8f19-4b7815e2e659.png)

**Comment by hawkeye116477** [comment]
Najwyraźniej stabilny uBO i AdGuard po prostu olewali tą regułę czy coś, a w dev coś się zmieniło. Zainstalowałem [śledzenie gremlinów](https://marketplace.visualstudio.com/items?itemName=nhoizey.gremlins) do VS Code, by zapobiec temu w przyszłości :smile:.

**Comment by krystian3w** [comment]
https://stackoverflow.com/questions/10342012/wordpress-putting-e2808e-at-the-end-of-my-url-howcome

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KADhosts/issues/31
