### ISSUE TITLE
ebonplus.com

### ISSUE THREAD

**Issue by MajsterMechazod** [PolishFiltersTeam/KAD#1419]
### Dodatkowe informacje mogące mieć znaczenie

pośrednia strona: `http://ebonplus.com/polo`
docelowa: `https://firezat.com/nomad/tracking.php`

https://www.wykop.pl/wpis/50354441/ciekway-rodzaj-scamu-wpadl-mi-do-skrzynki-jacys-je/

**Comment by krystian3w** [comment]
Ja mam na odwrót z stroną docelową i przekierowaniem.

**Comment by hawkeye116477** [comment]
ebonplus, 404 - https://www.hybrid-analysis.com/sample/8382971b64ddc8a0795404bb543876282d2dca49e84f21cfaabf2b3c6fc46362/5ef85a853e352718e3270948

firezat => https://www.hybrid-analysis.com/sample/ebc1427b6c19c656d569c4c87f7b3ce32bdde680501ae77030bf1661a61fc4a4/5ef85776a99a3b794f5b4b9e

**Comment by krystian3w** [comment]
Strona jest starsza: https://www.hppr.org/post/wrapping-home-baked-potato-can-save-it-wildfire-study-finds więc ktoś musi ocenić poziom angielskiego czy to nie próba z kilkomiesięcznym maskowaniem jako USA by Google wolało nie banować całości.

**Comment by krystian3w** [comment]
Co do błędu 403 to może blokada geo-regionalna, że hosting nie działa poza Polską lub Europą.

**Comment by hawkeye116477** [comment]
Firezat, data stworzenia to 2006 r, ebonplus.com - 2017 r.

**Comment by krystian3w** [comment]
Czyli najpewniej luka w ich CMS / serwerze i ktoś sobie wykorzystał.

Zobaczymy czy Amerykanie naprawią, bo Irańczycy raczej nie?

**Comment by krystian3w** [comment]
CERT.pl zbanował Iran, skrypt umie sprawdzić plik `przekierowujace_do_przekretow.txt`?

**Comment by hawkeye116477** [comment]
@krystian3w Skrypt porównuje do KADhosts.

**Comment by krystian3w** [comment]
A i padło `ebonplus.com/polo` - 404 czyli teraz czekamy aż USA oczyści serwer (trochę lipa że pewnie CERT nie zrobi ponownej analizy strony - niby tylko 3 wpisy usunęli i niby nie czyszczą domen usuniętych).

**Comment by krystian3w** [comment]
Strony posprzątały syf.
