### ISSUE TITLE
ippko.website

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1430]
### Link bezpośredni 
`https://ippko.website/Millenium-Prezent/`
### Dodatkowe informacje mogące mieć znaczenie
Wyłudzenia danych logowania bankowego.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
https://github.com/PolishFiltersTeam/KAD/commit/59081a2a77358cfcccdcbdcdd67efc8d8a14123b

**Comment by krystian3w** [comment]
A skrypt na wykrywanie losowych kombinacji jest?
