### ISSUE TITLE
FitGirl Repacks

### ISSUE THREAD

**Issue by Thuijoss** [PolishFiltersTeam/KAD#1431]
Skoro w KAD znajduje się `||skidrowcrack.com^$all` (pomimo braku polonizacji strony), to może warto byłoby dodać `fitgirlrepacks.co`, `fitgirl-repack.net`, `fitgirl-repacks.cc`, `fitgirl-repack.com`, które podszywają się pod `fitgirl-repacks.site`?

**Daty rejestracji wypadają następująco:**
✅ `.site`  -> 2016.09.01
❌ `.co`    -> 2019.08.26
❌ `.com` -> 2019.10.29
❌ `.net`   -> 2020.01.24
❌ `.cc`     -> 2020.01.28

> **Special note about impostors:**
> This site, fitgirl-repacks.site is THE ONLY official site of my repacks. Every single FG repack installer has a link inside, which leads here. ALL other “mirrors” (fitgirlrepacks.co, fitgirl-repacks.cc, fitgirl-repack.com, etc.) are fakes, made to infect you with malware, show you tons of ads and get your money as donations. Don’t fall for them during your google sessions, just bookmark (CTRL+D) this site and come here directly.

**Comment by Thuijoss** [comment]
Zostaje do przeanalizowania jeszcze `fitgirlrepack.games`

**Comment by hawkeye116477** [comment]
> Skoro w KAD znajduje się ||skidrowcrack.com^$all (pomimo braku polonizacji strony)

Ta strona została dodana jakby to powiedzieć - przed erą PolishFiltersTeam, wtedy być może czasem były też dodawane nie spolonizowane strony. Teraz polityka się nieco zmieniła.
