### ISSUE TITLE
il.ink/nagroda_gwarantowana

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1432]

**Comment by krystian3w** [comment]
Wygląda na legalną stronę - coś jak `bit.ly`.

https://github.com/PolishFiltersTeam/KAD/blob/d209d27a22fe2ad584cda6e0053eaec96f8d8555/sections/przekierowujace_do_przekretow.txt#L71

Niby ubija otwarcie przekrętu podpięty pod `https://golead[.]pl/p/eVlP/fHFs/5FSS`

**Comment by hawkeye116477** [comment]
https://il.ink/report

**Comment by krystian3w** [comment]
Tyle że nie działa:

![obraz](https://user-images.githubusercontent.com/35370833/86605484-0efb1100-bfa7-11ea-9a97-23050f829d56.png)


Nie wiem czego nie znaleźli, raczej bez szklanej kuli nie podam im linka do profilu scammera.

Opcjonalnie to próba zamaskowania, że już mają jakieś zgłoszenie i przetwarzają po 1 i blokują dalsze raportowanie...
