### ISSUE TITLE
skladaniekomputera.pl

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/KAD#1434]
Czemu blokujecie PDF-a na stronie ( na dole ) ? .

**Comment by krystian3w** [comment]
`||getleads.pl^$document` - ktoś po prostu zablokował linki afiliacyjne.

**Comment by krystian3w** [comment]
Z wad tego poradnika to jest:

- wpisywanie się na subskrypcje śmieci od pana `marcin.gurtowski@gmail.com` / `dario.orzechowski@gmail.com`.
- poradnik na 2 próby to nie przyszedł po zatwierdzeniu subskrypcji ani nie mam linka który by otworzył etap drugi.

**Comment by hawkeye116477** [comment]
https://github.com/PolishFiltersTeam/KAD/commit/e861acf2f2610bc0fd7fc031f791ef1de9cadb7e
