### ISSUE TITLE
telewizja.cc

### ISSUE THREAD

**Issue by xxcriticxx** [PolishFiltersTeam/KAD#1438]

**Comment by krystian3w** [comment]
U mnie działa, niby mają "30 sekundowe" opóźnienie ale nie straszą.

**Comment by krystian3w** [comment]
Co do anty-blokady DDoS to oni coś sobie ją źle zaimplementowali, że wisi dłużej niż 5 sekund.

**Comment by xxcriticxx** [comment]
ja mam wlasnie ddos loop 

a w robocie: 

This site has been blocked because it is on the blocked country list.
Block reason: Gateway GEO-IP Filter Alert
IP address: 185.178.208.168
Connection initiated towards country: Russian Federation

**Comment by krystian3w** [comment]
To odśwież jak minie minuta, na geo-lock kad nie pomoże ani ban się za to nie należy.

**Comment by xxcriticxx** [comment]
ok zamykamy
