### ISSUE TITLE
detoxpolska.pl

### ISSUE THREAD

**Issue by FadeMind** [PolishFiltersTeam/KAD#1439]
`detoxpolska.pl`

> Tachionizowane dyski krzemowe i inne produkty Tachionizowane pomagają w naprawie urazów ciała, równowagi narządów, wzmocnieniu układu odpornościowego i poprawy wyników sportowych. Ochraniają cię przed szkodliwymi falami EMF, 5G i przed promieniowaniem elektromagnetycznym poprzez regulacje naszych subtelnych pól energii.
> 
> Poszukując darmowej energii, profesor David Wagner początkowo teoretyzował - a następnie udowodnił - istnienie energii tachyon. W wyniku prac Dawida Wagners możemy wyobrazić sobie świat, w którym można zmobilizować niezwykłą moc tachionu, aby pomóc chronić, energetyzować, odmładzać i równoważyć ludzkie ciało. Energia z tachionów jest dostępna tylko w produktach przetwarzanych w procesie tachionizacji, i wiekszość tych produktów jest dostępne na tej stronie. Profesor Wagner wynalazł proces tachionizacji w 1990 roku i od tego czasu tworzy produkty zdrowotne , które służą w pomocy utrzymania najlepszego zdrowia.

bo wiecie, 5G, szczepionki od Gatesa i Illuminati.

**Comment by krystian3w** [comment]
Już jest, niestety raczej KAD nie ma fizycznie numerka na KAD Fake pewnie.

https://github.com/PolishFiltersTeam/KAD/blob/2a9098d0e964b695a1d6c155a9945e1855dea83e/sections/pseudonauka_fake_news.txt#L5

Niby najlepiej było rozdzielić by nie ciągać się po sądach - niby umieją grzebać w dark necie za bazą np. morele.net...

**Comment by hawkeye116477** [comment]
@krystian3w W takim razie nie ma co przemyślać. Temat zamykamy :smile:..
