### ISSUE TITLE
jednoslad.pl

### ISSUE THREAD

**Issue by gargul4** [PolishFiltersTeam/KAD#1440]
Podobne do mojego poprzedniego zgłoszenia https://github.com/PolishFiltersTeam/KAD/issues/1422,  albo jakiś błąd na stronie albo strona złapała jakiegoś syfa, który przy okazji uszkodził arkusz styli i dodatkowo spowodował, że strona ładuje się w nieskończoność i nie może się załadować przez co pojawia się komunikat" Strona spowalnia działanie przeglądarki".

![capture_009_15-07-2020_13-46-20](https://user-images.githubusercontent.com/67454905/87541910-603f8a80-c6a2-11ea-8916-2f2f4344b59e.gif)

**Comment by krystian3w** [comment]
To chyba infekcja gdzieś w CNAME, EdgeHTML ładuje szybko bez awarii.

**Comment by krystian3w** [comment]
Konfilkty na Firefox robi: 

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 | `\|\|www.jednoslad.pl/wp-content/cache/busting/1/*/ui/*slider*11.$script,domain=www.jednoslad.pl` | -- | `www.jednoslad.pl` | 1 | script | `https://www.jednoslad.pl/wp-content/cache/busting/1/wp-includes/js/jquery/ui/slider.min-1.11.4.js` |
| +1 | `\|\|www.jednoslad.pl/wp-content/cache/busting/1/*/ui/*slider*11.$script,domain=www.jednoslad.pl` | -- | `www.jednoslad.pl` | 1 | script | `https://www.jednoslad.pl/wp-content/cache/busting/1/wp-includes/js/jquery/ui/slider.min-1.11.4.js` |

Z wad, to niby czysty plugin do menu:

![Screenshot_2020-07-16 Motocykle 125, Skutery, Motorowery Opinie, Testy, Forum Portal Motocyklowy Jednoślad pl](https://user-images.githubusercontent.com/35370833/87637865-26729080-c743-11ea-9aa7-8872ab6132a8.png) |
--- |
