### ISSUE TITLE
kasyno-pl.fun

### ISSUE THREAD

**Issue by Thuijoss** [PolishFiltersTeam/KAD#1448]
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/51072809/scam-na-algorytm-do-gry-w-wirtualnym-kasynie-tl-dr/

**Comment by xMaap** [comment]
@krystian3w ja bym dodał też vulkanvegas-24.com/pl bo kasyno-pl.fun przekierowuje na vulkanvegas

**Comment by xMaap** [comment]
Jeszze przed tym robi przekierowanie do 
`https://vegas777spin.com/?s=54&encoded_url=IyEvYXV0aC9yZWdpc3Rlcj9jbGlja19pZD0lMjUlMjVjbGlja19pZCUyNSUyNQ==&click_id=%%click_id%%`

Jeszcze
vulkanvegas-offers.com

Po wyszukaniu w Google "vulkanvegas-offers.com"
kasyno-online-vulkan.pl/pl
