### ISSUE TITLE
torrentu.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1462]
### Dodatkowe informacje mogące mieć znaczenie
Wydaje się scamem

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
Strona założona pod koniec tego roku w marcu.

**Comment by krystian3w** [comment]
Brak opcji rejestracji, dużo przekierowań:

`torrentu.pl/logowanie.html` > `torrentu.pl/rejestracja.html` > `leadtrack.pl` > `t.fileman.pl`
