### ISSUE TITLE
pol-news24.pl ==> lokalneinformacje.pl ==> leadtrack.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/KAD#1476]
https://github.com/olegwukr/polish-privacy-filters/issues/106

Strona w tej chwili to chyba zamieniła się w malware / zhackowana bo:

**1** po wejściu na: `http://pol-news24.pl/` przekierowuje na inną stronę typu malware / albo zhackowaną: `http://lokalneinformacje.pl/`, na której z kolei każdy link znowuż przekierowuje na kolejną jakąś syfiastą stronę: `https://leadtrack.pl/p_uri2/d3NsUHc0VlpWMXJBek1pOVJnZmFxNHJTd0QzZUdGZW9nMU4xV2lPeWRyQT0/?parametr=` blokowaną przez filtry

**2** z kolei po wejściu na: `https://pol-news24.pl/` lub artykuł np. https://github.com/olegwukr/polish-privacy-filters/issues/106#issue-499761819, przekierowanie jest blokowane przez przeglądarkę (Firefox) ale:
- nie wiem czy na innych przeglądarkach również, 
- nie jestem również pewien czy KAD hosts bazuje na tym co blokowane przez przeglądarki czy jest niezależne

**Comment by krystian3w** [comment]
Blokada błędu `https`, to nie dziwne, że się nie da otworzyć.

Nie mamy jak tego implementować z pomocą uBO/AdGuard/HOSTS.

**Comment by gargul2** [comment]
> Blokada błędu `https`, to nie dziwne, że się nie da otworzyć.

Wiem, a czy ja gdzieś pisałem, że dziwne...w kontekście chodziło nie o to, że jest dziwne, że przeglądarka blokuje stronę, lecz o uwiarygodnienie, że skoro strona jest blokowana przez przeglądarkę, to tymbardziej jest niebezpieczna / malware / zhackowana i kwalifikuje się na listę KAD.

> Nie mamy jak tego implementować z pomocą uBO/AdGuard/HOSTS.

- tu literówka z mojej strony, chodziło mi o listę KAD do adblockerów, a nie o wersję hosts listy KAD, dodało mi się niechcący słowo "hosts",
- poza tym już nie istotna ta kwestia KAD, bo zapomniałem, że i tak KAD blokuje obywa protokoły na raz (`http` i `https`) za pomocą `||` np. `||pol-news24.pl` (więc to, że `https://pol-news24.pl` jest już blokowane przez przeglądarkę nie ma znaczenia)
