### ISSUE TITLE
biznesoweinfo.miasta.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1488]
```
http://biznesoweinfo.miasta.pl/kobietywyznanie/
https://moneynew.investmarket.info
http://investmarket.info
```

**Comment by xMaap** [comment]
Przed przekierowaniem na moneynew.investmarket.info jeszcze wcześniej wchodzi na 

`https://go.foxoffers.com/visit/?bta=35982&nci=5475&afp=Phc6izNrZFg4Hk1LSvR8PH`

**Comment by krystian3w** [comment]
Niby nieładnie blokować alfikację.

**Comment by xMaap** [comment]
Zawsze można do nich napisać i zobaczyć jak zareagują na biznesoweinfo. Jak oleją to widocznie na takie coś pozwalają.

**Comment by krystian3w** [comment]
Oksana M. z 🦊 się pyta co przekierowało cię na `go.foxoffers.com`, że potem widzisz scam na `"TrustPilot"`.

Na obecną chwilę, to mnie się urwał ciąg i nie umiem jej wskazać źródła "poprzedzającego".
