### ISSUE TITLE
londontrade.exchange

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1489]
Strona ma możliwość tłumaczenia przez Google
https://forexclub.pl/swisstrade-exchange-i-3-inne-podmioty-na-liscie-ostrzezen-knf/

Jeszcze jest, ale coś im się zepsuło i nie wiem czy jest po polsku.
`http://grandtrade.exchange`

**Comment by MajkiIT** [comment]
@xMaap chyba strona już wyleciała

**Comment by krystian3w** [comment]
Niby lepiej poczekać aż whois wygaśnie, przynajmniej długo nie reaktywują starych linków z innym hostingiem (chyba, że inni oleją powód jakby ich wykreślono).

**Comment by xMaap** [comment]
londontrade
![2020-09-14 12 53 22 londontrade exchange 4da5bc9c2fdf](https://user-images.githubusercontent.com/36385327/93077637-5d085100-f689-11ea-8de7-07cd32e86d6f.png)
