### ISSUE TITLE
Prośba o zweryfikowanie dodanych stron - natural.pl

### ISSUE THREAD

**Issue by Cestis** [PolishFiltersTeam/KAD#1490]
Dzień dobry,
piszę do Państwa w imieniu firmy Natural Pharmaceuticals. Zostaliśmy dodani na Państwa filtr antyspamowy:
https://github.com/PolishFiltersTeam/KAD/issues/1471
https://github.com/PolishFiltersTeam/KAD/commit/ca4569aac4577a31f61cd578699f3745ab1adf28

uważamy jednak, że jest to błąd. Każdy klient jest informowany o kosztach, jakie ponosi. Oto pierwszy obrazek, który można zobaczyć po wejściu na zablokowaną stronę witaminazadarmo.pl:
![image](https://user-images.githubusercontent.com/36989635/93067948-2415af80-f67c-11ea-9fde-a221c09a0d54.png)

widać tutaj wyraźną informację o koszcie przesyłki. Tę i wiele innych kwestii wyjaśnia również sekcja FAQ na stronie: https://witaminadzadarmo.pl/pytania-i-odpowiedzi

Dodatkowo, nasze strony:
- nie zawierają reklam
- nie zawierają przekierowań na żadne zewnętrzne strony

Oferujemy również przejrzyste FAQ dla klientów dostępne pod linkiem: https://natural.pl/czesto-zadawane-pytania/
Znajdują się tam wszystkie informacje potrzebne do zwrotu produktu czy reklamacji.

Podsumowując, firma działa uczciwie; informuje o kosztach wysyłki darmowych próbek oraz oferuje prawo do odstąpienia od umowy bez podania przyczyny w ciągu 30 dni od daty odebrania przesyłki.
Proszę o zweryfikowanie słuszności dodania tych dwóch stron: natural.pl, witaminazadarmo.pl.

W razie pytań zapraszam.
Dzięki!

**Comment by Thuijoss** [comment]
Oprócz wspomnianego artykułu ze zgłoszenia #1471, znalazłem w sieci dodatkowe materiały, które mogą być pomocne w dyskusji: 
* https://f.kafeteria.pl/temat-5389464-natural-pharmaceuticals-spzoo/
* https://www.google.com/amp/s/forumprawne.org/amp.php%3ft=474100
* https://www.google.com/search?hl=pl&q=Natural+Pharmaceuticals+rezygnacja&sa=X&ved=2ahUKEwi1yeef7OjrAhXvwosKHdufB94Q1QIwEHoECA0QBg&biw=375&bih=635#trex=m_t:pqaQ,rc_fid:0x4719326fb232857b%253A0xe0c26073d1ae99fb,rc_q:Natural%2520Pharmaceuticals%2520rezygnacja
* https://decyzje.uokik.gov.pl/bp/dec_prez.nsf/43104c28a7a1be23c1257eac006d8dd4/8415bc13866a0714c1257ec6007ba1db/$FILE/Decyzja%20nr%20RKT-25_2013%20z%2003.09.2013%20r.pdf

**Comment by Cestis** [comment]
Dzięki za linki! Pozwolę sobie również podlinkować materiały, w tym nieco bardziej aktualne:

- [wątek na pepper.pl, założony 12.2018](https://www.pepper.pl/promocje/darmowe-opakowanie-suplementu-omega-3-omegamarine-forte-128178)
- [wątek na zarabiam.com, założony 03.2019](https://zarabiam.com/Temat-darmowe-opakowanie-OmegaMarine-Forte-161793) (strona na ten moment nie działa, kopia pierwszej strony: [LINK](https://webcache.googleusercontent.com/search?q=cache:Z2oRsLHqX_8J:https://zarabiam.com/printthread.php%3Ftid%3D161793+&cd=1&hl=pl&ct=clnk&gl=pl))
- [artykuł na zakupersi.pl z dyskusją, założony 07.2017](https://zakupersi.com/promocja/darmowa-probka-suplementow-diety-z-kwasem-omega-3-od-omegamarine/)
- [dyskusja na polki.pl, założona 08.2016](https://rozmowy.polki.pl/przepisy,suplementy-natural-pharmaceuticals-warto-kupowac,214890,1,wypowiedzi.html)
- [archiwum regulaminów promocji - wszystko przejrzyście dostępne](https://natural.pl/regulaminy-promocji/)
- [potwierdzenie członkowstwa KRSiO](https://www.krsio.org.pl/pl/o-nas/czlonkowie/)

**Comment by krystian3w** [comment]
Ja dla mnie to nie ma poprawy niby numery telefoniczne i e-mail błędnie oznaczają, że jest zgoda na marketing.
