### ISSUE TITLE
Zdublowane 2 domeny

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1496]
||wszystko.biz^$all has been made redundant by ||wszystko.biz^$all
||trampoliny.club^$all has been made redundant by ||trampoliny.club^$all

**Comment by gargul2** [comment]
Tak samo jak [zdublowane 4 wątki](https://github.com/PolishFiltersTeam/KAD/issues?q=is%3Aissue+redundant) haha

**Comment by hawkeye116477** [comment]
> zdublowane 4 wątki, 

Nie liczy się, bo one są zamknięte.

**Comment by gargul2** [comment]
Sami trzymacie [zbiorcze wątki](https://github.com/PolishFiltersTeam/KAD/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+kilka) + [tu](https://github.com/MajkiIT/polish-ads-filter/issues/3318) też jest zbiorczy, więc chyba powinen być też zbiorczy dla duplikatów itp., chyba się [samozaorałeś](https://pl.wiktionary.org/wiki/samozaoranie) :smiley:

**Comment by krystian3w** [comment]
uBO i AdGuard nie widzi problemu w duplikatach, ABP jest porzucone w tym projekcie.

Niby tylko dla KADHosts warto rozstrzygnąć z którego pliku "szablonu" usunąć.

Niby to są wpisy CERT, może bot znowu nie sprawdza całego pliku "kad.txt" - co sugeruje, że to nie są np. "sklepy" jak te z `LWS`.

**Comment by hawkeye116477** [comment]
`Niby to są wpisy CERT, może bot znowu nie sprawdza całego pliku "kad.txt" - co sugeruje, że to nie są np. "sklepy" jak te z LWS`

Okazuje się, że LWS i CERT dodali tą samą domenę.
