### ISSUE TITLE
www.macheaper.top

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1499]
### Link bezpośredni 
`http://www.macheaper.top/`
### Dodatkowe informacje mogące mieć znaczenie
Scamowa strona, dużo stron powiązanych w domenie .top
Zarejestrowana w Chinach, napisana łamaną polszczyzną. 

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
#1479
