### ISSUE TITLE
Wyłudzenie danych logowania Allegro

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1513]
### Link bezpośredni 
`https://allegro-credit.info/`
### Dodatkowe informacje mogące mieć znaczenie
Strona chce dane logowania do Allegro

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
```
  {
    "RegisterPositionId": 4525,
    "DomainAddress": "www.allegro-credit.info",
    "InsertDate": "2020-09-30T10:01:24",
    "DeleteDate": null
  },
  {
    "RegisterPositionId": 4524,
    "DomainAddress": "allegro-credit.info",
    "InsertDate": "2020-09-30T08:47:35",
    "DeleteDate": null
  },
```

Jak @PolishJarvis  nie dodasz, to możemy rozpatrzyć reklamację.

**Comment by krystian3w** [comment]
https://www.virustotal.com/gui/file-analysis/MTlhZDRkMjBlZjc3NGVkYzdlOTMxOGE5NDI1OGRkYmU6MTYwMTQ2NzMxNA==/detection

**Comment by xMaap** [comment]
@krystian3w 102.130.124.5

**Comment by krystian3w** [comment]
A używają w mailu/sms-ie, brzydkiej reklamie FB?

**Comment by krystian3w** [comment]
@hawkeye116477 `KAD_Hole` umie banować IP, może wymaga ulepszenia lista na malinki "🍓"?

**Comment by xMaap** [comment]
@krystian3w mailing. Wysyłają allegro-credit.info i również samo IP który nie jest blokowane przez ublocka i wchodzi strona.

**Comment by hawkeye116477** [comment]
> KAD_Hole umie banować IP, może wymaga ulepszenia lista na malinki

Czy aby na pewno?

Nie sprawdzałem tej teorii, ale znalazłem na ich forum:

> DNS only resolves names to IP addresses. The Pi-hole doesn’t block IP addresses, for that you need a firewall on the router.

**Comment by krystian3w** [comment]
🇿🇦 ma chyba luźne podejście do tego czy IP tłumaczyć na domenę.
