### ISSUE TITLE
nadziejjaniegasnie.seohost.com.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1518]
### Link bezpośredni 
`http://nadziejjaniegasnie.seohost.com.pl/strona-artykul/`
### Dodatkowe informacje mogące mieć znaczenie
Phishing. Wyłudzenie danych logowania do FB.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Będzie po automatycznej aktualizacji, chyba że @PolishJarvis uznasz że strona padła i pominiesz `WHOIS`.

```json
[
  {
    "RegisterPositionId": 4601,
    "DomainAddress": "www.nadziejjaniegasnie.seohost.com.pl",
    "InsertDate": "2020-10-05T15:43:58",
    "DeleteDate": null
  },
  {
    "RegisterPositionId": 4600,
    "DomainAddress": "nadziejjaniegasnie.seohost.com.pl",
    "InsertDate": "2020-10-05T15:43:54",
    "DeleteDate": null
  }
]
```
