### ISSUE TITLE
Adidas & KFC Phishing Scam

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1520]
### Link bezpośredni 

`http://owo-owo.vip/ad/`
KFC phishing scam variant: `https://kfc-vip.vip/kfc/`

### Dodatkowe informacje mogące mieć znaczenie

Also, `https://super-1.vip/j/te5?c=ad` is redirected to the same fake adidas page.

References: 
Cofacts
`https://www.facebook.com/cofacts.tw/posts/689165235030857`
`https://www.facebook.com/cofacts.tw/posts/695301344417246`

Taiwan FactCheck Center
`https://tfc-taiwan.org.tw/articles/4531`

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Nie po polsku.
