### ISSUE TITLE
Lista domen cert - może nie widzieliście 

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1528]
Cert rozszerzył pliki z listami 

![obraz](https://user-images.githubusercontent.com/11302675/95308570-5fc22480-088a-11eb-9db4-8f18acf9a46e.png)

**Comment by hawkeye116477** [comment]
I co w związku z tym?

**Comment by MajkiIT** [comment]
Nic może Wam się coś przyda. A dodatkowo za takie wpisy nie krzyczeliście na mnie ?

http://hole.cert.pl/domains/domains_adblock.txt

**Comment by hawkeye116477** [comment]
> Nic może Wam się coś przyda. 

Dzięki, ale chyba raczej nie.

> A dodatkowo za takie wpisy nie krzyczeliście na mnie

Tak, krzyczeliśmy, bo one psują działanie strony w przypadku ABP, AdGuarda i spółki. Ktoś pamiętam nawet zgłaszał, że w AG ma problem, bo mu psuje strony. Na końcu musi być `$all`, by było poprawnie. Dodatkowo widzę sporo duplikatów pododawali.

**Comment by krystian3w** [comment]
AG nie ma zamiaru wyrównać filtrów:

`||*^`

z tym jak działają w uBO / iOS / Content Blocker.

**Comment by krystian3w** [comment]
Dodatkowo nic nie wnoszą jak przekręt ładuje CSS tagiem:  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style

> ```html
> <style>
> 
> </style>
> ```

A grafiki z pomocą Base64: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs
