### ISSUE TITLE
Ostrzeżenia forexrev i KNF

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1536]
https://forexrev.pl/ostrzezenia-16-10-binvesting-markets-cfd/

**Comment by xMaap** [comment]
Jest jeszcze glob-markets.net tylko na stronie jest błąd 404
https://forexrev.pl/knf-ostrzega-przed-global-markets/

**Comment by krystian3w** [comment]
Pewnie domena tylko do e-mailowania.

**Comment by xMaap** [comment]
`solidinvest.co`
https://forexrev.pl/ostrzezenia-22-10-solid-invest-bitrend-pibexa/
