### ISSUE TITLE
https://cda-tv.online/

### ISSUE THREAD

**Issue by mino815** [PolishFiltersTeam/KAD#1547]
Witam,
Strona https://cda-tv.online/ wydaje się już nie być fałszywą, bo z tego co przetestowałem to można normalnie oglądać filmy lub seriale.

![2020-10-30_10h04_07](https://user-images.githubusercontent.com/47322804/97692301-847b7780-1a97-11eb-93b6-3978062dadd0.png)

**Comment by krystian3w** [comment]
Tam raczej chodziło o problem z reklamami - wyślizgiwały się spoza regexów.
