### ISSUE TITLE
tipanddonation.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1550]
### Dodatkowe informacje mogące mieć znaczenie
1. https://antyweb.pl/uwazajcie-na-tip-and-donation-setki-oszukanych-moze-nie-zobaczyc-swoich-pieniedzy/

2. https://www.facebook.com/groups/891974464633651

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Duplicate of #1549
