### ISSUE TITLE
Facebook zablokowany po ostatniej aktualizacji 

### ISSUE THREAD

**Issue by sher04lock** [PolishFiltersTeam/KAD#1562]
Cześć,
Po ostatniej aktualizacji listy Facebook przestał działać. Nie mogę wejść zarówno z URL facebook.com jak i przez pierwszy wynik z google'a. Alert kieruje mnie do tego filtru:
`+  ||facebook.com^$all`
https://github.com/PolishFiltersTeam/KAD/commit/629027827844511c928b5886788e3347ffb5a0e4#diff-50722a3325584da687dc35a97b54ebb75db04e85da0e2531ab48492752fbec64R539

Czy coś jest nie tak z moją przeglądarką/systemem i powinienem zrobić solidny skan, czy jest to może jakaś literówka w filtrze i zamiast blokować szkodliwą stronę blokuje faktycznego facebooka?

![image](https://user-images.githubusercontent.com/17743466/98472271-4c400b80-21f2-11eb-857b-53fc7c8c74e7.png)

**Comment by FadeMind** [comment]
![20201108-1604858044-001](https://user-images.githubusercontent.com/9846948/98472513-d472e080-21f3-11eb-8d9f-5cad7da4e084.png)

xD

**Comment by FadeMind** [comment]
@sher04lock uwalili domenę facebook dot com na amen.

**Comment by xMaap** [comment]
Pewnie bot coś namieszał.

**Comment by krystian3w** [comment]
Nie bot, niby na liście jest jakiś sklep facebookowy.

**Comment by krystian3w** [comment]
W AdGuard pewnie od 24 pewnie ponownie ruszy.
