### ISSUE TITLE
olx.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1567]
### Dodatkowe informacje mogące mieć znaczenie
Jak to się stało, że główna strona olx znalazła się na liście?

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by gwarser** [comment]
https://github.com/PolishFiltersTeam/KAD/commit/43980361b4358e4ed7dbb795f1186195c9f6a36f#diff-50722a3325584da687dc35a97b54ebb75db04e85da0e2531ab48492752fbec64R4613

**Comment by hawkeye116477** [comment]
To ekipa CERT dodała, a bot zassał.

https://github.com/PolishFiltersTeam/KAD/commit/ee5b6a0c4670d421019cc6f0ef9debab29a4f3f0

**Comment by hawkeye116477** [comment]
Wygląda na to, że w skrypcie przetwarzającym listę CERT był mały błąd, otóż ucinał na początku `www`, jeżeli po `www` był dowolny znak, a powinien tylko z kropką, po prostu zapomniałem dodać znak ucieczki.

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KAD/issues/1568
