### ISSUE TITLE
olx.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1568]
### Dodatkowe informacje mogące mieć znaczenie
Zablokowaliście wszystko adresy z oxl.pl w nazwie. Nawet te legalne olx :(

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Duplicate of #1567

**Comment by krystian3w** [comment]
Wystarczy wymusić aktualizacje listy, wpis jest usunięty, skrypt naprawiony i nie doda nic w stylu:

`www-domena.pl` jako `||domena.pl^$all`
