### ISSUE TITLE
Phishing na "dagrasso.pl"

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1574]
`przeplyw-danych.eu/w.php`
`najlepszy-wynik.eu/w.php`
`wybor-podpunktu.eu` ?

Phishing na "dagrasso.pl".

**Comment by hawkeye116477** [comment]
Jakieś szczegóły, kiedy i gdzie to dokładnie się pojawia? Bo ja tam widzę tylko pizze...

**Comment by krystian3w** [comment]
Bo źle czytasz, oni udają pizzerię.

**Comment by krystian3w** [comment]
@xMaap  jak leci tej 3 domenie, bo `wybor-podpunktu.eu` wygląda na opróźniony na serwerze lub nie używa `/w.php`.

**Comment by xMaap** [comment]
Teraz wszystkie popadały.

**Comment by krystian3w** [comment]
Skrypt oceni kiedy WHOIS wygasa.
