### ISSUE TITLE
mirroir-grossissant.fr

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/KAD#1577]
`hxxps://mirroir-grossissant.fr/wp-includes/www.podatki.gov.pl/c2554/`

Więcej na : https://www.bankier.pl/wiadomosc/Ministerstwo-Finansow-ostrzega-oszusci-wyludzaja-dane-na-zwrotu-podatku-8004533.html

**Comment by krystian3w** [comment]
Już "offline", na przyszłość można kombinować z wildcard/regex.

Co do strony to trzeba by sprawdzić czy jej WP 4.9.16 to wersja z hotfixem jak nie to raczej powinna dołączyć do reliktów niezaktualizowanych WordPressów.
