### ISSUE TITLE
dopek.info

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/KAD#1578]
https://dopek.info/scam-lista-nieuczciwe-sklepy-f30.html

**Comment by hawkeye116477** [comment]
Lista utworzona 3 lata temu, może już nieaktualna. Poza tym, wymagana rejestracja, by zobaczyć w ogóle.

**Comment by krystian3w** [comment]
Albo bawić się z jakimś proxy, blokują chyba po IP.

**Comment by blocker999** [comment]
OK lista utworza 3 lata temu ale ostatni post 1 dzień temu ( w sumie 25 stron ) Może warto się zarejestrować choć by na przyszłość.

**Comment by krystian3w** [comment]
Dużo padło, obecnie jak ktoś w wątku pyta czy sklep legalny to musi prawie całą nazwę wykropkować:

`s****t***.org`
