### ISSUE TITLE
steamcammunlly.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1595]
### Link bezpośredni 
`https://steamcammunlly.com/OperationBrokenFan`
### Dodatkowe informacje mogące mieć znaczenie
Fałszywa strona steam wyłudzające dane do logowania

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Literówka lub offline.

`The requested domain was not found in the Registry or Registrar's RDAP server.`

`steamcammunlly.com is available 1 year $ 9.88`

**Comment by hawkeye116477** [comment]
Zapewne `steamcammunity.com`.
