### ISSUE TITLE
glosowanie-lubelskie.vot.pl

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1597]
glosowanie-lubelskie.vot.pl badziewie z FB

**Comment by MajkiIT** [comment]
Jak coś to wysłałem też do certu i już dodali.

**Comment by hawkeye116477** [comment]
W takim razie nie trzeba było pisać do nas, bot i tak pobiera od nich.

**Comment by MajkiIT** [comment]
Nie wiedziałem, że dodadzą. Czasami nie chcą.

**Comment by krystian3w** [comment]
Może nie pobrać jak wykryje błąd `NX-DOMAIN` (np. strona śledzi w jakich interwałach bot dodaje i na 10 minut przed i po uszkadzają działanie serwera około 4 razy na dzień).

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KAD/commit/dab7bda280a655bf7172a8ca2990c33957db0c85#diff-50722a3325584da687dc35a97b54ebb75db04e85da0e2531ab48492752fbec64R3639
