### ISSUE TITLE
desin.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1611]
### Dodatkowe informacje mogące mieć znaczenie
* Brak SSL
* Bardzo duże obniżki
* Metoda płatności tylko i wyłącznie karta Visa/MasterCard. 
* Po wypełnieniu losowymi polami przekierowuje na stronę httpx://www.liheas.com/cardpay/prepare.php, która z kolei ma mniej niż 30 dni.

https://who.is/whois/desin.pl
Zarejestrowana: 2020.07.15 10:04:44
Ostatnio zmodyfikowana: 2020.07.15 10:04:49
Wygasa: 2021.07.15 10:04:44

https://who.is/whois/liheas.com
Zarejestrowana: 2020-12-10
Ostatnio zmodyfikowana: 2020-12-11
Wygasa: 2021-12-10

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
#1613
