### ISSUE TITLE
rbtwf.net

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1614]
Domena która wyświetla się na obrazkach promocji/wyprzedaży okularów Rayban po tym jak ktoś kliknie w dziwny link.

![image](https://user-images.githubusercontent.com/11302675/102716218-b44a3d00-42da-11eb-9341-dc199672c747.png)

**Comment by krystian3w** [comment]
Brak polonizacji

**Comment by krystian3w** [comment]
Na razie zostawiam, może do 5 dni zrobią tłumacza Google na stronie...

**Comment by krystian3w** [comment]
#1241
