### ISSUE TITLE
Najnowsze filtry 29.12.2020 ~16:09 wywalają każdą stronę

### ISSUE THREAD

**Issue by qarmin** [PolishFiltersTeam/KAD#1619]
Po wyłączeniu wszystko działa tak jak powinno

Tutaj chyba może być problem - https://github.com/PolishFiltersTeam/KAD/blob/7bc27800806c56be26ff1d541bae473dcaddf793/sections/podejrzane_inne_oszustwa.txt#L1937

![Zrzut ekranu z 2020-12-29 16-43-41](https://user-images.githubusercontent.com/41945903/103295886-37fbdc00-49f5-11eb-8b08-418f202dbfea.png)

**Comment by hawkeye116477** [comment]
https://github.com/PolishFiltersTeam/KAD/commit/7bc27800806c56be26ff1d541bae473dcaddf793#diff-5c51b251c292f5c5855613f3392f09f1f52a958a53930a32dfa6e3d0529c8151

Czyli skrypt nawalił, zaraz sprawdzimy o co biega.

**Comment by krystian3w** [comment]
Może nie tyle pusty co może przywracają nieklikane linki i im nie wyszło.
