### ISSUE TITLE
fotkizneta.vot.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1623]
### Dodatkowe informacje mogące mieć znaczenie
Oszustwo?

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
CERT Polska posprzątał. 🙂

**Comment by hawkeye116477** [comment]
Ktoś chyba nie zaktualizował listy.

https://github.com/PolishFiltersTeam/KAD/commit/ebb50c2f0bc9909f0a623088b9b65c713691e219
