### ISSUE TITLE
e-kino.tv

### ISSUE THREAD

**Issue by FadeMind** [PolishFiltersTeam/KAD#1625]
Fake adres przekierowuje do stron blokowanych przez ESET.

`http://e-kino.tv >`
`http://alfik-fik.com/zcvisitor/2af4a322-5030-11eb-b273-124c3cb10e07/72092e88-2c53-401c-b988-51ef43ce1034?campaignid=2b1ceba0-5030-11eb-b273-124c3cb10e07 >`
`http://iyfnzgb.com/?pid=9PO1H9V71&dn=e-kino.tv`

**Comment by krystian3w** [comment]
U mnie inny schemat: na końcu ładują: `​http://kzayak.com/` / `https://ww38.kzayak.com/`

`iyfnzgb.com` banuje EasyList, bo to otwiera różne śmieci/malware.
