### ISSUE TITLE
kamilassurma.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1629]
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/54784135/wykop-dlaczego-na-waszej-stronie-sa-takie-reklamy-/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Wygląda, że blog oczyszczono i z wersji 5.3.X zaktualizowano do 5.5 (nawet jest 5.6 jak ktoś nie ma konfliktu szablonu/wtyczek).
