### ISSUE TITLE
pekaao.cam

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1630]
`https://pekaao.cam/?ca=cascmasjcjajq&fbclid=IwAR28apObbHiB5ZGTZqIZ_QRFvwRI65OCWRxQroictPV1eDDnr-tZ4cuAuZc`

**Comment by krystian3w** [comment]
ID chyba jednorazowe:

`/?ca=cascmasjcjajq&fbclid=IwAR28apObbHiB5ZGTZqIZ_QRFvwRI65OCWRxQroictPV1eDDnr-tZ4cuAuZc`

bo widzę:

![obraz](https://user-images.githubusercontent.com/35370833/104108977-92384f00-52c9-11eb-85b6-07389fe3e492.png)

**Comment by MajkiIT** [comment]
Chyba zablokowali domenę na serwerze. Dzięki
