### ISSUE TITLE
ultimate-opportunities.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1638]

**Comment by ClusterByte-x** [comment]
CERT:
> "RegisterPositionId": 7971,
> "DomainAddress": "ultimate-opportunities.com",
> "InsertDate": "2021-01-13T10:37:42",
> "DeleteDate": null

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KAD/commit/c0bd6d4df0f07bfb854bd836537a879314de1401
https://github.com/PolishFiltersTeam/KAD/commit/5861d923bf4ead5507fcfaa8c9e3e02c8f384815 - 👍🏻
