### ISSUE TITLE
wschodniepapierosy.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1651]
### Link bezpośredni 
`https://www.wykop.pl/wpis/55040693/kojarzy-ktos-stronke-wschodniepapierosy-pl-legit-j/`
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/55040693/kojarzy-ktos-stronke-wschodniepapierosy-pl-legit-j/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
Strona nie weryfikuje wpisanych danych. Metody płatności to tylko przelew bankowy. 
[Dane rachunku bankowego](https://jakitobank.pl/konto/PL29105015201000009736029209/1#Comments)

**Comment by krystian3w** [comment]
Niby kontynuacja: https://github.com/PolishFiltersTeam/KAD/blob/9ca69567306c30c936b9398e803e9b66ed8391c0/sections/podejrzane_inne_oszustwa.txt#L1166
