### ISSUE TITLE
prawdopodobnie fałszywy sklep

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1670]
### Link bezpośredni 
`https://dyskonto.store`
### Dodatkowe informacje mogące mieć znaczenie
najprawdopodobniej fałszywy sklep. brak telefonu, adresu, nazwiska, nazwy firmy itd.
opłaty tylko z góry.
produkty pod zmienionymi nazwami z wielokrotnie niższymi cenami niż prawdziwe.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Banned: #1241
