### ISSUE TITLE
olx.pl-???

### ISSUE THREAD

**Issue by AroKol78** [PolishFiltersTeam/KAD#1679]
`https://olx.pl-pay.work` 
źródło `https://phishtank.com/phish_detail.php?phish_id=6969673`

`https://olx.pl-get.work` 
źródło `https://phishtank.com/phish_detail.php?phish_id=6969703`

`https://olx.pl-konto.ltd/pay/?order_id=1613400306`
źródło  `https://phishtank.com/phish_detail.php?phish_id=6969707`

**Comment by krystian3w** [comment]
Już coś jest:

https://github.com/PolishFiltersTeam/KAD/blob/b14d7572ee9d1c4c46c6286d80ce92a9383c3bbd/sections/przekrety.txt#L2872 https://github.com/PolishFiltersTeam/KAD/blob/c07d84a64d5cbd687296cf56bf66854896e100dc/KAD.txt#L5156

Może za dużo kropek jak nie masz planszy ostrzegawczej.

**Comment by AroKol78** [comment]
> Może za dużo kropek

👍 (ubo legacy)
