### ISSUE TITLE
dziewczyn.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1680]
### Dodatkowe informacje mogące mieć znaczenie
Strona do przeanalizowania - możliwe oszustwo.

https://www.wykop.pl/wpis/55607003/kilka-dni-temu-odkrylem-ze-jakis-sklep-internetowy/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
#1241
