### ISSUE TITLE
neos.com.pl 

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1686]
https://forum.bitcoin.pl/viewtopic.php?f=129&t=33832

**Comment by krystian3w** [comment]
Firma uznała, że to trolle biconiowe są. Nie wiem czy po prostu olewać maile?

**Comment by hawkeye116477** [comment]
Nie wiem co sobie myśleć o tym wszystkim ,ale jak dla mnie to wygląda trochę jak sprawa do jakiejś listy fake-newsowej...

`http://neos.biuroprasowe.pl/133923/uwazaja-rzad-za-grupe-przestepcza-covid19-za-metode-kontroli-a-sami-buduja-nowy-system`

**Comment by krystian3w** [comment]
Czyli ignorować maile i pisać im, że DNS mogą sobie ludzie zmienić a listę ręcznie wyłączyć?

**Comment by hawkeye116477** [comment]
Poczytaj, poddaj analizie.
