### ISSUE TITLE
Okresowe weryfikowanie błędów 404/403? Ciągła lista domen z wygasłym whois?

### ISSUE THREAD

**Issue by AroKol78** [PolishFiltersTeam/KAD#1688]
sprawdziłem wyrkowo jeden adres `CERT_whitelist.txt` > `zacznij-prace.co.pl`
i trafiłem na to
`http://zacznij-prace.co.pl/mobile`
100% `https://phishtank.com/phish_detail.php?phish_id=6667841`

(`whitelist` - ktoś weryfikuje , czy w ogóle są potrzebne?)

---
~można dodać~

`https://olxsafepay.pl/payment`
info `https://phishtank.com/phish_detail.php?phish_id=6994934`

`https://olxsafepay.pl/track?id=514757241`
info `https://phishtank.com/phish_detail.php?phish_id=6994933`

już dodali do `hole.cert.pl` to i pewnie "kad" doda

**Comment by hawkeye116477** [comment]
` trafiłem na to`

Jak to, jak strona nie działa?

**Comment by AroKol78** [comment]
"strona nie działa" a jest na `CERT_whitelist.txt` , `phishtank`

**Comment by xMaap** [comment]
Przecież strona padła.

**Comment by AroKol78** [comment]
tak
 > sprawdziłem wyrkowo jeden adres

a był `phishtank` `hole.cert.pl`

a dali go do "whitelist" , **zamiast skasować**

`whitelist` - ktoś weryfikuje , czy w ogóle są potrzebne? podejrzane te "whitelist" :(

**Comment by hawkeye116477** [comment]
Cóż, jak nie działa, to jest dodawane do wykluczeń. Ktoś w końcu musi robić porządki, skoro Cert rzadko to robi.
Jednakże w tym przypadku wydaje się, że wyjątek nie jest już konieczny, gdyż bot sam wykrywa czy strona jest aktywna, ale wtedy strona działała i był napis „403", więc dlatego została dodana => https://github.com/PolishFiltersTeam/KAD/commit/8c3ce1222041f46003edce96ad86f6d764039320.

**Comment by AroKol78** [comment]
nie chciałbym być z powodu jakiś "białych list" ja i inni użytkownicy stracili  mamone
(oczywiście obowiązują zasady ograniczonego zaufania / zdrowego rozsądku)

jak często jest sprawdzana zawartość "whitelist"  , czy strony ponownie nie stanową zagrożenia ?

**Comment by krystian3w** [comment]
W sumie to i można zrobić mega listę czy strony z utraconą rejestracją "Who IS" nie wróciły.

**Comment by hawkeye116477** [comment]
> strony z utraconą rejestracją "Who IS" nie wróciły.
> Ciągła lista domen z wygasłym whois

Jeżeli CERT nie usunął domeny, to bot sprawdza za każdym razem w whois. 
Jak ich hosting zdjął, to raczej chyba tak szybko nie wrócą. 
Mam pomysła, może zrobimy skrypt sprawdzający te domeny z whitelisty, który zobaczy czy będzie tam dany komunikat lub czy w ogóle strona jest aktywna :smile:.

**Comment by krystian3w** [comment]
CERT ma tylko 32 usuniętych domen i 25 subdomen "`www.`" np. po 5 minutach (niby błąd tych dwóch pracowników pewnie sprawdzających jednoczenie a nie po sobie) lub kilku tygodniach [jak któryś uznawał brak whois lub realny error 403 za powód (a nie status 202 i fejkowa plansza w "html5" wskazująca na error 403/404)]:

```
sub2.blocked-site-hole-cert.pl
sub1.blocked-site-hole-cert.pl
tarnow7.vercel.app
wwwareshop.pl
doninishop.com
olx24.eu
gelber.pl
firebasestorage.googleapis.com
ados.com.my
kurierfedex.pl
bnpparibas.kantarpolska.com
klient.bnpparibas.kantarpolska.com
ms-mbank.onfly.pl
df9e8783c33d.ngrok.io
nagrania-covid-19.ct8.pl
jhamarielvin.ct8.pl
prywatne-fotki.5v.pl
podgladacze.5v.pl
skryte-zdjecia.ct8.pl
galeria-nagosci.ct8.pl
terminator3000.ct8.pl
janskowron.ct8.pl
krepujace-zdjeciaa.5v.pl
tkozlowski.ct8.pl
wiadomosci-lokalne.5v.pl
adamdj.ct8.pl
wiad-info.5v.pl
pllubiok.5v.pl
centrumrozrywki.5v.pl
direct3.greenfitness.net
gabriela.ct8.pl
windykacjajagoda.org
```

czyli zerowe pokrycie na dzisiaj z naszym plikiem wykluczającym strony z błędami 404 (darmowe hostingi) / 403 (np. nazwa / home).


Lista LWS raczej wymagała by dodania szukania tekstu "sklep nieaktywny" / "zablokowany" czyli jakiś `set` / `grep` w skrypcie python?

**Comment by krystian3w** [comment]
Co do sprawdzenia to prawdziwego offline nie wykryłem z pomocą ping/tracert w powershell - musiałbym w Chrome pootwierać każdy wynik i czekać na rezultat `nxdomain`.

**Comment by hawkeye116477** [comment]
Odnośnie https://github.com/PolishFiltersTeam/KAD/commit/93837022ed90f6d3903e05cdc44bc714cb364000, to jednak w whois jeszcze są aktywne. Miałem raczej na myśli by porównać białą listę z listą Cert.

**Comment by krystian3w** [comment]
No to pisałem = 0 duplikatów między ich usuniętym a naszymi dezaktywowanymi za errory 403 (bany) / 404 (bany na 5v.pl i innych darmowych hostingach).

Jeszcze muszę sprawdzić czy udało mi się wyłączyć OpenDNS i łap @AroKol78:

`https://phish.opendns.com/main?url=https://pomoc.o2.pl/polityka-prywatnosci&server=fra2&prefs=&tagging=&nref#`

może wywalą błędne tagowanie bez zakładania konta kiedyś.

**Comment by hawkeye116477** [comment]
https://www.hybrid-analysis.com/sample/6c825fa3eb955d5db994e74eef79e9e6985b5dad6b119dbc9a0dc1212536f6c5/603fae009af54a4f597c3136

**Comment by krystian3w** [comment]
Czyli to są słupy:

```
FedEx Express Poland Sp. z o.o
Annopol 19
03-236 Warszawa, PL
+48.178602186
Typ abonenta: organizacja
Ostatnia modyfikacja: 2020.06.24 14:36:24
```

```
Dinfo.pl Sylwia Wierońska
ul. Nadbrzeżna 2
43-300 Bielsko-Biała
Polska/Poland
+48.695404404
biuro@dinfo.pl
```

lub luki w CMS?

**Comment by AroKol78** [comment]
`https://phish.opendns.com/main?url=https://pomoc.o2.pl/polityka-prywatnosci&server=fra2&prefs=&tagging=&nref#`
`https://phish.opendns.com/`

mi wyświetla "Server not found" i jakiś dziwny adres

---
> `https://phishtank.com/phish_detail.php?phish_id=6891502`
Submission #6891502 `https://pomoc.o2.pl/polityka-prywatnosci`

podają w info 
WHOIS database responses: `https://dns.pl/en/whois`

**Comment by hawkeye116477** [comment]
https://www.tnt.com/dam/tnt_express_media/tnt-local-pages/pl_pl/docs/N20/onepager-less_pl.pdf

Cóż, no niby adres się zgadza...

**Comment by krystian3w** [comment]
Czyli pisać na mail `polska@fedex.com` czy to ich strona czy ta Wera się podszywa?

**Comment by hawkeye116477** [comment]
Możesz napisać. 

Jak dla mnie to trochę podejrzane, że nie widać nigdzie żadnego linku do tej strony.

**Comment by hawkeye116477** [comment]
Nie wiem co z `ebonplus.com`, bo strona niby działa, ale nie jest po polsku...

Znalazłem https://www.wykop.pl/wpis/50354441/ciekway-rodzaj-scamu-wpadl-mi-do-skrzynki-jacys-je/.

W takim wypadku raczej skryptem tego nie da rady sprawdzić.

**Comment by AroKol78** [comment]
`https://ebonplus.com/nes/` - niby 403 - `https://phishtank.com/phish_detail.php?phish_id=6656489`

**Comment by hawkeye116477** [comment]
@krystian3w Potestuj https://github.com/PolishFiltersTeam/KAD/blob/b59d2fb9ae9c702a087b7b010b7da822d02d88d4/scripts/Offline.py. W niektórych dziwnie zrobili, więc nie wiem czy da się jakoś inaczej.

**Comment by krystian3w** [comment]
Ale oni już chyba z 3 infekcję złapali i fałszują numer instalacji WordPress na 9XXX a tak wysokiej nie wydano.

**Comment by krystian3w** [comment]
Jak na dzisiaj to żaden nie wrócił, dla części jest już error "nx domain" jakich chyba bot od CERT uzna za offline do kolejnego sprawdzania w ramach 3 prób na dzień.
