### ISSUE TITLE
moto-agro.pl

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/KAD#1691]

**Comment by AroKol78** [comment]
już jest w "kad"
(
nie wchodziłem na stronę `moto-agro.pl` ale chyba offline według `phishtank`
`http://moto-agro.pl/dop`
`https://phishtank.com/phish_detail.php?phish_id=4633890`
)

**Comment by krystian3w** [comment]
W sumie nie wiem czy blocker może uznał sklep za bezpieczny.

Co do stanu offline, to po prostu sklep oczyścił CMS z przekrętu wyłudzającego dane logowania.

**Comment by krystian3w** [comment]
Niby to efekt próbowania użycia: https://github.com/PolishFiltersTeam/KAD/commit/50632e220248541552d9e6c685350225c8b1c33b projektu `mitchellkrogza ~ hacked domains`: https://github.com/PolishFiltersTeam/KAD/issues/1346

**Comment by AroKol78** [comment]
`||admwarszawa.pl^$all` w "kad"
offline `http://admwarszawa.pl/mmp/` według `https://phishtank.com/phish_detail.php?phish_id=5148835`

może być więcej stron offline
