### ISSUE TITLE
pl.whokeys.com

### ISSUE THREAD

**Issue by seba2282** [PolishFiltersTeam/KAD#1693]
pl.whokeys.com podejrzenie o przekręty.

Np. zbyt niskie ceny kluczy na produkty Microsoft, co samo w sobie jest podejrzane. Prośba o zweryfikowanie strony.

**Comment by hawkeye116477** [comment]
https://www.reddit.com/r/Steam/comments/2yhnsw/key_resellers_and_what_they_mean_for_you/

**Comment by seba2282** [comment]
Czyli nie ma na liście bezpiecznych stron tej strony "whokeys", @hawkeye116477 .

**Comment by hawkeye116477** [comment]
A MS na to:
> With the exception of Product Key Cards (PKC’s) distributed with COA’s, Microsoft does not distribute products keys as standalone products. If you see a listing on an auction site, online classified ad, or other online page advertising product keys for sale, it’s a good indication that the keys are likely stolen or counterfeit. If you were to purchase and use a stolen or counterfeit product key to activate Windows installed on your PC, the key may not work for activation, may already be in use on another PC, or it might be blocked from use later by Microsoft when the key is reported stolen. The best way to get everything you expect up front is to buy genuine Microsoft software preinstalled on a new PC or genuine Microsoft software from an authorized reseller.

**Comment by seba2282** [comment]
@hawkeye116477  😅
