### ISSUE TITLE
dobregry.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1709]
### Link bezpośredni 
`https://dobregry.com/facebook-hacker-pro/`
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/56414003/patrzcie-na-reklame-czego-dzisiaj-natrafilem-w-jed/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
+`https://catsplit.pl/410476`
