### ISSUE TITLE
somi.tiktokclaim.eu

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1712]
### Link bezpośredni 
`https://somi.tiktokclaim.eu/pl/`
### Dodatkowe informacje mogące mieć znaczenie
Oszustwo?

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Chyba ten jest prawdziwy: https://somi.nl/en/tiktok-claim

 a tamta domena może kraść dane jak jej SOMI nie kojarzy.
