### ISSUE TITLE
Lista domen spoza listy certu. 

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1714]
[ Phishing/Bramka ]

potwierdzenie-nadania[.]fun
sendpost24[.]xyz
pl[.]paysouts.com

[ Phishing/Olx ]
pay33-olx[.]pl
olx.pl-posta[.]casa
olx.pl.pay-information[.]com
olx-uzyskiwanie[.]pl
olx.pl-posts[.]club
olx.polska-dostawka[.]live
olx.pl-posts[.]icu
olx.pl-posts[.]cyou

[ Phishing/Facebook ]

kurierzmojegomiastaa[.]site

**Comment by MajkiIT** [comment]
@krystian3w znalazłem jeszcze coś takiego 
olx-pay-dk.online

**Comment by krystian3w** [comment]
U mnie już offline (3 różne usługi DNS i dwie bez opierania się o listy cert polska), pomyślę później czy należy się ban na około 12 miesięcy na podstawie długiego wykupu domeny (whois).

**Comment by MajkiIT** [comment]
@krystian3w dziękuję
