### ISSUE TITLE
f000.backblazeb2.com

### ISSUE THREAD

**Issue by Dullage** [PolishFiltersTeam/KAD#1721]
f000.backblazeb2.com is listed in **sections/przekrety.txt** but this is a domain used by the popular online storage platform Backblaze (https://www.backblaze.com/).

The reason I noticed this issue is that my backup to their b2 storage failed (as the DNS was blocked).

Please can this entry be removed/whitelisted.

**Comment by hawkeye116477** [comment]
Well, seems that was added by CERT.

https://github.com/PolishFiltersTeam/KAD/commit/ffb3947ddb9d2261c05b3788207ad79b1d7d6a18

Looks like that they removed it from their list now.
