### ISSUE TITLE
inpost.pl-safes.xyz

### ISSUE THREAD

**Issue by dolohow** [PolishFiltersTeam/KAD#1727]
![image](https://user-images.githubusercontent.com/1408564/113616593-96b89d80-9655-11eb-8afc-fe46d3be9b45.png)

Przekręt na olx, klasyka https://niebezpiecznik.pl/post/olx-scam-karta-platnicza/

**Comment by ClusterByte-x** [comment]
Lepiej będzie zgłaszać takie scamy bezpośrednio do CERT Polska, za pomocą [formularza](https://incydent.cert.pl/#!/lang=pl). Lista analizowana jest stale przez dwóch pracowników i aktualizowana co 5 minut. Do KAD lepiej zgłaszać strony, które napewno „nie wchodzą” w kompetencję CERTu, choćby fałszywe sklepy.

**Comment by krystian3w** [comment]
Dodatkowo od jakiegoś czasu dodałem:

`||inpost.pl-*.*^$document`
`||inpost.pl.*.*^$document`

wzorując na OLX.

**Comment by krystian3w** [comment]
@ClusterByte-x a nie lepiej pod phishing ten osobny:

https://incydent.cert.pl/phishing -> https://incydent.cert.pl/domena -> https://incydent.cert.pl/domena#!/lang=pl

Jakby tam pracowało więcej osób i tym dwóm nikt tego nie przekazał na `hole.cert.pl`

**Comment by krystian3w** [comment]
Uruchomili zgłaszanie SMS-ów jako opcja "przekaż dalej": `0048-799-448-084`
