### ISSUE TITLE
mandatoplac.net i mandaty24.net

### ISSUE THREAD

**Issue by szymonx20** [PolishFiltersTeam/KAD#1730]
### Dodatkowe informacje mogące mieć znaczenie

https://niebezpiecznik.pl/post/uwaga-sms-mandat-karny/?aktywneataki

przykładowy link: https://mandatoplac[.]net/7452

**Comment by ClusterByte-x** [comment]
https://github.com/PolishFiltersTeam/KAD/commit/b738a9f6351af03731d65cb7db1dcb8180ca97c3

**Comment by hawkeye116477** [comment]
`Host mandaty24.net not found: 3(NXDOMAIN)`

Strona padła, dlatego też bot nie dopisał.

**Comment by krystian3w** [comment]
Niby połowę domen blokuje ochrona MS wbudowana w Defender i stosowana w Edge jako zamiennik Google antimalware.

**Comment by ClusterByte-x** [comment]
Hmmm... ta ochrona z Defendera do przeglądarek działa bez żadnych dodatków czy tylko w Edge? Czy trzeba instalować nadal [rozszerzenie](https://chrome.google.com/webstore/detail/microsoft-defender-browse/bkbeeeffjjeopflfhgeknacdieedcoml)?
