### ISSUE TITLE
vider.info

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/KAD#1739]
### Dodatkowe informacje mogące mieć znaczenie
```
||vider.info^$document,domain=~uwaga-natretne-reklamy|vider.info
```

**Comment by krystian3w** [comment]
Czemu?

@hawkeye116477 woli blokować niż polegać na filtrach regex od Majkela.

**Comment by hawkeye116477** [comment]
https://cert.orange.pl/aktualnosci/zbuntowany-kalendarz

Wg. sandboxu Hybrid-Analysis Vider.info nie jest – łagodnie mówiąc – serwisem godnym zaufania. I
