### ISSUE TITLE
toddley.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1740]
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/56879913/uwaga-na-scam-sklep-toddley-pl-toddley-sklep-toddl/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
> 
> Nazwa domeny | toddley.pl
> -- | --
> Stan | Aktywna w DNS [REGISTERED]
> Utworzona | 2020.04.06 21:39:07
> Ostatnia modyfikacja | 2021.03.17 12:56:25
> Koniec okresu rozliczeniowego | 2024.04.06 21:39:07
> Nazwy serwerów | dns16.ovh.net ns16.ovh.net
> Abonent | Graph Concept - Zblewski AdrianBrzozowa 14A76-270 Wodnica, PL+48.517585507. Typ abonenta: organizacja. Ostatnia modyfikacja: 2020.04.06 21:38:04.
> Rejestrator | OVH SAS2 Rue Kellermann59100 RoubaixFrancja/France+48.717500200 https://www.ovh.pl/abuse/
> 
>
