### ISSUE TITLE
lfforms.linnbenton.edu

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1746]
### Link bezpośredni 
`https://lfforms.linnbenton.edu/`
### Dodatkowe informacje mogące mieć znaczenie
`https://lfforms.linnbenton.edu/`

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Niby offline, proszę wysyłać pełny link z parametrami.

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/115972378-3c24aa00-a54e-11eb-98ad-6fdadaf2cf9c.png)
