### ISSUE TITLE
pl.godeal24.com

### ISSUE THREAD

**Issue by seba2282** [PolishFiltersTeam/KAD#1748]
Produkty Microsoft za grosze. Definitywne oszustwo. 

Proszę o zweryfikowanie.

**Comment by hawkeye116477** [comment]
Strona utworzona rok temu, opinie ma różne. Wiadomo to keyshop, więc różnie bywa. W niektórych słyszałem, że bywają klucze pochodzące z zakupów kradzionymi kartami.

https://pl.trustpilot.com/review/godeal24.com

Z analizy whois:
```
Admin Name: Registration Private
Registrant Name: Registration Private
```

**Comment by seba2282** [comment]
Mi pachnie przekrętem, bo klucze autentycznie za tanio dla produktów MS.

**Comment by hawkeye116477** [comment]
To może za mało spostrzegawczy jestem, ale ja tam widzę jedynie gry.

**Comment by seba2282** [comment]
Wejdź w spring promo, to zobaczysz ceny produktów ms za kilka euro. Groszowe sprawy.

**Comment by hawkeye116477** [comment]
Cóż, na głównej tego nie ma albo ślepy jestem, ale znalazłem dopiero w Google. Nawet jak w ich wyszukiwarkę wpisuję, to nie zwraca tego, dziwne... Faktycznie, jest sporo taniej.

**Comment by seba2282** [comment]
Czyli przekręt i tyle w temacie. Nie bez powodu zgłosiłem. Weź sobie wpisz w google "Windows 10". Któryś artykuł jest kwietniowe promocje i z niego dostajesz się na tą stronę z promocjami. Dziwne, bo powinno być to widoczne i z głównej. A nie ma. Wnioski nasuwają się same.

**Comment by krystian3w** [comment]
Niby se dało się przekupić.

**Comment by seba2282** [comment]
Dziękuję za rozstrzygnięcie sprawy i dodanie tej witryny do przekrętów.
