### ISSUE TITLE
dashot.xyz

### ISSUE THREAD

**Issue by KcrPL** [PolishFiltersTeam/KAD#1755]
### Dodatkowe informacje mogące mieć znaczenie

PGE Płatność scam. Proszą o płatność 3,46zł.
Przekierowuje z adresu cli.co wysyłany przez SMS'y.

**Comment by KcrPL** [comment]
Dokładny adres przekierowujący to https://cli.co/platnosc-pge-tlj53o5

**Comment by krystian3w** [comment]
Cert dodał:

```
  {
    "RegisterPositionId": 14767,
    "DomainAddress": "www.dashot.xyz",
    "InsertDate": "2021-05-05T17:19:55",
    "DeleteDate": null
  },
  {
    "RegisterPositionId": 14766,
    "DomainAddress": "dashot.xyz",
    "InsertDate": "2021-05-05T17:19:51",
    "DeleteDate": null
  },
```

Zostaje ocenić czy skracz linków to też scam bez darmowego skracania linków lub sieć alifilacyjna.

**Comment by krystian3w** [comment]
@hawkeye116477 bot uznał przekręt za offline, podobnie jak użyję VPN.
