### ISSUE TITLE
www.investing-headlines.com

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1768]
`https://www.investing-headlines.com/PL-Orlen-Gas/?cep=z6y94VNew_zL-jq8sGYaZHW7Csq2AQg9SP-yHVzVNsPx1A7C6fYHgNNZdAT4L9UefIl5z1rRE_KuoGyno6E5_LTscfshHf6fq060jtqj1TdDCuesBzP13GqUSv4J6Cya-cpe6FBBAyRGqJyBM91ZYA-1YkkebNIdyDr_QMUYH55pBjsmlsFwHI-G_oPowotb_SKz79nF7FdPOtrFa9US6GKXP6UY_FywTaBKz8hatZBUMkUb_M4vB-8-21JkLMuFFvk-Lk3nKJSap3AHlIwxwrWbxrVEE6hmQqj_F4qEO2sBZfC6kjbCqypobgHDJxL6WNXh-x3J4ZCt5iFA39vFSDULugx11eU8XX-Ui7LBvWUxZZhR12LnbaIDtytbYeaUsRh3VVMWEIQqgNKmLEXtlJ5Qjf6L0o370My5S1ZKEkpT5WOjJIS9teFMOrSfV2sH&lptoken=16f5209c63ef26bb046d&key1=Ivana-PL-DESK&campaign_id=23847224620990764&adset_name=35%2BM-D&ad_name=ad1`

**Comment by krystian3w** [comment]
Cert dodał:

```json
  {
    "RegisterPositionId": 15071,
    "DomainAddress": "investing-headlines.com",
    "InsertDate": "2021-05-10T09:24:22",
    "DeleteDate": null
  },
  {
    "RegisterPositionId": 15070,
    "DomainAddress": "www.investing-headlines.com",
    "InsertDate": "2021-05-10T09:24:19",
    "DeleteDate": null
  },
```

Jak bot uznał za offline, to trzeba sprawdzić na DNS/VPN niewspółpracującym z CERT.pl
