### ISSUE TITLE
gadgetarchive.com

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1769]
`https://l.facebook.com/l.php?u=https%3A%2F%2Fgadgetarchive.com%2Fasdf%2F%3Fkey1%3DIvana-PL-DESK%26campaign_id%3D23847224620990764%26adset_name%3D35%252BM-D%26ad_name%3Dad1%26fbclid%3DIwAR252MkW8p1xiooUl2TxWf4XTPxiE8ovTnD5xx7DLpEJNU-bVOKAe6QyaQA&h=AT0cwpwbZGbTmL7ccZXydGEpG0qQyWSO-GADAQgV_r09tP7YTfqiWuiSjH1OpnWoOzBo43rEBZaQEAw2pr1efAAyle5M1zV05N1EiNEO_bY2SN9pccFqphrS-1PpyyyrC-TnHw&__tn__=%2CmH-R&c[0]=AT05W9lTXpRTGfEYIDDF4o5gTKF4NcSBCCy8ENEUzTLOmWQnQJdo8AewO_P_6QgstuXZf7zcPuiaiw1udhyMx0zYoPWKgQDOdmNrJ0g3hUSMQfK6lkif7bMsr0vtV_SaIhsoX3HySPS_FG_907XcCJFlWJvSqmAkeFay5wCQEFsmM4GK6RvkkGRFb_RxCndYA-CnKlXUbQOAtMHgRP-J41VF5iYUmT2Pcn3qDnUPRu2uEMLFSqhpIjR1xbndBDwVQlN6W6MS5gydz3YS_l9v4W7BnVHQBmXctalKhNeEogfH9tNn-UAk8vP2D49K1XmdY8u-yw`

\>\> `https://gadgetarchive.com/asdf/?key1=Ivana-PL-DESK&campaign_id=23847224620990764&adset_name=35%2BM-D&ad_name=ad1&fbclid=IwAR252MkW8p1xiooUl2TxWf4XTPxiE8ovTnD5xx7DLpEJNU-bVOKAe6QyaQA`

\>\> `https://www.investing-headlines.com/PL-Orlen-Gas?cep=BKB-Qd68HWg7HYM-4S-NoeXcvrx6wlISy4tRB1mx57XFay8Zwk9rCv6A0p5UwHiGleW8JUR7d-SDeMYkAwHiRrHlhbKgFOOvmzaLffPcFOkcwlXZ9qrpNAd7YwlbztEY1UfupkI1T1SsxbaDNqlPJo3NRxuINux8vVFzQlK-s38hNeGo__cmys81W6Yfb3eS8w6_kD0MLtZa6wq-mTyqfsb6OYRPQ_FWit7iq8Bn0zy2e7y3B2QZz2-I_-0CBvVUzq4-PvreKImBNntz9OaWayfZy5EK0SvMgn31mQQujoPTz50hVgqKCiwBa7iInylvF4vNy5Dpe-NbRRMuB3vFutmYlzvQvachcVasu3xtcmJJToMujvh02UXLopliZCEYUAcT42E_tAPzeRG8-nL8sadUIxFCLdDp5DmwjQhjZwi2KKEtNKIt7D6003LOZEEG&lptoken=16b2202f65ee33a7533e&key1=Ivana-PL-DESK&campaign_id=23847224620990764&adset_name=35%2BM-D&ad_name=ad1&fbclid=IwAR252MkW8p1xiooUl2TxWf4XTPxiE8ovTnD5xx7DLpEJNU-bVOKAe6QyaQA`

---

`https://gadgetarchive.com/2021/05/09/212/`

**Comment by krystian3w** [comment]
Pierwsze już u mnie offline z przekierowaniem do `investing-headlines.com`.

**Comment by MajkiIT** [comment]
ale to działa jeszcze http://gadgetarchive.com/
