### ISSUE TITLE
komputerswiat.pl

### ISSUE THREAD

**Issue by seba2282** [PolishFiltersTeam/KAD#1776]
Co mogę więcej powiedzieć? Naciąganie na premium.

**Comment by xMaap** [comment]
Jakie premium?

**Comment by seba2282** [comment]
Widzę, że teraz już jakiś filtr wywala (odblokowuje) contentpremium na komputerswiat.pl, gdzie jest blokada, że "zostało 99% artykułu i wykup subskrypcję".
Tak więc temat nieaktualny. Zamykam i dziękuję za zainteresowanie tematem.

**Comment by krystian3w** [comment]
Nie ma takiego filtru na ich paywall: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2812

**Comment by krystian3w** [comment]
Opcjonalnie masz na myśli kresy.pl: https://github.com/MajkiIT/polish-ads-filter/issues/19911 tam przywrócono link do darmowego czytania "dalej".

Przyciski "zasponsoruj mi kawę" raczej nie są reklamą jaką MajkiIT ukrywa, to robił mati aka `KonoromiHimaries`.

**Comment by seba2282** [comment]
Opcjonalnie mam na myśli np. to https://www.komputerswiat.pl/poradniki/programy/tak-szpieguje-windows-10-jak-sie-chronic/fgsd5sb

![naciaganie](https://user-images.githubusercontent.com/16944478/119461564-1dc5f000-bd40-11eb-9b81-0787e48cb527.png)

Ja bym w takim razie dał do KAD cały komputerswiat.pl za naciąganie.

**Comment by hawkeye116477** [comment]
Raczej nie ma takiej opcji, nie blokujemy stron z paywallem.

**Comment by seba2282** [comment]
Nie ma jakiegoś filtra na anty paywall? @hawkeye116477 @krystian3w
