### ISSUE TITLE
bitcoind scam

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1779]
### Link bezpośredni 
`https://polandinww1.space`
### Dodatkowe informacje mogące mieć znaczenie
```
https://polandinww1.space
https://polandinww2.space
https://polandinww3.space
https://polandinww4.space
https://polandinww5.space
https://polandinww6.space
https://polandinww7.space
https://polandinww8.space
https://polandinww9.space
https://polandinww10.space
```

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
Czyli dołożyli drugie `w`.

Nie wiem czy lepiej zamiast `w` zrobić regex na dowolne litery.

https://github.com/PolishFiltersTeam/KAD/blob/master/KAD.txt#L2015

**Comment by krystian3w** [comment]
Może warto przerobić linię:

https://github.com/PolishFiltersTeam/KAD/commit/17a223067b3f81729f738dcc40facd00cd12b946#diff-269381da98ff06dde11226ef06019e35651b7f1ddf78a517bb878a5dd5eaf038L11

Ja chyba coś chętniej uruchamiam regexy jak szybko obchodzą wildcard.

**Comment by krystian3w** [comment]
#1735 #1742 #1779 #1775
