### ISSUE TITLE
Oszustwo konieczności opłacania rachunków energ.

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1786]
### Link bezpośredni 
`https://cli.co/platnosc-pge-gfj43iq`
### Dodatkowe informacje mogące mieć znaczenie
Takiego smsa dziś otrzymałem, mimo że nie jestem odbiorcą żadnych usług energetycznych:
PGE: Na dzien 30.05 zaplanowano odlaczenie energii elektrycznej!
Prosimy o uregulowanie naleznosci 3.46 zl Zaplac teraz na:
`https://cli.co/platnosc-pge-gfj43iq`

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by xMaap** [comment]
Przekierowuje do 
`https://marselosq.site/pge/891241974/1274917/`
cli.co chyba nie nadaje się do zablokowania.

**Comment by krystian3w** [comment]
Cert niby zablokował.

Skracania linków lepiej nie tykać, niech sobie AdGuard blokuje takie.
