### ISSUE TITLE
zalukaj.vip

### ISSUE THREAD

**Issue by gzenio22** [PolishFiltersTeam/KAD#1790]
### Dodatkowe informacje mogące mieć znaczenie

Ta strona jest płatna ale nie jest to scam ani żaden przekręt proszę o rozważenie usunięcia tej witryny z blokowanych :)

**Comment by hawkeye116477** [comment]
#1074

**Comment by krystian3w** [comment]
Po rejestracji filmy lecą, nie trzeba opłacać abonamentu im w ciemno (kupno kota w worku).

Pewnie za kilka dni będzie cofka jak nagle zwali im się za dużo chętnych do oglądania.

**Comment by gzenio22** [comment]
Oni istnieją odkąd zalukaj dedło ale nie podszywają się od początku były komunikaty że oni to co innego ze to tylko nazwa szczerze już dawno korciło mnie zeby to zgłosic jako błąd ciągle zapominałem

**Comment by gzenio22** [comment]
@krystian3w mimo aktualizacji filtrów i wyczyszczeniu historii nadal mi blokuje tę strone Adguard

**Comment by krystian3w** [comment]
W AdGuard trzeba doliczyć 3 godziny na aktualizację w ich domenie:

https://filters.adtidy.org/windows/filters/232.txt?id=232

https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_232_KADPrzekrety

Jak dalej nie rusza, bo ta była już aktualizacja https://github.com/AdguardTeam/FiltersRegistry/commit/4a01c903756d9ec284d1cd390920b008717edad7#diff-09a511950597e264cf166df99b5f90381d1a3aed9020ee9cba1a5d12222d661eL9007-R9010 to pewnie trzeba poprawić reguły "Specjalne_AdGuard", bo apka blokuje nawet link otwierany z obcej domeny #1747
