### ISSUE TITLE
vider.info

### ISSUE THREAD

**Issue by gzenio22** [PolishFiltersTeam/KAD#1792]
Nie wiem czy do poprawnego repo to zgłaszam ale blokujecie stronę która działa jako natrętne reklamy :D reklamy usunąć strony całej blokować nie trzeba Xd

![Screenshot](https://user-images.githubusercontent.com/21177361/120628952-937b3b80-c465-11eb-9361-a6c7d2830f3e.png)

**Comment by hawkeye116477** [comment]
https://github.com/PolishFiltersTeam/KAD/issues/1739

**Comment by gzenio22** [comment]
ale ze jak stracic? Xd oglądając tam? nie mam zamiaru im płacic jak o to lotto

**Comment by xMaap** [comment]
Po wejściu na stronę infekuje kalendarz 
https://cert.orange.pl/aktualnosci/zbuntowany-kalendarz

![](https://cert.orange.pl/uploads/files/3ccfc88f1a210eb1686f558c9e2e6b8f23c96543.jpeg)

**Comment by krystian3w** [comment]
Duplicate of https://github.com/PolishFiltersTeam/KAD/issues/1739#issuecomment-821793506

**Comment by krystian3w** [comment]
W takim wypadku dodaj do reguł własnych AdGuard takie coś:

`||vider.info^$document,domain=vider.info|~uwaga-natretne-reklamy,badfilter`

Skoro w grę nie wchodzi okresowe klikanie "Mimo wszystko kontynuuj. Niby ten filtr już nie powinien blokować przy okazji `XmlHttpRequest` (xhr), że strona by mogła źle działać.
