### ISSUE TITLE
inchrightliquid.live

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/KAD#1796]
`https://inchrightliquid.live/?utm_campaign=pEv9cTd8QNHYzqqr5UNFx2COHvnp_JE3r8uVIhm3Qww1&t=main9`

**Comment by krystian3w** [comment]
Już offline.

I najnowsza ochrona zakłada blokowanie końcówki:

https://github.com/PolishFiltersTeam/KAD/blob/5285027f4b3b27a149faf99ce31c7a47bfaaf983/sections/przekrety.txt#L22
https://github.com/PolishFiltersTeam/KAD/blob/5285027f4b3b27a149faf99ce31c7a47bfaaf983/sections/przekrety.txt#L24-L26

Czyli link wyglądający mniej-wiecej:

`slowo123slowo.live/1234567890/?utm_`
`slowo123slowo.life/1234567890/?utm_`
