### ISSUE TITLE
debridleech.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1799]
### Link bezpośredni 
`https://www.debridleech.com/`
### Dodatkowe informacje mogące mieć znaczenie
Fałszywy generator.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Nie widzę polonizacji natywnej lub wtyczką/pluginem. Tej wbudowanej w chrome nie uznajemy.

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/121780214-9c73b780-cb9f-11eb-8157-6536063b1f42.png)
