### ISSUE TITLE
kilka witryn reklamowych

### ISSUE THREAD

**Issue by ProgramComputer** [PolishFiltersTeam/KAD#1814]
### Link bezpośredni do strony zawierającej "oszustwo"

```markdown
wizhumpgyros.com 

coccyxwickimp.com
```

### Dodatkowe informacje mogące mieć znaczenie

https://pastebin.com/VZNb7Xrg

```
Znalezione na toonily.com
Witryna korzysta z zaawansowanych reklam Wordpress Pro, więc to wszystko, co mogę zrobić bez blokowania reklam w skryptach.
```

**Comment by krystian3w** [comment]
EasyList / AdGuard Base powinno blokować sieciowo?

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/blob/6405616cec6697159e45b33ad9d58a4e97ae6bbf/easylist/easylist_adservers.txt#L10737
https://github.com/easylist/easylist/blob/6405616cec6697159e45b33ad9d58a4e97ae6bbf/easylist/easylist_adservers.txt#L2321

**Comment by krystian3w** [comment]
A majkiit nie lubi stron 18+, więc jak ci on reklam nie wyciął to zostaje uAssets.
