### ISSUE TITLE
wykonajzadanie.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1817]
### Dodatkowe informacje mogące mieć znaczenie
Oszustwo?

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Niby działa lub fałszowane wideo (brak 4K / cięcia):

https://www.youtube.com/watch?v=cB8JN_8B-sM

**Comment by ClusterByte-x** [comment]
Powyższe konto ma 150 subskrybentów i jeden video-poradnik. Domena `wykonajzadanie.pl` stworzona 30 marca 2021r. Wątpię, by dawali za taką prostą czynność równowartość 150 zł (4650 RP = 150 PLN). Oszustwo zdecydowanie.

**Comment by krystian3w** [comment]
Ocenisz polonizacje do linków gdzie przekierowują?
