### ISSUE TITLE
jannova.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1818]
### Link bezpośredni 
`https://jannova.pl/products/gaming?fbclid=IwAR2CTNFcXvv9lJ1V99txDhsSUTC7zoKn6FhHpP-OAQCXfjOWEjQx5T7_Q2o`
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/58887943/sklepyinternetowe-scam-no-ewidentnie-legitna-stron/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
> DOMAIN NAME:    jannova.pl
> registrant type:      individual
> **created:                  2021.07.03 19:42:15** <--- DOMENA STWORZONA NIEDAWNO
> last modified:         2021.07.03 19:54:20
> renewal date:          2022.07.03 19:42:15
