### ISSUE TITLE
atwi.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1819]
<div align="center">

### *Oszukańcze praktyki Atwi.pl - prośba o dodanie do KAD*

 </div>

### Link bezpośredni 
`https://atwi.pl/`
### Dodatkowe informacje mogące mieć znaczenie
Oszustwo ze strony firmy ATWI.pl polega na tym, że bazując na naiwności ludzi wciskają im strony ZROBIONE ZA DARMO gdzie później przychodzi płacić horrendalne kwoty za hosting i utrzymanie stron, a jeśli ktoś przestanie płacić to strony są usuwane.
Cała historia dostępna jest tutaj:
https://webcache.googleusercontent.com/search?q=cache:Iaocd___rPgJ:https://www.wykop.pl/wpis/54259075/mireczki-chcialem-wam-przedstawic-walek-ktory-od-j/199603095+&cd=11&hl=pl&ct=clnk&gl=pl

Niestety pełny wpis został już usunięty przez moderację WYKOP.pl o czym piszę tutaj
https://www.wykop.pl/wpis/58910423/mirki-afera-jest-dodalem-jakis-czas-temu-wpis-o-os/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Czyli nie dają danych dostępu na FTP/SSH a jak ktoś ma hosting i domenę własną to, be i oni muszą wykupywać (brak instrukcji "łopatologicznej jak to skopowiać do siebie jakby nie dało się zapewnić bezpieczeństwa własnego hostingu i domeny).

**Comment by ClusterByte-x** [comment]
- https://www.wykop.pl/link/6177485/wykop-bez-zadnej-informacji-usuwa-wpis-demaskujacy-dzialania-pewnej-firmy/#
- https://www.wykop.pl/wpis/46040469/o-gurwa-5000-zl-za-9h-kurs-wordpressa-xd-xd-xd-htt/
