### ISSUE TITLE
ndna.info

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1821]
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/58781699/uwazajcie-ktos-wyludza-dane-do-karty-pod-pretekste/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Wydaje się być offline = 404  i dla głównej "`Сайт «ndna.info» создан / Website "ndna.info" was created`"
