### ISSUE TITLE
fxpoint.co | bitengecko.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1823]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
fxpoint.co
bitengecko.com
```

### Dodatkowe informacje mogące mieć znaczenie

https://forexrev.pl/ostrzezenia-8-07-ncapital-group-fx-point-profit-trade/

**Comment by krystian3w** [comment]
https://pastebin.com/ftN5vqHt
