### ISSUE TITLE
cspricelist.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1824]
### Link bezpośredni 
`https://cspricelist.com/`
### Dodatkowe informacje mogące mieć znaczenie
Strona służąca do wyłudzania danych do kont Steam. Następnie przestępcy "opróżniają" konto ze skinów do gry CS:GO.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Kiepska polonizacja @ClusterByte-x w tobie nadzieja przed próbą zgłoszenia tego tylko do Google/Eset/Spam 404

**Comment by ClusterByte-x** [comment]
Niestety, strona nie nadaję się. Powód: brak polonizacji.

**Comment by ClusterByte-x** [comment]
Niestety, brak polonizacji.
