### ISSUE TITLE
telix.pl

### ISSUE THREAD

**Issue by seba2282** [PolishFiltersTeam/KAD#1825]
<div align="center"><h3> telix.pl - strona która wprowadza wszystkich w błąd z sugerowaniem tanich kluczy na produkty MS </h3></div>

Tak jak w temacie, np.:

https://www.telix.pl/artykuly/newsy/2021/07/letnia-promocja-oryginalny-klucz-windows-10-pro-oem-do-zdobycia-za-tylko-14/

Moglibyście polepszyć wyłapywanie takich typu stron moim zdaniem. Zweryfikujecie też ją. A ja nie wiem gdzie dokładnie zamieścić to zgłoszenie, bo po części jest to sugestia aby poprawić mechanizm wykrywania takich typów stron. Z drugiej strony zgłaszam konkretną stronę do weryfikacji.

**Comment by krystian3w** [comment]
Znaczy codziennie wpisywać w Google "windows 10 za darmo"?

**Comment by krystian3w** [comment]
@hawkeye116477 telix.pl banujemy, bo `||pl.whokeys.com` jest na liście:

https://github.com/PolishFiltersTeam/KAD/blob/d2c7e09c39a2e68e93d98340e37a0f6a13b6c193/sections/podejrzane_inne_oszustwa.txt#L1076

**Comment by hawkeye116477** [comment]
W zasadzie to może z 2 wpisy są z tą stroną, reszta wydaje się, że jest z wiarygodnymi linkami. A więc może po prostu proponuję propozycję nr 2 :smile:.

**Comment by seba2282** [comment]
> Chyba, że wystarczy uruchomić:
> 
> `##a[href*="whokeys.com/"]` w https://github.com/PolishFiltersTeam/KAD/edit/master/sections/natretne_lub_wprowadzajace_w_blad.txt

Znaczy ta? @hawkeye116477

**Comment by krystian3w** [comment]
Znaczy nie za bardzo opłaca się wycinać news letnia promocja z głównej, mogą co 4 godziny śledzić czym zablokowaliśmy i zmieniać klasy/url/tekst.

**Comment by hawkeye116477** [comment]
Od 6 września niby będzie zakaz takich praktyk. Tylko autoryzowani sprzedawcy będą mogli oferować klucze.
