### ISSUE TITLE
Fałszywy sklep bikiniboom.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1832]
### Link bezpośredni 
`https://www.bikiniboom.pl`
### Dodatkowe informacje mogące mieć znaczenie
Relacja oszukanej osoby: https://www.wykop.pl/wpis/59112053/oszukujo-rozowepaski-chcialbym-ostrzec-wszystkich-/
Sprawdziłem i płatność jest możliwa tylko przelewem. Adres z przelewu to adres siedziby Alior Banku.
Domena bikiniboom.pl wygasła 17 sierpnia 2020 i została kupiona ponownie 1 kwietnia 2021 w aftermarket.pl
Adres IP serwera to 23.227.38.65, reverse lookup pokazuje, że jest to adres IP myshopify.com

Dane do wpłaty:
BIKINIBOOM.PL
PEKAO SA
14124026141111001104311580
Alior Bank SA
68249010287000045102378952
ul.Łopuszańska 38D 02-232 Warszawa
Tytuł: imię i nazwisko lub numer zamówienia
Użyj tego numeru konta do przelewów międzynarodowych:
Alior Bank SA
PL68249010287000045102378952
GB16 TCCL 0414 0432 7890 96
SWIFT/BIC: TCCLGB3L

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
Wysłałem również zgłoszenie do zespołu [legalniewsieci.pl](https://www.legalniewsieci.pl/aktualnosci/podejrzane-sklepy-internetowe).

Nazwa domeny | bikiniboom.pl
-- | --
Stan | Aktywna w DNS [REGISTERED]
Utworzona | 2021.04.01 16:03:34
Ostatnia modyfikacja | 2021.05.05 17:13:40
Koniec okresu rozliczeniowego | 2022.04.01 16:03:34
Nazwy serwerów | ns1.aftermarket.pl [185.253.213.10] ns2.aftermarket.pl [185.253.214.10]

**Comment by hawkeye116477** [comment]
Nie ma numeru KRS.

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/126048525-dce8f22f-1970-45be-8761-d2aa53af2b1f.png)
