### ISSUE TITLE
panigoanalyticsgfabza.xyz

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1833]
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/59207605/smierdzi-walkiem-na-kilometr-ale-jak-to-jest-mozli/

![obraz](https://user-images.githubusercontent.com/35370833/126816827-bb8a66f0-cd8b-4711-9cb6-9aeb9a80b4e3.png)

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
U mnie offline.

**Comment by krystian3w** [comment]
```
panigoanalyticsgfbaza.xyz
is available
1 year
$ 12.88
$ 1.48
88.51% off

**Comment by hawkeye116477** [comment]
@krystian3w Nie jest offlnie, tylko zgłaszający pomylił adres. Spójrz na zrzut ekranu z wykopu. Wynika z niego, że poprawny adres to `panigoanalyticsgfabza.xyz` (baza => abza).
