### ISSUE TITLE
ewymianka.com.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1838]
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/59343049/jest-taka-strona-jak-e-wymiana-com-pl-na-pewno-kto/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
KAD blokuje pierwszą domenę. Pozostaje zablokować drugą.
> ||ewymiana.com.pl^$all
