### ISSUE TITLE
sekretfotki.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1841]
### Dodatkowe informacje mogące mieć znaczenie
Scam?
 https://www.wykop.pl/wpis/59369037/halo-co-to-za-scam-scam-nudes/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Raczej tak, yuki z uAssets zablokował:

`https://zbmerk.wishuiuck.net/c/1e3a4e532f1c7040?s1=115587&s2=1250785&s3=&s5=backuser&click_id=0ENaKqZxnA3wnv2z5oLn&iexpp=1&j1=1&j3=1&rref=` (brak polonizacji)
