### ISSUE TITLE
otomotoklik.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1844]
### Dodatkowe informacje mogące mieć znaczenie
Wykop: https://www.wykop.pl/wpis/59423673/wchodzac-na-otomoto-dostaje-ostrzezenie-z-avast-o-/

WHOIS - https://who.is/whois/otomotoklik.pl
VirusTotal - https://www.virustotal.com/gui/url/fda637cc2c19cc0dbaba049b94a381aeabfc7a4f73efc287769092b390c4ad42/detection

Nadgorliwy antywirus czy strona phishing?

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
To nowy serwis Otomoto.

https://www.facebook.com/otomotopl/posts/4767205323306975?__xts__%5B0%5D=68.ARC8G2DsaYPJepO3n5WaK9XmwvZAIhuJRRdk3WByE9OLWydzK0PpF1xEQ4sEvgDjVVeg-2_Y42ai3DwXaHonYX0mcz87MG1yquKB7b0F-5K0BLnTemQNMzhDmg6Th9njqznqXw7tBbiiQk1v99fKRFG5Y8l55C0ds4DywTKGftWR_nYRA-62RxubFODiO1_ucCVux6xhBS5RHbtid-fbQkO0fReZDp133p3nLXsYMSXZYOASeLicDLcT6a4OlkDodQY0fzQlnfTd2AUS_6V6fRZ-4R8rcCzVWDpxzFdzXPywBr3Piwgl2A&__tn__=-R

**Comment by xMaap** [comment]
Winny Avast to nowy serwis.
