### ISSUE TITLE
pl.decimuss.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1847]
### Link bezpośredni 
`https://pl.decimuss.com/silver-toner?fbclid=IwAR0nf44E-fqwoAPyELym8jUxbALSvI8_n5LXwHNsUA-r1TFmEdZYhcv4vy4`
### Dodatkowe informacje mogące mieć znaczenie
Omawiany produkt kosztuje ok. 10 zł -> https://www.rossmann.pl/Produkt/Plukanki/Delia-Cameleo-plukanka-do-wlosow-srebrna-200-ml,34005,8666

WHOIS - https://who.is/whois/decimuss.com
Expires On2022-06-08
Registered On2021-06-08
Updated On2021-06-08

Facebook - https://www.facebook.com/109409161405516/posts/6108687242489733/?d=n

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Wysoka ta marża/narzut.
