### ISSUE TITLE
eu.adyen.link

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1851]
### Dodatkowe informacje mogące mieć znaczenie
False positive? Wywołane przez wejście na OLX i kliknięcie "kupuję z przesyłką".

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
Raczej phishing. https://github.com/PolishFiltersTeam/KAD/commit/c8ace0f697e4018c9fb02e78fd54c4c0ba9bb6ee
![CE9C6737-4E37-43D2-81E4-4FFED50B6504](https://user-images.githubusercontent.com/76107417/129041106-74f8d319-b6df-4e03-b07a-165241f3decb.jpeg)

**Comment by xMaap** [comment]
Przydałoby się więcej szczegółów i adyen.link nie ma na liście KAD.

**Comment by ClusterByte-x** [comment]
https://github.com/PolishFiltersTeam/KAD/commit/c8ace0f697e4018c9fb02e78fd54c4c0ba9bb6ee

**Comment by hawkeye116477** [comment]
Aha, czyli nie zaktualizował listy.
