### ISSUE TITLE
Spam na youtube

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1855]
### Link bezpośredni 
`https://pinvazo.com/?gclid=CjwKCAjw9uKIBhA8EiwAYPUS3EKiMrm-s6hZdLe42PvBYHY1a91AJpJ7xXJKY5a2QHLfmiJk6pD01RoCu84QAvD_BwE&subid3=youtube.com`
### Dodatkowe informacje mogące mieć znaczenie
reklama na yt i link kierujący na ten link 

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
KAD reklam nie blokuje, wyciekają to musi to ogarnąć jedno z trzech repo:

- EasyList
- AdGuard Filters
- uAssets

ale raczej żaden nie posunie się do wycinania komentarzy nawet jakby sięgać po `:upward()`.
