### ISSUE TITLE
`poland-lotos.site` / `lotos-poland*.site`

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1859]
### Link bezpośredni 
`https://poland-lotos.site/`
### Dodatkowe informacje mogące mieć znaczenie
```https://poland-lotos.site/
https://lotos-poland1.site/
```
Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Raczej scam

**Comment by xMaap** [comment]
poland-lotos już Cert dodał.

**Comment by krystian3w** [comment]
Pod drugi uruchomię regex jak Hawkeye nie wyprzedzi.
