### ISSUE TITLE
Propozycja nowej listy - filtry blokujące pornografię

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1860]
### Dodatkowe informacje mogące mieć znaczenie
Czy PolishFIltersTeam byłby zainteresowany w ogóle stworzyć taką odrębną listę? Wydaje mi się, że jest dość duża luka jeśli o takie listy chodzi, zwłaszcza zawierajace polskojęzyczne strony. 

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Ja raczej nie, zostaje więc blocker / hawkeye / azet12
