### ISSUE TITLE
laptopy-komputery-naprawa.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1863]
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/59902949/tak-wyglada-jacek-pasztaleniec-jacek-pasztaleniec-/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
To chyba powiązane z tym: https://www.wykop.pl/link/6240697/podupadla-gwiazda-dziennikarstwa-chciala-wyludzic-200zl-powolujac-sie-na-wplywy/

![F5D8E472-3ECD-410D-8120-FD438D899C63](https://user-images.githubusercontent.com/76107417/130337474-8fa3a6f9-94af-4878-9c32-641ca0949e0e.jpeg)

**Comment by ClusterByte-x** [comment]
@krystian3w jeszcze domeny `regulamin-pomoc.pl` nie dodałeś.

**Comment by xMaap** [comment]
Matko po co mu tyle tego.

**Comment by krystian3w** [comment]
Bot za tydzień sprawdzi whois to się wywali.

**Comment by ClusterByte-x** [comment]
> Matko po co mu tyle tego.

Tych domen z tego co usłyszałem od pokrzywdzonych jest więcej. W razie czego mogą dopisywać tutaj lub zgłoszą mi.
