### ISSUE TITLE
thermomix.vorwerk.pl

### ISSUE THREAD

**Issue by moriakaice** [PolishFiltersTeam/KAD#1871]
### Bloker (Blocker)

uBlock Origin 1.37.2

### Link bezpośredni, na którym występuje problem

```markdown
https://thermomix.vorwerk.pl/
```

### Opis błędu

Rozumiem, że dla niektórych sposób sprzedaży Thermomixa może być podejrzany, ale strona jest legit, przekrętem nie jest.

**Comment by krystian3w** [comment]
Ale może jest na stronie dalej "zamów" pana z piramidy i stań się piramdziarzem z długami.

Kup starszy model na aukcji?

**Comment by moriakaice** [comment]
Ale to jest legalny, działający biznes, możesz kupić i dostaniesz Thermomixa (i nie, nie musisz zostawać sprzedawcą, lol). Tak, mają denerwujący system sprzedaży, ale skoro i tak nie można kupić tego przez stronę, to po co stronę blokować (zwłaszcza, że mają tam inne rzeczy, np. kreator etykiet: https://thermomix.vorwerk.pl/przepisy/kreator-etykiet/)?

Kosmetykowe MLMy, jak Oriflame, Avon itp. też będziecie podłączać pod "przekręty"? GMaila też kiedyś można było założyć tylko z zaproszenia...

**Comment by krystian3w** [comment]
Kreator etykiet powinien działać z nowym filtrem sieciowym, w obecnej formie jak nie chcesz dopisywać pustego parametru:

`/?_` to można dać w uBO:

`no-strict-blocking: thermomix.vorwerk.pl true`

uBO w przeciwieństwie do AG nie zablokuje xmlHttpRequest (dopiero to naprawiają i trzeba śledzić kiedy `doc` będzie blokować otwarcie witryny a nie przy okazji blokować `xhr`).

**Comment by moriakaice** [comment]
Dzięki za update (w chwili, gdy pisałem swój komentarz, jeszcze nowej listy nie mieliście zbudowanej, pomimo Twojego commitu). Teraz wszystko ładnie śmiga (poza zamawianiem prezentacji, ale to mi akurat obojętne :P).

Dzięki!
