### ISSUE TITLE
niedzwiedz-sanit.pl

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/KAD#1874]
### Dodatkowe informacje mogące mieć znaczenie

adguard

**Comment by hawkeye116477** [comment]
Strona została stworzona w 2013 roku, opinie ma raczej pozytywne. Jakiś komentarz do sprawy, bo `adguard` raczej nic nie wnosi :stuck_out_tongue:

**Comment by blocker999** [comment]
Być może to fałszywy alarm lub jakiiś błąd.

![sanit](https://user-images.githubusercontent.com/23176832/131533764-1efa5542-0a74-4a13-8391-b56ab0ee0ac4.png)

**Comment by hawkeye116477** [comment]
VirusTotal mówi, że jest [czysta](https://www.virustotal.com/gui/url/2d249638faec6cb2a0c8d46d65577841466d5e31aef2f91718b2ac186a1a1e48/detection).
