### ISSUE TITLE
Domeny z niebezpiecznika

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#1876]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://niebezpiecznik.pl/post/uwaga-na-oszustwo-na-orlen/?fbclid=IwAR2rtcQMZU4rwC-Cyny-c6nhIjmearQorYD4KRlFU9D8KbpN0WS-4fCAszM
```

### Dodatkowe informacje mogące mieć znaczenie

https://niebezpiecznik.pl/post/uwaga-na-oszustwo-na-orlen/?fbclid=IwAR2rtcQMZU4rwC-Cyny-c6nhIjmearQorYD4KRlFU9D8KbpN0WS-4fCAszM

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KAD/blob/47b2d6852ab1e3ecdc00fabe0c7d7f55f463fc2a/sections/przekrety.txt#L9365 https://github.com/PolishFiltersTeam/KAD/blob/47b2d6852ab1e3ecdc00fabe0c7d7f55f463fc2a/sections/przekrety.txt#L9980

tych co Cert nie tknął to:

`https://anubandi.com/`
`https://millsdeals.com/`
`https://geekrunners.com/`
`https://govtjobopenings.com/`
``https://411otelcoal.com/`
`https://ibriffath.com/`
