### ISSUE TITLE
auto.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1878]
### Link bezpośredni 
`http://yfteiytpr.newsy.auto.pl/?l=1`
### Dodatkowe informacje mogące mieć znaczenie
`https://www.wykop.pl/wpis/60148459/jakie-znacie-strony-z-oszustwami-na-holownie-i-pod/`

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by xMaap** [comment]
Ja bym dodał 
`newsy.auto.pl`
![Zrzut ekranu z 2021-09-02 21-28-31](https://user-images.githubusercontent.com/36385327/131904634-9345ef44-7d19-43cb-92ff-7dc447c56f20.png)

Oraz
`lockeddeal.com`
Który robi przekierowanie do
`bepayedtoday.com`

```
https://lockeddeal.com/click.php?project_id=e7a490add2&affiliate_id=d8dab2ece5
https://bepayedtoday.com/bitqt/?intgrtn_clickID=L1q5VomYxQ3GWAZrBdl69XJ0JgkPN0DyMPn2gzJKbaepkO74R&country=PL&intgrtn_redirectReturningLead=false
```

**Comment by krystian3w** [comment]
może wszystko co jest inne od www.auto.pl, bo widać coś nawala tam na hostingu (np. luki php...).
