### ISSUE TITLE
mobile.sites.google.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1880]
Szybkie pytanie dlaczego ta strona jest blokowana?

**Comment by krystian3w** [comment]
Cwaniaki zrobiły fejkowe zgłaszanie lub ingerują w mechanizm Google:

![obraz](https://user-images.githubusercontent.com/35370833/132109293-2d4d9eca-640e-4a8b-a422-e2ca36714f7b.png)

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersRegistry/commit/bfef188d9a7d861cae658583f58c5c9426a81f1e#diff-09a511950597e264cf166df99b5f90381d1a3aed9020ee9cba1a5d12222d661eL7909

https://github.com/AdguardTeam/FiltersRegistry/commit/bfef188d9a7d861cae658583f58c5c9426a81f1e#diff-09a511950597e264cf166df99b5f90381d1a3aed9020ee9cba1a5d12222d661eR11387

https://github.com/AdguardTeam/FiltersRegistry/commit/7bdce96003e0ba7cc6edbf845a9c9d7d10cfdad7#diff-09a511950597e264cf166df99b5f90381d1a3aed9020ee9cba1a5d12222d661eR11405

**Comment by krystian3w** [comment]
404, zbanowali też 2 podobne jakie powstały 14 dni temu.
