### ISSUE TITLE
wp-wiadomosci.eu

### ISSUE THREAD

**Issue by FadeMind** [PolishFiltersTeam/KAD#1882]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
http://wp-wiadomosci.eu/porwanie_szkola/?c=W%C4%85growcu&fbclid=IwAR1NuRoBOL8f7KM-nPeM915MvXtkFOxI6eBLrgfrz7uc8eOHkgZ8EhVD_tk#
```

### Dodatkowe informacje mogące mieć znaczenie

Scam na FB:
![20210907-1631021249](https://user-images.githubusercontent.com/9846948/132352971-1d6fe481-1b18-4578-b834-93fef3e27fbe.png)
chętnie udostępniany. ESET już wyje:
![20210907-1631021188](https://user-images.githubusercontent.com/9846948/132353026-3a171f74-1272-4c85-b063-f188a6d7a7c3.png)

**Comment by krystian3w** [comment]
https://cert.t-mobile.pl/alert.php?url=1acc30b3c3b85f22c3a2d42b7ee1e246

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KAD/blob/7b8ff60c66fbb14b310568a1f24ead221a29da44/sections/przekrety.txt#L11066

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KAD/commit/c7af62d5712612521742cc792461642cd97d3749#diff-269381da98ff06dde11226ef06019e35651b7f1ddf78a517bb878a5dd5eaf038R11325

**Comment by hawkeye116477** [comment]
No nie tak `dawno zrobione`, bo dopiero parę godzin po zgłoszeniu. Byłoby dawno jakby ktoś coś zgłosił, a wcześniej było już dodane.
