### ISSUE TITLE
Złośliwe WPAD

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1885]
### Link bezpośredni 
`https://cert.orange.pl/aktualnosci/jak-wpadnac-w-pulapke`
### Dodatkowe informacje mogące mieć znaczenie
https://cert.orange.pl/aktualnosci/jak-wpadnac-w-pulapke

```
wpad.BI
wpad.EXPOSED
wpad.ONLINE
wpad.BJ
wpad.FO
wpad.org.RU
wpad.BLACK
wpad.KE
wpad.RS
wpad.CI
wpad.MK
wpad.SITE
wpad.com.RU
wpad.MR
wpad.SOFTWARE
wpad.ENGINEER
wpad.MW
wpad.SPACE
wpad.EXCHANGE
wpad.net.RU
wpad.TRADE
```

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Na razie bez wlidcard/regex, jak zacznie mutować o np. cyfry to raczej nie ma wyjścia i trzeba iść w regex.
