### ISSUE TITLE
getvoltbox.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1887]
### Link bezpośredni 
`https://getvoltbox.com/article4/pl?gclid=EAIaIQobChMIjr-T_oWB8wIVrUYeAh1BbguEEAEYASAAEgL1qfD_BwE`
### Dodatkowe informacje mogące mieć znaczenie
Scam, oszustwo

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KAD/commit/669b68b3c14bfda14948521c98d9b09dad208385
