### ISSUE TITLE
lotos-polska.site

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1889]
### Link bezpośredni 
`https://lotos-polska.site/`
### Dodatkowe informacje mogące mieć znaczenie
wyglada na fejk news

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
```json
[
  {
    "RegisterPositionId": 21267,
    "DomainAddress": "lotos-polska.site",
    "InsertDate": "2021-07-23T16:47:16",
    "DeleteDate": null
  }
]
```

**Comment by ClusterByte-x** [comment]
Domena znajduje się na liście filtrów KAD-Przekręty:
https://github.com/PolishFiltersTeam/KAD/blob/00edbdbbbd185e3e3b83ad2df01bb1c04413064b/KAD.txt#L7977

Została dodana do listy CERT Polska w lipcu tego roku:
```
   "RegisterPositionId": 21267,
        "DomainAddress": "lotos-polska.site",
        "InsertDate": "2021-07-23T16:47:16",
        "DeleteDate": null
```

Zaktualizuj listę w blokerze reklam lub plik hosts -> https://kadantiscam.netlify.app

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KAD/blob/00edbdbbbd185e3e3b83ad2df01bb1c04413064b/sections/przekrety.txt#L6024

**Comment by krystian3w** [comment]
W HOSTS też się dodało:

https://github.com/PolishFiltersTeam/KADhosts/commit/ce137d005bdb8c67e5ec7cbf4249c0cae7ee322b#diff-10176db289275d94cf4db522d31673a57737d93d9b779e3c2edb5c151545c770R7564 lub https://github.com/PolishFiltersTeam/KADhosts/commit/ce137d005bdb8c67e5ec7cbf4249c0cae7ee322b#diff-10176db289275d94cf4db522d31673a57737d93d9b779e3c2edb5c151545c770R18001

https://github.com/PolishFiltersTeam/KADhosts/commit/9bc0cc4269912aada65672ebd8ecd13f1082bf97#diff-0cb6b2b322378cb88a5ef38147d3fea603a48615f505e9cae7d5eaf18bf6a603R7582 lub https://github.com/PolishFiltersTeam/KADhosts/commit/9bc0cc4269912aada65672ebd8ecd13f1082bf97#diff-0cb6b2b322378cb88a5ef38147d3fea603a48615f505e9cae7d5eaf18bf6a603R18019

Czyli autor utknął na wersji `2021.7.23.0`, dużo starszej lub zniekształconej.

**Comment by krystian3w** [comment]
Opcjonalnie można zmienić nagłówek na:

`[uBlock Origin 1.38.0 or AdGuard 3.6]`

lub na ABP 5.0 jakie wyjdzie pewnie za 3 lata dopiero.

Wtedy ABP i AdBlock generują błąd, że lista jest nieprawidłowa, podobnie jest w blokerze wbudowanym w Slimjet/SlimBrowser.
