### ISSUE TITLE
extubating.info

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1893]
### Link bezpośredni 
`https://weiloffers.com/btc-profit-multi/pl/index.html?d=eyJpZCI6MTEzNDQ3OCwic2VjcmV0IjoiOWE4N2NkMDMzZDM1OGVkZCIsImRvbWFpbiI6InFydXBub290ZS5jb20iLCJhcGkiOiJtZ2EifQ%3D%3D`
### Dodatkowe informacje mogące mieć znaczenie
Oszustwo

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
`dodanie wykrzyknika na początku lini`

Tak się oznacza komentarze. Można też za pomocą `#`, ale to chyba działa tylko w uBO.

**Comment by krystian3w** [comment]
Serwis z torrentami wyglądał mi na kolejną kopię z paywallem i być może fejkowymi plikami.

**Comment by ClusterByte-x** [comment]
@krystian3w podobne do zgłoszenia https://github.com/PolishFiltersTeam/KAD/issues/1898 
Zauważ, że co do `torrentos.pl` pod każdym filmem/gra są podobnie brzmiące komentarze i przewijanie jest zapętlone do tych samych tytułów. Co do wykrzyknika - wtedy bloker nie blokuje tej strony, a chyba powinien?
