### ISSUE TITLE
investingly.xyz

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1897]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
investingly.xyz
```

### Dodatkowe informacje mogące mieć znaczenie

![](https://cert.orange.pl/uploads/files/8b13bdd67cdda208ef19132c4443df6814806656.png)

**Comment by ClusterByte-x** [comment]
<img width="1303" alt="Zrzut ekranu 2021-09-23 o 00 00 03" src="https://user-images.githubusercontent.com/76107417/134427899-2d072627-17b6-4089-be96-5224b930919d.png">
