### ISSUE TITLE
torrenteo.nojo.tv

### ISSUE THREAD

**Issue by mino815** [PolishFiltersTeam/KAD#1898]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://torrenteo.nojo.tv//film/Co+w+duszy+gra-2020-836650
```

### Dodatkowe informacje mogące mieć znaczenie

"Aby móc w pełni korzystać z zasobów witryny bez limitów, konieczna jest aktywacja konta"

**Comment by ClusterByte-x** [comment]
Z regulaminu serwisu - https://torrenteo.nojo.tv/pTORRENTEO/regulamin.pdf

> NOJO TV to informacyjny portal internetowy, umożliwiający wyszukiwanie użytkownikom źródeł (linków) do filmów udostępnianych przez podmioty trzecie. NOJO TV samodzielnie nie stream-uje, ani w żaden inny sposób nie udostępnia samodzielnie filmów. Oglądanie filmów następuje w portalach i na warunkach (w tym, regulaminie oraz przy odrębnej odpłatności) określonych przez podmioty udostępniające dany film.

> Jedyną funkcjonalnością NOJO TV jest wyszukiwanie źródeł (linków) do filmów udostępnianych przez podmioty trzecie, co oznacza, że NOJO TV jest wyszukiwarką
> materiałów filmowych. Przejście przez użytkownika przez hiperłącze (klikniecie w link) spowoduje przeniesienie użytkownika do innego niż NOJO TV portalu. NOJO TV:
> a. informuje, że uiszczenie opłaty przez użytkownika za korzystanie z wyszukiwarki nie zwalnia go z konieczności uiszczenia opłat za możliwość oglądania filmu, o ile taka opłata została przewidziana;
> b. nie bada zawartości linkowanych stron internetowych pod kątem obecności złośliwego oprogramowania lub innych nieprawidłowości. Tym samym, NOJO TV nie ponosi odpowiedzialności za szkody poniesione przez użytkownika, wynikające z korzystania przez niego z witryn zewnętrznych;
> c. nie gwarantuje, że pod podanym linkiem znajduje się poszukiwany przez użytkownika film. Dane w NOJO TV aktualizowane są na bieżąco, przy czym ich dostępność uzależniona jest od dostępności witryny zewnętrznej, która także na bieżąco może się zmieniać.

Ze stopki strony:

> Znalazłeś się właśnie na platformie będącej prawdopodobnie najskuteczniejszym agregatem posiadającym dane o dostępności filmów i seriali na legalnych platformach vod. Jeżeli nie wiesz który serwis posiada najwięcej Twoich ulubionych filmów bądź tych, które dopiero chciałbyś obejrzeć, znalazłeś się we właściwym miejscu w sieci. Każdy użytkownik, który aktywuje swoje konto, uzyskuje dostęp do oferowanych przez nas danych.
