### ISSUE TITLE
zasobygwp.pl

### ISSUE THREAD

**Issue by AroKol78** [PolishFiltersTeam/KAD#1901]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://zasobygwp.pl
```

### Dodatkowe informacje mogące mieć znaczenie

nie wiem czy spełnia wymogi (Phishing?) tej listy czy może "Polish Privacy Filters"
przekierowania z poczty (temat z `https://forum.dobreprogramy.pl/t/przekierowanie-na-zasobygwp-pl/522915`)
na "virustotal" pokazuje 5 zagrożeń
stare info ale ciekawe `https://zaufanatrzeciastrona.pl/post/prosty-ale-skuteczny-atak-na-uzytkownikow-allegro-trwa-od-4-lat/`

**Comment by ClusterByte-x** [comment]
@AroKol78 - mógłbyś pokazać pełny link?
<img width="970" alt="Zrzut ekranu 2021-09-24 o 00 09 33" src="https://user-images.githubusercontent.com/76107417/134590715-e27ddac9-c227-4636-8e20-a2fdd6b71107.png">

**Comment by krystian3w** [comment]
Pewnie to samo co ze OpenDNS / PhishTank:

<a href="https://phishtank.com/phish_detail.php?phish_id=6891502">

```
https://phishtank.com/phish_detail.php?phish_id=6891502
```

</a>

https://github.com/curbengh/phishing-filter/issues/2 / https://gitlab.com/curben/phishing-filter/-/issues/5


---

Luki niby WP może mieć gdzieś w serwerach lub ktoś nawet złapać infekcję DNS co podmienia zawartość domeny na coś innego i tylko po https można poznać, że jest konflikt certyfikatu.

**Comment by krystian3w** [comment]
Niby też jest nowszy temat ale progiem wejścia może być znajomość polskiego przez Iwonę:

https://forum.dobreprogramy.pl/t/opera-witryna-poczty-o2-pl-jest-nieosiagalna-err-connection-reset/650415/10

**Comment by krystian3w** [comment]
Jakby ktoś chciał się bawić w regex z `not`:

nowy scam domen life blokowany regexem od Yuki z uAssets:

```
https://zasobygwp.pl/redirect?sig=68e20855ea54cccc22db6379668bbe921c4b7eb20675234f7f34658eb1ef77fd&url=aHR0cHM6Ly95b3VybGFkaWVmdW4ubGlmZS8_dT0ydXJwZDB4Jm89eWtmZWt1ZCZtPTEmdD13cDIxMDktMTAwMA==&platform=desktop&brand=wp&middleguard=true&platform=desktop&label=5&brand=wp
```

Link od niebezpiecznika bez parametrów ograniczających automatyczne otwarcie:

```
https://zasobygwp.pl/redirect?sig=0316577be0ea59123e5040dc84c5b5aed56acc8d95dded47a3c6bc8aca4916a7&url=aHR0cHM6Ly9ndXNjaG8ucnUvd3AtbG9naW5nL3dwLw==&platform=app_ios&brand=o2
```

**Comment by AroKol78** [comment]
ip servera od `zasobygwp.pl` co podaje virustotal jest przez "avire" oznaczone jako "phishing"

> nie wiem czy spełnia wymogi (Phishing?) tej listy czy może "Polish Privacy Filters"

`||zasobygwp.pl^$all` już se dałem  :relaxed:

**Comment by AroKol78** [comment]
sprawdziłem pocztę i tylko znalazłem to związane z `zasobygwp`
`https://zasobygwp.pl/proxy?sig= ...............` `$image` ("ubo-logger")

`^$all` - jest za mocny
na razie zostawię se to `||zasobygwp.pl/redirect?sig=` tak na wszelki wypadek chyba, że ktoś zna coś lepszego

**Comment by krystian3w** [comment]
Wymyśliłem taki regex:

```
/^https?:\/\/zasobyg(rupy)?\.?wp.pl\/(proxy|redirect)(?!.*middleguard=true)[\w]{0,}/$document,domain=zasobygwp.pl|zasobyg.wp.pl|zasobygrupy.wp.pl
```

ale on ma lukę w postaci `.*` - taki zapis nie powinien zostać za ukośnikiem i trzeba by znaleźć spósób na sprawdzanie czy przed `middle` jest `$` lub `?`.

**Comment by AroKol78** [comment]
nie widziałem `redirect`,`middleguard`  ("ubo-logger")
u mnie tylko `proxy` z `?sig=` i `&url=` innych parametrów nie uraczyłem
`$image` naprawdę są obrazkami

**Comment by krystian3w** [comment]
Mnie chodzi, że link z `middleguard=true` generuje planszę jaką załączyłem w https://github.com/PolishFiltersTeam/KAD/issues/1901#issuecomment-926212326 i jej nie ma sensu blokować.

Jak parametru braknie to ich link działa jak każdy inny ze skraczacza linków lub domen: https://github.com/PolishFiltersTeam/KAD/blob/master/sections/przekierowujace_do_przekretow.txt

**Comment by AroKol78** [comment]
mi tylko pobiera z `zasobygwp` obrazki powiązane z mailem

**Comment by krystian3w** [comment]
Ale w regexie na końcu nie ma `$image` ani `domain=poczta.wp.pl` / `poczta.o2.pl` by się psuł mail, w TB na 99% obrazek nie będzie używał domeny WP a leciał w base64 lub z brzydkiej domeny po "URL".

**Comment by AroKol78** [comment]
> Jedynie przypominam, że regex ma dziwne ograniczenie, że nie mogę generować wykluczenia z `[\w]+` i dodać wykrywania `$` lub `?` przed słowem `middleguard`.

> na razie zostawię se to `||zasobygwp.pl/redirect?sig=` tak na wszelki wypadek

chodzi ot żeby na przyszłość nie powtórzyła się historia 
`https://zaufanatrzeciastrona.pl/post/prosty-ale-skuteczny-atak-na-uzytkownikow-allegro-trwa-od-4-lat/`
`https://forum.dobreprogramy.pl/t/przekierowanie-na-zasobygwp-pl/522915`
`https://forum.dobreprogramy.pl/t/opera-witryna-poczty-o2-pl-jest-nieosiagalna-err-connection-reset/650415/10`

a wersja z `proxy` - tak na wszelki wypadek (u mnie i tak szyły tylko obrazki)
`||zasobygwp.pl/proxy?sig=`
`@@||zasobygwp.pl/proxy?sig=$image`
