### ISSUE TITLE
profit-btc.monster

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1904]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
profit-btc.monster
```

### Dodatkowe informacje mogące mieć znaczenie

![Zrzut ekranu z 2021-09-24 20-49-38](https://user-images.githubusercontent.com/36385327/134725582-eae9255b-9fc4-4047-8710-9497dca3c881.png)

**Comment by ClusterByte-x** [comment]
Zgłoszenie podobne do: https://github.com/PolishFiltersTeam/KAD/issues/1897
