### ISSUE TITLE
herosuby-xyz.preview-domain.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1907]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
herosuby-xyz.preview-domain.com
```

### Dodatkowe informacje mogące mieć znaczenie

![Zrzut ekranu z 2021-09-26 10-46-46](https://user-images.githubusercontent.com/36385327/134800627-ff54d263-6af7-4eea-931f-1daf5405767f.png)

**Comment by ClusterByte-x** [comment]
Bot powinien niedługo dodać z listy CERT Polska.

```
"RegisterPositionId": 30181,
        "DomainAddress": "herosuby-xyz.preview-domain.com",
        "InsertDate": "2021-09-26T10:05:04",
        "DeleteDate": null
```

**Comment by ClusterByte-x** [comment]
https://github.com/PolishFiltersTeam/KAD/commit/82732d0667cb73441c29a7c6af008e07545d4250
