### ISSUE TITLE
kupbilecik.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1910]
### Link bezpośredni 
`https://www.kupbilecik.pl/imprezy/63387/Rzeszów/Kult/`
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/60721029/moze-mi-ktos-wytlumaczyc-o-o-chodzi-https-www-kupb/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
Raczej tak jak w https://github.com/PolishFiltersTeam/KAD/pull/1905, bo domena założona już w 2010 roku.


<img width="937" alt="Zrzut ekranu 2021-09-28 o 22 00 35" src="https://user-images.githubusercontent.com/76107417/135157428-bff4b80c-de39-4880-8788-0ed2c18f8bc3.png">

**Comment by krystian3w** [comment]
Ja mam już odwołanie na `kupbilecik.pl`, można najwyżej resztę przyblokować i śledzić profil kultu lub ich trasę koncertową.
