### ISSUE TITLE
tametc.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#1911]
### Link bezpośredni 
`https://www.wykop.pl/wpis/60720093/ktos-tez-to-gowno-dostal-scam-oszukujo/`
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/60720093/ktos-tez-to-gowno-dostal-scam-oszukujo/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
`tametc.pl `
`subscribepage.com`

https://www.nieznany-numer.pl/Numer/723975692
