### ISSUE TITLE
`kartliew.com`   | `agloclar.com`

### ISSUE THREAD

**Issue by FadeMind** [PolishFiltersTeam/KAD#1918]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://l.facebook.com/l.php?u=http%3A%2F%2Fyoutube.com.ued2c3z0.kartliew.com%2Ffyth84dglxa31zv4ty8h.image%3Fid%3DMQ%252F%26fbclid%3DIwAR2GvWrKmT_hfi7MtTsBZKxhZIUJNxQu_0akvNC8tMgkz4c0MymnVuYZ96k&h=AT030h2iZVcwl3URCo3UyefV_70BbKAtI-72ODnhe2tbYMObmpXdMxTgZeurmVMZsA5St_c9EhhPHmAi422B0XBkBOiosp25TUz_w0s8102i83Yd7Ddq-yDVtbV_FWescGMn&__tn__=%2CmH-y-R&c[0]=AT1YKdV50eZplA34SmBnhTG5vvQdoqzmMsHQy8aptCAtPVB-A29R-dLJGkbBBM-fDbchMU7d6HRTAW_do86Fh7IQ5ccUzlG6y4aphhHoyC_fXLWReAXJlgrZ6l_4FHhkJ0vfT-x1LoeFveCzcDH7TP3RqeT2aXE4AyI43jOz6zgrNFAMIvV2eaIBq5VGYAR5h2yD4cNW-hZM1HlCyLnByjQhJbjsyl1qn9OYKWM9ETL4QE6yPGIq7XVqjas
```

### Dodatkowe informacje mogące mieć znaczenie

Scam na FB
<details>
<img src="https://user-images.githubusercontent.com/9846948/136000729-65e34f0a-9f4d-43b5-a560-5e5a4c7ba0b4.png">
</details>

**Comment by krystian3w** [comment]
Ja nie mam polonizacji tylko wietnamski...

**Comment by krystian3w** [comment]
Albo angielski blogspot:

`https://as70013614.blogspot.com/2021/08/daily-tiktok-thots-compilation.html`

**Comment by FadeMind** [comment]
@krystian3w 
![20211006-1633501738](https://user-images.githubusercontent.com/9846948/136151673-80808ab1-1719-4b6f-9967-e3c90e102eef.png)

`http://youtube.com.cjl6wf5y.agloclar.com/mdw3rehsw4nntjpn7gii.image?id=MQ%2F&fbclid=IwAR2dXfU8npWzZuCOCGgXLWvQDSAZnBQ_mPkOzgyJuY7_5sGpUKYAvDnNpnY`

![20211006-1633501844](https://user-images.githubusercontent.com/9846948/136151862-d656e459-5c0c-4ebb-98b6-a1933da4bfdb.png)

**Comment by krystian3w** [comment]
Dalej opis posta po angielsku z nagą panią.

Strona ostrzegawcza bazuje na ustawieniach przeglądarki/systemu, bo ostrzeżenie po angielsku lub wietnamsku będzie dla części Polaków niezrozumiałe (przy wietnamskim może to być nawet 90% a nie daj Boże ktoś uzna, że to po węgiersku z 4 literowymi słowami...).
