### ISSUE TITLE
biegnij.buzz

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#1924]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://biegnij.buzz/dec/index2.html?cpid=4f701023-1833-43d9-9696-c74e59d36960
https://www.sprzet-sportowy.fans/
```

### Dodatkowe informacje mogące mieć znaczenie

Fejkowy konkurs na bon 500 zł do Decathlonu.

**Comment by ClusterByte-x** [comment]
https://github.com/PolishFiltersTeam/KAD/pull/1922
