### ISSUE TITLE
Nowa sekcja w aktualizacji 2018061602

### ISSUE THREAD

**Issue by azet12** [PolishFiltersTeam/KAD#649]
Aktualizacja 2018061602 wprowadza nową sekcję stron. Jest to sekcja _Promocja pseudonauki / Fake news_ na podstawie zasad stron dodawanych do KAD: https://github.com/azet12/KAD/wiki/Strony.

### Dlaczego o tym informuję
Fake news i podobne kwestie są istotnie kontrowersyjne, dlatego chcę być przejrzysty w tym, co robię.

### Jakie strony wprowadza aktualizacja 2018061602
- strony powiązane z osobą Jerzego Zięby, jego marki Visanto lub jego książki "Ukryte terapie"
- strony powiązane z ruchem antyszczepionkowym
- strony powiązane z osobą Justyny Sochy

### Dlaczego teraz
_Tekst zawiera opinię_
Osoby takie jak Justyna Socha i Jerzy Zięba są mi znane od dawna, jednak ostatnio zagłębiłem się w sylwetki tych postaci. Ostatnio zobaczyłem, że Jerzy Zięba poleca kąpiele w perhydrolu. Było to dla mnie bardzo alarmujące. Dodatkowo, ostatnio miała miejsce manifestacja STOP NOP.

Osoby takie jak Jerzy Zięba i Justyna Socha promują kontrowersyjne, a często nawet niezgodne z nauką postulaty. Dodatkowo, Pan Jerzy i Pani Justyna nie mają naukowych tytułów. Nie przeszkadzało to jednak Panu Jerzemu napisania książki o terapiach, a Pani Sochy utworzenia polskiego ruchu antyszczepionkowego.

----

*Jeśli jednak nie chcesz blokować tej sekcji stron, nie będę ci stał na przeszkodzie, **[kliknij tutaj][KAD - Fake Whitelist Subscribe]** a blokowanie tej sekcji zostanie zatrzymane.*

[KAD - Fake Whitelist Subscribe]: https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/azet12/KAD/gh-pages/assets/other/kadfakewhitelist.txt&title=KADfakeWL

**Comment by KonoromiHimaries** [comment]
lepiej zrobić nową listę, nie każdy chce blokować fejkniusy

**Comment by KonoromiHimaries** [comment]
prosiłbym o przeniesienie fejkniusów do osobnej listy

**Comment by azet12** [comment]
@KonoromiHimaries To by mijało się z celem. Nie skupiam się na tych stronach, lista by była bardzo krótka. Unikam kwestii politycznych. Dodatkowo, podobne strony (podejrzane leki) już znajdowały się na liście, np. dziwne preparaty na odchudzanie lub podobne.

**Comment by SceneAddict** [comment]
Ja również bym prosił o oddzielenie tej sekcji; ogólnie filtry mi się podobają, ale takie coś to bardziej podchodzi pod cenzurę innych punktów widzenia (nawet jeśli są one pseudonaukowe/anty-naukowe) niż zwalczanie realnych przekrętów w stylu phishingu.

**Comment by xMaap** [comment]
To mają być strony tylko z pseudonauką i tymi lekami?

**Comment by azet12** [comment]
@xMaap Jeśli masz na myśli whitelistę, to blokowane jest sekcja https://github.com/azet12/KAD/blob/a6dbc29bf5a4bbeba63dd21f7b5c1f5fff642c7b/KAD.txt#L589
Na chwilę obecną jest to 11 stron:
`||bio-chemik24.pl^
||jerzyzieba.com^
||odpowiedzialni-rodzice.pl^
||paulinajanowicz.pl^
||planetazdrowia.com^
||stopnop.com.pl^
||timeforvitamins.com^
||ukryteterapie.pl^
||vaccgenocide.wordpress.com^
||www.odkrywamyzakryte.com^
||www.witnatura.pl^`

Jeśli zasubskrybujesz link w mojej odpowiedzi wyżej, te strony przestaną być blokowane przez KAD. Reszta stron z przekrętami będzie dalej blokowana.

**Comment by xMaap** [comment]
Nie wiem dlaczego, ale na Operze nie blokuje mi tych stron i tylko z tej sekcji. Na Chrome, Firefox normalnie blokuje.

**Comment by azet12** [comment]
@xMaap Miałem podobnie i głupio to zabrzmi, ale samo się naprawiło po pewnym czasie (może po aktualizacji uBO, nie wiem). Spróbuj usunąć całą listę z ustawień uBO wchodząc podobnie jak tutaj: https://github.com/azet12/KAD/wiki/Instalacja-manualna i klikając ikonę kosza przy KAD a następnie "Zastosuj zmiany". Potem wejdź na https://azet12.github.io/KAD/ i zasubskrybuj ponownie.
Jeśli nadal się upiera, możesz usunąć całego uBO i zainstalować ponownie.
Jak dalej nie działa, spróbuj dodać samemu te strony w zakładce "Moje filtry" ustawień. Wklej:
```
||bio-chemik24.pl^
||jerzyzieba.com^
||odpowiedzialni-rodzice.pl^
||paulinajanowicz.pl^
||planetazdrowia.com^
||stopnop.com.pl^
||timeforvitamins.com^
||ukryteterapie.pl^
||vaccgenocide.wordpress.com^
||www.odkrywamyzakryte.com^
||www.witnatura.pl^
```
Zapisz i sprawdź. Wejdź na dowolną stąd stronę i zobacz czy pokazuje "Filtr znajduje się na liście: KAD - Przekręty". Jeśli tak, usuń te linijki i zapisz ponownie. To powinno odświeżyć.

**Comment by xMaap** [comment]
Przywróciłem ustawienia domyślne i dodałem jeszcze raz filtr i działa.

Poszukaj też o:
Janusz Bieszk - turbosłowianin nie wiem czy prowadzi jakiegoś bloga wiem, że książki napisał
Maciej Giertych - młoda ziemia czy coś takiego też nie wiem czy prowadzi jakiegoś bloga, ale na pewno ma sporo napisanych książek
Jan Pająk - UFO itd. http://pajak.org.nz http://totalizm.com.pl
Paweł Chojecki - może nie ma tu nic z pseudonauką, ale prowadzi własną sektę i nic tu nie ma wspólnego z religią i wszędzie widzi żydów. W sumie to z lewej i z prawej go krytykują. https://idzpodprad.pl http://idzpodprad.tv
Jeszcze http://www.zjawiskaniewyjasnione.pl
https://obserwatorczasowkonca.wordpress.com
http://www.jasnastronamocy.info
https://wolna-polska.pl
http://forumplaskaziemia.pl
https://gaja.tv
http://detektywprawdy.pl
https://radionafali.pl

**Comment by xMaap** [comment]
https://wiesci24.pl
Co i jak http://www.wykop.pl/ramka/3840639/moze-afera-moze-nie-luzne-podsumowanie-tego-co-sie-dzieje-w-ostatnich-dniach/
http://www.wykop.pl/ramka/3982527/afera-fejkowi-redaktorzy-wiesci24-pl-podszywaja-sie-pod-ukradzione-tozsamosci/

**Comment by xMaap** [comment]
http://porozmawiajmy.tv - nie chce mi się nawet tłumaczyć
http://emisja.tv - Rosja jest wspaniała, Ameryka to zagrożenie dla polski, żydzi itd.

**Comment by xMaap** [comment]
http://www.portal.nysa.pl
https://prawda2.info

@azet12 a nie dałoby rady dodać filtru do uBlock Origin albo chociaż do Nano Adblocker?

**Comment by azet12** [comment]
@xMaap Powstrzymam się od blokowania stron z teoriami spiskowymi i podobnymi dziwactwami, uważam, że to bez sensu.
https://github.com/azet12/KAD/issues/649#issuecomment-405580081 - właśnie takie przypadki mnie interesują.

> @azet12 a nie dałoby rady dodać filtru do uBlock Origin albo chociaż do Nano Adblocker?

Pytałem się gorhilla o dodanie mojego filtra, jednak odmówił, ponieważ jest ich tam już za dużo.

**Comment by krystian3w** [comment]
> Jeśli nadal się upiera, możesz usunąć całego uBO i zainstalować ponownie.

* Można spróbować wygenerowany link aktualizacji zobaczyć w loggerze (uBO doklei parametr "`_`" z cyfrą np. "`?_=213077`"), 
* skopiować, 
* wkleić do przeglądarki, 
* odświeżyć <kbd>Ctrl</kbd> + <kbd>F5</kbd> i potem wymusić aktualizacje w uBO = u mnie takie coś działa i unikam resetowania dodatku.

**Comment by krystian3w** [comment]
`||facebook.com/justynasochastopnop/*$document,domain=pl-pl.facebook.com`
`||youtube.com/channel/UCNLjn8aCPtoIyx9v81vAkCQ$document,domain=youtube.com`

a takie coś dla uBlock Origin to już będzie przesada?

**Comment by krystian3w** [comment]
Hmmm... wyczuwam urlop.

**Comment by azet12** [comment]
@krystian3w Blokowanie profili na fb i youtube nie będzie tak naprawdę działać, bo i tak będziesz widzieć ich posty i filmy. A poza tym to lekka przesada.
Staram się wchodzić co tydzień, nie zawsze wychodzi. Być może wkrótce dam komuś z polish filters uprawnienia do repo, żeby mogli aktualizować jakbym wyparował na dłużej.

@xMaap Strony podobne do aszdziennika. To jest humorystyczne i niegroźne. A to, że ludzie wierzą we wszystko... ¯\_(ツ)_/¯

**Comment by azet12** [comment]
@MajkiIT To by pomogło.
Jest jednak coś, czego twój automat nie dodaje. Jest to sekcja
`# Szybko wygaszajace mobilne i dodatki hosts` która jest ekskluzywna dla tego pliku i nie występuje w zwykłym KAD. Musi ona istnieć, bo bez tego niektóre strony nadal nie będą blokowane ze względu na to, że hosts działa okropnie. Jeśli dodasz do niego `0.0.0.0 example.com` to już nie będzie blokował `0.0.0.0 www.example.com`, przez co niektóre strony muszę dodawać podwójnie, bo czasami przełączają się na www. Najgorsze jest to, że niekoniecznie te dodatki znajdują się w tej sekcji akurat. Więc trzeba by było od KADhosts usunąć zawartość KAD i zobaczyć, jakie strony tam są i wkońcu zrobić z tym porządek i przenieść do jednej sekcji.

**Comment by MajkiIT** [comment]
@azet12 nie ma jej, bo ja obrabiam ten plik https://raw.githubusercontent.com/azet12/KAD/master/KAD.txt

**Comment by azet12** [comment]
@MajkiIT Domyślałem się właśnie. Jak proponujesz rozwiązać ten problem? Czy dodać te strony do normalnego filtra, żeby automat je stamtąd brał? Wtedy jednak te zasady będą wyskakiwały jako duplikaty w redundancy checker.

**Comment by azet12** [comment]
@hawkeye116477 No kombinuję. Gdzie znajdę ten token i gdzie go wpisać?

**Comment by hawkeye116477** [comment]
@azet12 Token można wygenerować na `https://github.com/settings/tokens/new`, wpisać dowolną nazwę i  zaznaczyć `public_repo `. A jeżeli nie masz Linuxa, to wpisać go można na `https://travis-ci.com/`, tylko najpierw trzeba aktywować tam swoje repozytorium, a potem kliknąć tam w nazwę swojego repo i w more options => settings, no i w Environment Variables jako name wpisać `GH_TOKEN`, a jako wartość - wygenerowaną wartość przez GH. W ramach bezpieczeństwa, do tej komendy `git push` można jeszcze dopisać na końcu linii `>/dev/null 2>&1`   tak żeby przypadkiem token nie stał się publiczny :smile:. Polecam oczywiście to wszystko robić najlepiej na drugim koncie GH przeznaczonym specjalnie dla CI (machine account).

**Comment by azet12** [comment]
@hawkeye116477 No niestety nie wychodzi mi. Wysłałem ci emaila, żeby nie zaśmiecać tutaj.

**Comment by xMaap** [comment]
@azet12 a to nadaje się?
https://www.meganiusy.com
https://polakuleczsiesam.pl
http://biotalerz.pl

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KAD/issues/889

**Comment by krystian3w** [comment]
Jakby ktoś się dziwił że filtr: `KAD - Whitelista Stron Kontrowersyjnych​` to tak ma być za sprawą: `badfilter`

---
<sup>https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#badfilter</sup>
<sup>https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#badfilter-modifier</sup>

**Comment by krystian3w** [comment]
Jakby ktoś się dziwił że filtr: `KAD - Whitelista Stron Kontrowersyjnych​` ma `0 na 0 użytych`, to tak ma być za sprawą: `badfilter`.

---
<sup>https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#badfilter</sup>
<sup>https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#badfilter-modifier</sup>

**Comment by wolnemedia** [comment]
To co robicie to zakazana w Konstytucji RP cenzura prewencyjna, czyli blokowanie ludziom dostępu do starych i nowych treści stron z czarnej listy, na których znajduje się krytyka szczepień, dodatkowo strasząc internautów, że strona na którą chcą wejść to „przekręt".

Z poglądami dyskutuje się na argumenty, a nie cenzuruje/blokuje, tym bardziej że ludzie instalujący Wasz filtr Wam ufają, a Wy nadużywacie tego zaufania do prywatnej walki z osobami, z którymi się nie zgadzacie i ze stronami, które pozwalają im się wypowiadać w imię wolności słowa i prawa doi rozpowszechniania informacji. Wasza działalność jest niemoralna i przypomina działalność nazistów, którzy palili niewygodne książki.

Nie wiedziałbym o Waszej cenzurze, gdyby nie powiadomił mnie użytkownik, który jest oburzony, że zablokowaliście mu dostęp do mojego portalu. Musiał się nagimnastykować, by odzyskać dostęp. To co robicie jest ZŁE, a Wasze intencje, jakimi jest walka z konkretnymi osobami narażającymi się tzw. Wielkiej Farmacji - Justyną Sochą i Jerzym Ziębą - podważają Waszą wiarygodność i uczciwość.

Zastanawiam się, czy zgłosić na Policję Wasze publiczne zniesławienie mojego portalu i blokowanie ludziom dostępu do informacji wywołując u nich nieuzasadniony strach przed wejściem na stronę. Mam świadka - który chciał wejść na moją stronę, a Wasz filtr mu ją zablokował. Nie wyrażał zgody na cenzurowanie stron internetowych, chciał tylko mieć zablokowane strony niebezpieczne (np. piramid finansowych czy firm na miarę Amber Gold), a nie z niewygodnymi światopoglądami.
