### ISSUE TITLE
ask.com

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#798]
Dlaczego to blokujesz?

**Comment by krystian3w** [comment]
A kto tego używa już Duck Duck  czy Bing lepszy

**Comment by azet12** [comment]
@MajkiIT Ask.com to przecież znana strona dodawana przez adware. Coś około 2010 było to bardzo popularne, teraz mniej.

**Comment by krystian3w** [comment]
No niby tak, ale filtrem adware nie wyleczysz, jak ktoś się uparł to może z niej korzystać do dzisiaj.
