### ISSUE TITLE
instantreward.site

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#879]
https://www.instantreward.site/dir/gift/iphone/pl/

Nie wiem dlaczego teraz się strona nie chce załadować, ale było tam coś w stylu "Jesteś milionową osobą"

**Comment by hawkeye116477** [comment]
Aktualnie z głównej przekierowuje do Google, jest zarejestrowana do 2020, więc pewnie jeszcze będą coś kombinować.

**Comment by xMaap** [comment]
Można zamknąć?
