### ISSUE TITLE
Strony z Fake Newsami

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#889]
```
wyborcza24.pl
wsieci24.pl
oneto.pl
```
W ogóle to śmierdzi ruskimi trollami

https://www.wykop.pl/link/4934615/#comment-65243899

**Comment by hawkeye116477** [comment]
`https://oko.press/rosyjska-propagande-szerza-polskie-portale-znalezlismy-23-takie-witryny/`
Jest ich jeszcze więcej.

**Comment by krystian3w** [comment]
Ja się w tym nie czuję, może niech @azet12 rozwija sobie tę sekcję.

**Comment by hawkeye116477** [comment]
Tak w zasadzie, to azet nie chciał się mieszać w politykę i ja też nie uważam to za taki dobry pomysł.

**Comment by krystian3w** [comment]
To jak większość polityczna to lepiej wywalić i niech sobie xMapp da na strony "mentalnego" bana.

**Comment by hawkeye116477** [comment]
Albo może teraz pora na `Polską Listę Fałszywych Informacji Politycznych/Antytrollową` by @xMaap lub coś w tym stylu :smile:

**Comment by krystian3w** [comment]
Ale niech zrobi własne repo.

**Comment by hawkeye116477** [comment]
Ok, zmiany na razie cofnięte. Jak azet wróci to może część doda ponownie. A jeśli minie z pół roku i nic, to może po prostu zrezygnujemy z rozwijania tej sekcji, a @xMaap ją sobie włączy do swojej listy jeśli zechce.

**Comment by krystian3w** [comment]
Mnie ciekawi czy wyjątek nie przepuszcza przy okazji reklam, niby @gwarser  kontrolował ale kto wie, może bug w nowszych blokerach reklam.

**Comment by gwarser** [comment]
@krystian3w jaki wyjątek?

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KAD/blob/3df5029ada684dfac286251d878cd7ae516f1ee3/assets/other/kadfakewhitelist.txt#L10-L51

**Comment by krystian3w** [comment]
I w sumie one są do dupy jakiś piksel śledzący dopuszczony:

> ![obraz](https://user-images.githubusercontent.com/35370833/57183351-02af8b80-6eac-11e9-9017-12e33290c343.png) |
> ---- |

**Comment by gwarser** [comment]
No raczej `badfilter` niż takie whitelistowanie.

**Comment by xMaap** [comment]
@hawkeye116477 @krystian3w ja tu nie chce blokować portali lewicowych czy prawicowych, a tylko takie co sieją samymi fejkami. Wyjątek bym dał dla WP i Onetu 😛

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KAD/issues/889#issuecomment-489355258

To poprawione ale dziwnie wygląda:

https://github.com/PolishFiltersTeam/KAD/commit/77ba887fc480812923eda0556aee39ef59233ae4

a tak zrobione by działało teoretycznie może w AdGuard o ile wersja 3 umie zaczytać info z pliku bez serwera pośredniczącego `filters.adtidy.org`

**Comment by azet12** [comment]
Cześć. Zamysł tej sekcji nigdy nie był polityczny. Chodziło mi głównie o strony antyszczepionkowców i podobne, a że są one dosyć kontrowersyjne, dodałem je do oddzielnej sekcji. Pasuje mi to co zrobiliście, strony stricte polityczne typu Alex Jones raczej nie należą do tej listy i nie powinniśmy się nimi zajmować. Co innego jednak strona Jerzego Zięby, kolesia robiącego wyzysk na ludziach wierzących w leczenie raka witaminami. To już nie jest kwestia opinii.

**Comment by hawkeye116477** [comment]
Na WP jeszcze nie tak źle, co innego taka pewna strona na r, ale tutaj raczej nie widzę miejsca na polityczne sprawy, jakbym miał się za to zabrać, to pewnie sporo by wyleciało, ale z pewnych powodów raczej nie zrobię takiej listy.
