### ISSUE TITLE
Wygasłe

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#890]
```
9xa.pl
5gb-internetu-pakietyiframe.blogspot.com
dataasmierci.blogspot.com
datasmierci01.blogspot.com
localmeets.clu
```

**Comment by krystian3w** [comment]
skrypt i tak sprawdzi w niedziele jak się liczba testów nie skończy.

**Comment by hawkeye116477** [comment]
Pierwsza i ostatnia jeszcze aktywna, mają renewal do końca roku.

**Comment by hawkeye116477** [comment]
Tak generalnie to tych z blogspotem jakby nie sprawdza poprawnie, ma ustawioną zamianę subdomen na domeny (bo whois nie ogarnia subdomen), mógłbym teoretycznie zrobić wyjątek, by w przypadku blogspot tego nie robił, ale nadal jest jakby problem, bo te blogi zwracają status 200, czyli niby wszystko ok, bo jednak coś tam jest, podpięty jest iframe pod domenę, która nie jest już zarejestrowana. Tak więc te blogi nadal istnieją, nie zostały usunięte, skryptem raczej tego nie wyłapiemy, zresztą to by nie wyszło na dobre, jakby np. kod zepsuli i nagle po 10 minutach by naprawili, a my byśmy to usunęli...
Na razie te podpięte domeny mają zablokowaną rejestrację, ale niby teoretycznie mogliby skorzystać z jakiś innych, podmiankę zrobić, bo blogi nadal są. Tak więc @krystian3w, co robimy?

**Comment by krystian3w** [comment]
Zostaw blogi, ja tam mam "że nie można się połączyć" - nawet html strony się nie załadowuje, jakby zablokowali to bym miał komunikat nazwa niedostępna lub twórca z niej zrezygnował i kto pierwszy ten lepszy.
