### ISSUE TITLE
filmoteka.tv

### ISSUE THREAD

**Issue by xxcriticxx** [PolishFiltersTeam/KAD#894]
Firma zajmuje się prowadzeniem serwisu filmoteka.tv - niedorobionego dziecka starego dobrego alltuba. Serwis złudnie wydaje się dawać dostęp do filmów, jednak wykupienie na nim konta premium zapewnia wyłącznie dostęp do, uwaga, do stron na których, owszem są te filmy, ale trzeba osobno zapłacić za obejrzenie tych filmów. Stanowczo nie polecam, aby ktokolwiek planował w jakikolwiek sposób wiązać się z tego typu miejscami pracy, jeśli w ogóle takowe kiedykolwiek powstaną.

**Comment by hawkeye116477** [comment]
@krystian3w Już dodał 2 dni temu.

**Comment by krystian3w** [comment]
Tak, bo ten opis jest przerażający - 3 razy płacić i jeszcze nawet pewnie nie obejrzysz.
