### ISSUE TITLE
Widzieliście tą listę ?

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#901]
https://www.legalniewsieci.pl/aktualnosci/podejrzane-sklepy-internetowe

**Comment by hawkeye116477** [comment]
Tak, dawno dodane. A wczoraj ponownie przejrzane w celu dodania nowych `https://github.com/PolishFiltersTeam/KAD/commit/62cc218cee0c0c8eea2fb3924ba3045f4f8fc99c`.

**Comment by krystian3w** [comment]
I niby najczęściej jeszcze robią news z większościci co tam wpiszą.

 #884

**Comment by krystian3w** [comment]
Duplicate of #884
