### ISSUE TITLE
dragonist.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#903]
`https://dragonist.pl/content/3-regulamin-sklepu`

> 6) Sprzedającym – należy przez to rozumieć spółkę działająca w obrocie pod firmą Now Mobile LTD. nr 10881642, International House, 776-778 Barking Road, E13 9PJ London, United Kingdom,

**Comment by matkoniecz** [comment]
Co jest złego akurat w tym punkcie regulaminu?

Trafiłem na ten sklep internetowy, ale okazało się że mój plik hosts go wycina z powodu obecności na liście KAD.

Niestety nie jest dla mnie jasne czemu akurat ten kawałek regulaminu świadczy o ewidentnym oszustwie.

**Comment by krystian3w** [comment]
No trochę lipa jak to twój jakiś prywatny adresik a nic z domu nie wysyłasz.

**Comment by hawkeye116477** [comment]
Nie dają polskiej faktury i są zarejestrowani w Wielkiej Brytanii, zapewne próbują uniknąć płacenia VAT.

**Comment by hawkeye116477** [comment]
`https://bezprawnik.pl/dragonist-najem-telefonow/`
