### ISSUE TITLE
wartomiec.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/KAD#908]

**Comment by hawkeye116477** [comment]
@krystian3w Zerknij, ja tam nie widzę nic podejrzanego.

**Comment by krystian3w** [comment]
Bawią się w Spotify / ruskie całowanie anime...?

**Comment by krystian3w** [comment]
`https://www.wykop.pl/wpis/41614981/otwieram-sobie-strone-https-wartomiec-pl-porady-ku/`

Ale push blokowany przez EI.

**Comment by hawkeye116477** [comment]
@KonoromiHimaries Może jakiś opis co tu jest nie tak, sponsorowane recenzje :smiley:?

**Comment by krystian3w** [comment]
Ja tam mam nowe IP...

Jak z Google to otwarło wirusa to raczej lipa - można najwyżej zablokować to gdzie przekierowano po nowy iPhone bez foli czy Samsung Glaxy S10 (raczej nie widzę szans by kiedyś namierzyć gdzie ukrywa się złośliwy JavaScript).

**Comment by krystian3w** [comment]
@hawkeye116477 chyba ten pu-place.js tam się przypadkiem przypałętał i on może generować te brzydkie przekierowanie i push.

Więc można by plik dodatkowo banować dla ABP/AdGuard lub stronę, bo raczej porzucona i php pobiera datę do stopki z czasu serwera najpewniej.

**Comment by krystian3w** [comment]
@azet12 / @hawkeye116477 jak coś pierwsze blokuje `uBO filters` a drugie EasyPrivacy.

Więc najpewniej i najczęściej w AdBlock / ABP strona jest nieużywalna przez wirusa.

**Comment by hawkeye116477** [comment]
@krystian3w U mnie brak przekierowań.
`Ja tam mam nowe IP...`
U mnie niby jest stałe :smile:

**Comment by krystian3w** [comment]
Ale wrócą po deaktywacji uBo filters i EasyPrivacy (czyli ABP podatne, inna sprawa że filtr nie blokuje strony jak uBo, AdGuard może jak nie wychwycili nic podjerzanego w `mediaoaktree.com` i `tut-64.com`.

---

PS. Te skrypty robią rozciągnięty na całą stronę "link".

**Comment by krystian3w** [comment]
AdGuard jeszcze wcześniej blokuje pliki:

```
||yourservice.live^
||wmediaoaktree.com^
||tut-64.com^$third-party
```

czyli tylko pod ABP się nie da przeglądać.
