### ISSUE TITLE
filme.pl

### ISSUE THREAD

**Issue by xxcriticxx** [PolishFiltersTeam/KAD#910]
https://filme.pl/seriale-online/Britannia/s1e2/Odcinek__/22064

**Comment by krystian3w** [comment]
Niby się wczytują, czyli docięcie playera z góry co przekierowuje na `chili.com`?

Bo chyba nie chodzi by lista zwalczała piractwo i blokowała domeny z osadzonymi playerami do nieautoryzowanych kopii filmów.

**Comment by hawkeye116477** [comment]
Chilli jest niby ok, choć to chyba jednak robienie w balona, bo tam tego nie mają...

**Comment by krystian3w** [comment]
To może i warto nieco więcej z kodu wyciąć, bo szczerze to zostaje dezorganizacyjna luka.

**Comment by krystian3w** [comment]
Jak coś z playerów u mnie rusza `Ebd.cda.pl` inne jakby film zdjeli z hostingów lub problem po części związany z moim internetem.

----

I niby rusza też EN openload w 720p na dole.
