### ISSUE TITLE
leadmy.pl

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#914]
https://leadmy.pl/p/EjtQ/AbWi/s5hq?bId=qyZ7fRic

link ze strony
https://filme.pl/filmy-online/Kraina_Lodu__Przygoda_Olafa/2588

**Comment by krystian3w** [comment]
jest już, zablokować całą domenę?

https://github.com/PolishFiltersTeam/KAD/blob/45c251948666ddf1d81f5317207a1d822c2287bd/sections/natretne_lub_wprowadzajace_w_blad.txt#L2-L4

**Comment by MajkiIT** [comment]
![obraz](https://user-images.githubusercontent.com/11302675/59622551-26642380-9132-11e9-907b-1d2b5b805641.png)

Niestety cały czas widać reklamę

**Comment by krystian3w** [comment]
To z poprawką już nie powinno:


filme.pl##a[href*="://leadmy.pl/"]
filme.pl#?#.float-xl-left.col-lg-8 > div.mb-3.card:nth-of-type(odd):nth-of-type(-n+3):-abp-has(a[href*="://leadmy.pl/"])
filme.pl#?#.tabela_zrodla > div.mb-1.tabela_wiersz:-abp-has(a[href*="://leadmy.pl/"])

teraz próbuje wykryć link nie zważając czy to http / https / ftp.
filme.pl#?#.float-xl-left.col-lg-8 > div.mb-3.card:nth-of-type(odd):nth-of-type(-n+3):-abp-has(a[href*="://leadmy.pl/"])

**Comment by hawkeye116477** [comment]
Całej nie blokujemy, usunąłem parę dni temu ich z listy zgodnie z prośbą, gdyż jest to sieć afilacyjna, a to że ich mogą wykorzystywać do scamu, itd. to inna sprawa, wtedy trzeba pisać do nich i oni się tym zajmą. W tym przypadku akurat ten link prowadzi do normalnej legalnej strony, lecz wprowadzają w błąd.

**Comment by krystian3w** [comment]
Ale kler niby posiadają w bazie?

**Comment by krystian3w** [comment]
https://pl.chili.com/film/kler/14b2a02b-ea8c-4809-bfd1-e9b5a6abced2

**Comment by krystian3w** [comment]
https://pl.chili.com/film/kraina-lodu-2013/7781913a-0521-4f50-984b-187a67b9844b
https://pl.chili.com/film/goraczka-lodu-2015/f3b5f51a-c07b-4e44-be8c-9ff2219361e5

**Comment by hawkeye116477** [comment]
@krystian3w Ale „Kraina Lodu. Przygoda Olafa" to już chyba co innego i tego nie mają, miałem na myśli ten link z tabelki z wyborem playera. Jeżeli chodzi o Kler, to tak mają, w takim wypadku to wygląda na reklamę, a więc raczej to chyba nie do nas.

**Comment by krystian3w** [comment]
No to wtedy nagle musimy blokować per dokładniejszy URL - lipa.

**Comment by hawkeye116477** [comment]
@krystian3w Po prostu revert do stanu z przed poprawki, było chyba wtedy ok, a reklamy to do pana @MajkiIT.

**Comment by krystian3w** [comment]
No to linki https musiałyby być wycinane w liście reklamowej, bo na razie te po http:// niby są baitowe.

**Comment by hawkeye116477** [comment]
@MajkiIT https://github.com/PolishFiltersTeam/KAD/issues/914#issuecomment-502767459

**Comment by krystian3w** [comment]
Reklamą jest jak film dostępny w Chili i zgada się wersja, konto można za darmo założyć a @hawkeye116477  chyba wyszukiwarka działa nawet bez logowania?
