### ISSUE TITLE
giftdomain.site

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#916]
### Dodatkowe informacje mogące mieć znaczenie
Z reklam z alltube. Fałszywy konkurs.  `hxxps://www.giftdomain.site/gift/iphone/pl/?city=Bia%C5%82ystok&country=Poland&os_name=Windows&os_version=10&clickid=6bf77h9ejbzdu0697&trafficsource=7&lpkey=15eb61722184009101&campaign=1815&uclick=h9ejbzdu0`

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Zaparkowali.
