### ISSUE TITLE
naturalraport.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#925]
### Dodatkowe informacje mogące mieć znaczenie
https://www.glamour.pl/artykul/nareszcie-zgodnie-z-tym-trendem-nie-musimy-sie-juz-wstydzic-tradziku#mielibyscie-odwage-zamiescic-takie-zdjecia-brawo-kali-kushner

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
A link inny...

**Comment by hawkeye116477** [comment]
No raczej bez związku. Nie wiem co jest takiego oszukanego w linku zamieszczonym w komentarzu, ale jeśli chodzi o `naturalraport.pl/nonacne-opinie` to raczej jakiś fake news podobny do poprzednich zgłoszeń. Zapewne namawiają do czegoś co nie działa.

**Comment by krystian3w** [comment]
A dasz radę doprogramować pseudonaukę "dopuszczenie" `gh-pages`?

Niby dobrze jakby sama się umiała sprzątać, ja tam jedynie ogarnąłem by filtr nie przepuszczał w uBlock Origin np. trackerów z doczepioną nazwą domeny jakoś do zdjęcia lub jako plik pierwszoplanowy.

**Comment by hawkeye116477** [comment]
Zobaczymy, z tym to może być problem jako że jest w osobnej gałęzi, nie wiem dlaczego azet taki bałagan zrobił, zresztą z hosts podobnie, najlepiej jakby wszystko w jednym repo było.
