### ISSUE TITLE
prośba o nową lepszą whiteliste do kad

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/KAD#926]
bo [obecnie polecana](https://raw.githubusercontent.com/azet12/KAD/gh-pages/assets/other/kadfakewhitelist.txt) odblokowuje całe domeny, a powinna odblokowywać same reguły blokujące dostęp do stron.

przykładowa reguła wygląda tak
```
@@jerzyzieba.com
```

a powinno wyglądać tak
```
||jerzyzieba.com^$badfilter
```

**Comment by hawkeye116477** [comment]
@KonoromiHimaries Ale w uBO działa poprawnie, w przypadku innych adblokerów nie można zrobić innej. Masz tam zaincludowaną dla uBO `https://github.com/PolishFiltersTeam/KAD/blob/gh-pages/assets/other/kadfakewhitelist_suplement.txt`

**Comment by krystian3w** [comment]
`0 na 0` czyli trackerów nie odblokowuje, ostatnio tylko zklikwidowałem tam WWW z 4 adresów?
