### ISSUE TITLE
givemegreenbottle.icu

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/KAD#927]
wchodząc na strone
```
 hXXp://tvntl[.]pl/nasze-programy/magazyn-sportowy
```
przekierowuje mnie na:
```
hXXps://givemegreenbottle[.]icu/?p=gi3ginlemu5gi3bpgeytcmi&sub1=Ganedawa&sub2=tryn2&#
```

**Comment by krystian3w** [comment]
No to wirus siedzi w `||favoriteadrequest.com^`

**Comment by krystian3w** [comment]
A wirus bierze się z:

```
challengeforme[.]com/pystats.js?l=l&
```

**Comment by krystian3w** [comment]
Do przemyślenia czy po oczyszczeni sieciowym banujemy stronę i czy ktoś ma ochotę poinformować `tvntl.pl` o podejrzeniu infekcji z jakiegoś pliku masującego się za statystykami.

**Comment by krystian3w** [comment]
Chyba oczyścili stronę już.
