### ISSUE TITLE
detoxpolska.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#931]
```
https://detoxpolska.pl
http://store.planet-tachyon.com
https://www.gotsprouts.com
https://go.globalhealingcenter.com
```
Ktoś taki takie coś reklamuje
https://www.youtube.com/watch?v=dYW-IR7bCJA

**Comment by krystian3w** [comment]
@hawkeye116477  jak to zablokować w KAD HOSTS:

```
go.globalhealingcenter.com
```

?

Nie mogę do hostsplus, bo nie usunie mi skrypt. Czy olać na tym poziomie to?

**Comment by hawkeye116477** [comment]
@krystian3w `Nie mogę do hostsplus, bo nie usunie mi skrypt. `
Co ma skrypt usuwać, nie ogarniam :stuck_out_tongue:

**Comment by hawkeye116477** [comment]
@krystian3w Po prostu zrób nową sekcję kontrowersyjną plus :smile:
