### ISSUE TITLE
komornik23-gov.tk + zaplata42.tk

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#933]
zaplata42.tk/d/kkSDTdZy

To samo co https://github.com/PolishFiltersTeam/KAD/issues/930

**Comment by krystian3w** [comment]
#929 - może kontynuacja, @hawkeye116477 może wilcard dodatkowo dla użytkowników uBO?

**Comment by hawkeye116477** [comment]
@krystian3w Już wygasła.
