### ISSUE TITLE
fakturownia-pl.tk

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#941]
https://sirt.pl/fakturownia-phishing/

**Comment by hawkeye116477** [comment]
@krystian3w Nie wiem czy warto było to dodawać, skoro @MajkiIT to dodał potem do siebie, jakoś nie widzę sensu duplikowania jego.

**Comment by krystian3w** [comment]
No pytanie ile sobie też dodaje wersję hosts jak nawet jest to ledwie 1/3 listy reklamowej.

**Comment by MajkiIT** [comment]
@hawkeye116477 Według mnie lepiej dodać ... a jak coś to mogę usunąć od siebie.

**Comment by krystian3w** [comment]
To w czwartek możesz usunąć zassą się wszystkim nawet takim co raz na tydzień włączają PC.
