### ISSUE TITLE
shinden-anime.info

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#943]
### Dodatkowe informacje mogące mieć znaczenie
Strona serwuje reklamy, chyba za zadanie ma podszywanie się pod inną stronę - shinden.pl

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
@xMapp już to zgłaszał, może zapomniał podać źródła #942

**Comment by krystian3w** [comment]
Niestety coś padło i nie mogę dodać - przekierowania do przekrętów.

**Comment by krystian3w** [comment]
`scenbe.com`

**Comment by krystian3w** [comment]
Duplicate of https://github.com/FiltersHeroes/KAD/issues/942
