### ISSUE TITLE
streetrulez.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/KAD#953]
Brak danych firmy.

**Comment by krystian3w** [comment]
Niby opłacenie blik działa (ale wszystko za drogie do testowania), pytanie czy już przestali kraść przelewem.

**Comment by krystian3w** [comment]
Jedno dobre, że firma od szablonu się zwinęła a na ich stronie domyślny plik NGINX.

**Comment by hawkeye116477** [comment]
Co tu testować, firma nie ma danych, podają tylko jakiegoś pośrednika i zero opinii, mimo, że napisali, że działają od 2012.
