### ISSUE TITLE
Fake artykuły na FB - sponsorowane 

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#956]
```
||newsinsider.me^
||dspinner.net^
||faberville.com^
||gratissos.com^
||kitchencollectivecool.info^
||pulsebiznesu.xyz^
||pulse-biznesowe.xyz^
```

`https://dspinner.net/2019/08/13/zygmunt-solorz-zak-czlowiek-z-pieniadza/`

**Comment by hawkeye116477** [comment]
Tylko, że w zasadzie jest to już na liście reklamowej, uważam, że skoro Majki dodaje to do siebie, to nie wiem po co tutaj znowu zgłasza, tym bardziej, że reklamowa to lista domyślna, szerzej dostępna, chyba, że to miało trafić do hosts, ale to w takim razie nie do tego repozytorium.

**Comment by MajkiIT** [comment]
@hawkeye116477 Już usunąłem, bo ktoś dodał dużo postów, ale jak dodałeś to spoko. 

Dodaj proszę jeszcze, https://puls-sukcesu.net/

**Comment by hawkeye116477** [comment]
@MajkiIT Ja nie dodałem, tylko @krystian3w, ale ok :smile:

**Comment by MajkiIT** [comment]
@hawkeye116477 Aha no tak ... przepraszam @krystian3w Dziękuję
