### ISSUE TITLE
kupujemy.to

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/KAD#961]
unblock

**Comment by KonoromiHimaries** [comment]
@KonoromiHimaries konkurencja? kupowałem tam kiedyś i jest ok.

**Comment by hawkeye116477** [comment]
Podane mają też, że niby uczestniczą w programie Rzetelna firma, a ja ich nie widzę na liście. 
@KonoromiHimaries A kiedy to było? Możliwe, że od tamtego czasu pozmieniało się...

**Comment by KonoromiHimaries** [comment]
@hawkeye116477 rok, może dwa. mają tanie laptopy, ponoć z tej samej fabryki co lenovo

**Comment by hawkeye116477** [comment]
Niektórzy twierdzą też że to loteria, więc mogłeś mieć farta. Po uzgodnieniu z @krystian3w ustaliliśmy, że na razie to zostawimy. A jak kupisz od nich kolejny sprzęt, to wtedy daj znać :smile:.
