### ISSUE TITLE
Lidl przekręt

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/KAD#963]
https://mobtech.interia.pl/news-lidl-rozdaje-telefony-nie-daj-sie-nabrac-to-oszustwo,nId,3209911

Nie wiem czy widać wystarczająco URL lub czy już bloknięte.

**Comment by hawkeye116477** [comment]
No tak średnio widać.

**Comment by krystian3w** [comment]
Tu wcale https://www.komputerswiat.pl/aktualnosci/bezpieczenstwo/darmowe-smartfony-w-lidlu-to-oszustwo-nie-podawaj-danych-w-ankietach-rozsylanych/21tlkvb

**Comment by krystian3w** [comment]
Tu tylko e-mail: https://tech.wp.pl/lidl-rozdaje-samsunga-galaxy-s9-oraz-iphonea-x-uwazaj-to-pulapka-6425774548063873a

**Comment by AdamWr** [comment]
Może `climblike[.]com`
Link (wymaga usunięcia `[` `]` przed i po kropce):
`http://www.climblike[.]com/PL/PL_alegro/?uclick=1zwfftlp`

Wygląda podobnie.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/65155781-2542db00-da2e-11e9-838d-0bc49a72aec0.png)

![image](https://user-images.githubusercontent.com/29142494/65155803-2ffd7000-da2e-11e9-9a20-01dece5de1ab.png)

</details>
