### ISSUE TITLE
medium.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#971]
### Dodatkowe informacje mogące mieć znaczenie
`https://medium.com/@dawidwilgosz/magda-gesler-nie-%C5%BCyje-735134a99e8a`
Fałszywa informacja 

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
KAD nie filtruje pojedynczych fake newsów, ban na całe medium.com raczej będzie złą decyzją.

**Comment by krystian3w** [comment]
Duplicate of #969
