### ISSUE TITLE
worldofwarships.eu

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#972]
### Dodatkowe informacje mogące mieć znaczenie
`https://worldofwarships.eu/join/5619_PL1?pub_id=1079705&xid=15702166341309179360216520270531550&sid=SIDBALc6n3wCeeczAoJ-aCCh__5mh5_W9HtTl8MpDfQCsHv6YIfQrEyQiJ91oNRJb-9hYpEEC3ua4tymIOdS7Bg4hOwQwxFFXIeEyomfJmL9Z8EpPAYeDe0wP15_uTvnqPMx-7wXvpDKCtPj3VIOJFTaw&enctid=bxgzd18tiayp&lpsn=WOWS+videoback+new+standards+SOI&utm_source=networks&utm_medium=affiliate&utm_campaign=bn-adcash-wows-pl&utm_content=1079705`

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Raczej nie, a zgłoszony URL o przekierowanie za późno.
