### ISSUE TITLE
Malicious WWW

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#976]
### Dodatkowe informacje mogące mieć znaczenie
1. business-made-fun.com -> https://www.virustotal.com/gui/url/2a8a9b2cc294528f875bcda712e66132a4680375dc27b9858dd056435de23dc3/detection

2. businessdirectnessource.com -> https://www.virustotal.com/gui/url/fa6ac562e5831e3b08b0f16316f9306883b617450c94ba87f63e63d2db61ff9e/detection

3. charmedno1.com -> https://www.virustotal.com/gui/url/025c57f46f0c11bd95173364f7a933f83698b4d643f350e2a6512b7d3167ce39/detection

4. cribdare2no.com -> https://www.virustotal.com/gui/url/fa4b6ef24e61eaf92d315cb8e2b75f08562692c6923e1fddcec670182bee4064/detection

5. dowelsobject.com -> https://www.virustotal.com/gui/url/ed3690340471c799845f2d1997c2adb2819d74ae295b8cd82a30fbc7613d2bbf/detection

6. following-technology.com -> https://www.virustotal.com/gui/url/354901dabfa3662338c6cc6ec9c9d66ce0b34eddeee3bc302ca154c185290250/detection

7. forgotten-deals.com -> https://www.virustotal.com/gui/url/45a47c38d40e1c81d583f872b52736bfa112671bee98be28b98e05e18b56d3e9/detection

8. functional-business.com -> https://www.virustotal.com/gui/url/52cedcce895af98b740ac178184ee2ce21645e551a1e63001dc40d43e6dd8fd1/detection

9. housedman.com -> https://www.virustotal.com/gui/url/263e08a37e1143e3e266e4f0256a97437033738460484ef4a00c1bb7cd9a5b48/detection

10. industry-deals.com -> https://www.virustotal.com/gui/url/5d762d0c42d7ab1f7be98d69b3be8e63e4edac5208687cb543188ffd148141e7/detection

11. listennewsnetwork.com -> https://www.virustotal.com/gui/url/e6fd563869761d8e24e979eba9141d8212b5151b6ec9967d7f2e0e631a4971cd/detection

12. phoneysoap.com -> https://www.virustotal.com/gui/url/fc30cc989dcdc8d493f283913a877b13b259a341d20f63cface68f84dedd91ca/detection

13. posed2shade.com -> https://www.virustotal.com/gui/url/cd4baf92244a06cfcc7692a8bb67485f0e6bec01976af66d6c81c55791e8b977/detection

14. rehabretie.com -> https://www.virustotal.com/gui/url/8cea0d7823261dbae18143f466cda8df7762c600a9935ab48c64a7951d260582/detection

15. speedynewsclips.com -> https://www.virustotal.com/gui/url/31d069fbf8ad72696c3743b8eea9642614d527f51d29519c420c40356f862fb3/detection

16. teatac4bath.com -> https://www.virustotal.com/gui/url/3f03fcd5ff37f56e1c3fcfc2dbda6aafc31352bd38573fd0dfca71bd72b5a672/detection

17. unite3tubes.com -> https://www.virustotal.com/gui/url/a91ea124d55869d9be93a4b55ad04f209f595c1e0408afb716107f1fdb6a6daa/detection

18. unwashedsound.com -> https://www.virustotal.com/gui/url/1988e6a64953922e1d0a7c2cb3edb057c1682e181da4f90ab72f3b9d624283d9/detection

19. arm2pie.com -> https://www.virustotal.com/gui/url/c7b75768508445b4de8fb7b3c9e483bb79f7e910500a65c0a352f1f40690f41d/detection

20. brittlefilet.com -> https://www.virustotal.com/gui/url/21c2918b9aaf124c97d7d0f0ccbf02bcc33a66e5d5d5418ed7cdea68beed4323/detection

21. cigape.net -> https://www.virustotal.com/gui/url/69466942231a34ab1ce66c9b6ac9cb600fa69929eff8f5cf89b50cd26f94f326/detection

22. crisptic01.net -> https://www.virustotal.com/gui/url/0180ee164dec38f3b4a5b0651138135ead3564528474bc233c397243fec28d1c/detection

23. fliteilex.com -> https://www.virustotal.com/gui/url/7cce6bf08ec53fccf66321043b820a08b2c0683fe7ff9f5bbab9d2726c8856a4/detection

24. itemagic.net -> https://www.virustotal.com/gui/url/517c81d7adea6890f94d9fda016f41ace048a6626fb36c0a67c255cee9bfbe4d/detection

25. micraamber.net -> https://www.virustotal.com/gui/url/ea88c8353b3aa7dee84e2a31594a2c7355b46f41ba967db53ba4f39577eef8ee/detection

26. mimicrice.com -> https://www.virustotal.com/gui/url/dfa1da024589a1507c58731a730f5c92f912c6383baa5938aa03c16b9c553ae1/detection

27. rampagegramar.com -> https://www.virustotal.com/gui/url/e822a623891207f0f36b1c5fae31a4838c79e8b74fcfb687a54a290f2d95c241/detection

28. rubi4edit.com -> https://www.virustotal.com/gui/url/771a3b44169a177aad7441d7a13281c7bdf2d99a1c0781cfcbb05bb197d4e9b8/detection

29. rubiccrum.com -> https://www.virustotal.com/gui/url/922f54ea05909b514abc7184172ac3e3de61158cbfa86bba61eba3f47116405a/detection

30. rubriccrumb.com -> https://www.virustotal.com/gui/url/3256716f2155f5b38ac4fb5f54c5f3f15a8af43ff24454e2b97fc34c79957e34/detection

31. team4heat.net -> https://www.virustotal.com/gui/url/3c2d77982bd79f4ea16e7099aa7c6f5ffdde3af68c56caa189ec9b3b4abbf01d/detection

32. tropiccritics.com -> https://www.virustotal.com/gui/url/6f08ad5d0764c02a1e360ccc0ac64add7cdd7d2a3c39d8f32c7591fc2544d20a/detection

33. wpcache-blogger.com -> https://www.virustotal.com/gui/url/7afd0489fcebed783309dcaf50c434c84b59498a7aacff86e4df2d49a9422813/detection

34. ads.akeemdom.com -> https://www.virustotal.com/gui/url/d178dac0a32918fb7792de35145d6ce6927a8e3e2514cfaa233b332d65961132/detection

35. nthost.shacknet.nu -> https://www.virustotal.com/gui/url/fdc36d38c6401d75cdfd93addd07da3e7df0d43c0134cfbabb9f7cc4968ba073/detection

36. tunga.homedns.org -> https://www.virustotal.com/gui/url/2def023967e8e28fd59056ceaaa4c98b661c5d9d207ad9a55533b72fc889bfeb/detection

37. prosoccer1.dyndns.info -> https://www.virustotal.com/gui/url/7ef51bd1dec997e89624ef966056a3ef7af33a2803c09c8360bbabbabf1fd9c8/detection

38. prosoccer2.dyndns.info -> https://www.virustotal.com/gui/url/d7a0d24e14cc760c2654b075deb966a5c8be4f1d9f75eac1aa08026455d8999f/detection

39. nav1002.ath.cx -> https://www.virustotal.com/gui/url/42477b4a72f5274cada115795eb1c02e8f511a238145f6e246d278d90abc8ac8/detection

40. pininfarina.dynalias.com -> https://www.virustotal.com/gui/url/3fd6c6062e451de8b6145f32a210ae5591a83d96b4db162cd2563de61c6a92a9/detection

41. supermegacool.bit -> https://www.virustotal.com/gui/url/fa4b6ef24e61eaf92d315cb8e2b75f08562692c6923e1fddcec670182bee4064/detection

42. ad-servicestats.net -> https://www.virustotal.com/gui/url/598946ec3327c026474edcf0454f4b664bbbddcba00c543b0915491e798e8824/detection

43. ad-noise.net -> https://www.virustotal.com/gui/url/a7fbf2c1f9ee6486ffd3128777825a8dd156028b55b81d695a03af9f8ca23c79/detection

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Z 75% offline, chyba szkoda na to i męczyć whois, z 4 zbanowane przez AdGuard DNS, może około 5 zwraca białą stronę lub jakiś error 404 lub coś o przejęciu przez Kaspersky, 1 coś otwiera jakieś chińskie badziewie.
