### ISSUE TITLE
forfollow.net

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/KAD#979]
https://zaufanatrzeciastrona.pl/post/uwaga-na-atak-panoszacy-sie-wlasnie-m-in-na-polskim-twitterze/

**Comment by hawkeye116477** [comment]
Ale to już jest na Oficjalnej PL liście... Trochę dziwna polityka, skoro dodaje tam, to raczej tu już niezbyt trzeba, bo Oficjalna jest niemalże wszędzie domyślnie.

**Comment by MajkiIT** [comment]
Usunę jak dodacie. Po 2 dniach... spoko luz :D

**Comment by hawkeye116477** [comment]
Po prostu nie lubię/nie widzę sensu w dublowaniu, zwłaszcza, że pewnie więcej osób ma „Oficjalną PL". Tak czy siak, ok, niech mu będzie :smiley:
