### ISSUE TITLE
itorrenty.org

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/KAD#990]
### Link bezpośredni 
`https://itorrenty.org/regulamin`
### Dodatkowe informacje mogące mieć znaczenie
Strona nie ma regulaminu, przy rejestracji wymaga SMS. Można to w jakiś sposób zweryfikować?

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Jak coś nie działa opcja "przelew" a SMS 21 zł + VAT twierdzą, że zeżre tylko 2,46 zł.
